### ISSUE TITLE
Add warning at user creation that users should backup their password

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1056]
## Abstract

Rotki accounts are local and encrypted by a user password. Much like a crypto account, If this password is lost, then access to the account is lost. For this purpose the user must acknowledge and understand at the creation time that their password needs to be backed up somewhere.

## Task

At user creation show a warning, or a prompt explaining that the user accounts are local and that the password needs to be backed up. To proceed the user would need to acknowledge this.

**Comment by BvL13** [comment]
What happens if a user has a pro account and paid for it. Can he somehow regain access?

**Comment by BvL13** [comment]
Is integration with services like 1password an option?

**Comment by isidorosp** [comment]
> Is integration with services like 1password an option?

Hi @BvL13 ,

What kind of integration did you have in mind? You can always store your rotki password in your password manager of choice (e.g. 1Password) and then just either manually retrieve it from the application / browser extension and copy paste, or type it in yourself. Like so:
https://support.1password.com/copy-passwords/

Eventually the plan is to allow rotki to run via a browser instead of just within Electron, in which case your password manager should be able to identify the login screen and propose your password automatically, but we're not quite there yet.

Some password managers (e.g. lastpass https://support.logmeininc.com/lastpass/help/use-the-lastpass-desktop-app-for-windows-lp010124#Add) allow you to define a set of "key sequences" that will fire when you open an application. If you identify the right sequence of key strokes when Rotki opens, that could also work to allow the auto-fill of your passwords. I don't know if 1Password has similar functionality.

**Comment by BvL13** [comment]
I was not aware that these services usually work on a browser basis, but it makes sense.
So the idea is, that during the registration process when I get asked for my password, it also asks if I want to store it in an existing service I run. I understand though that this is difficult and as you mention not every solution has such an API solution.  Sounds like the keystrokes are the closest solution to the challenge. Thanks.

**Comment by LefterisJP** [comment]
Note that any integrations with such tools would probably go to a different issue. This issue is mostly for some sort of warning in the front-end at user creation

**Comment by kelsos** [comment]
@isidorosp @LefterisJP Would it make sense to add some kind of checkbox there that the user has to actively check before enabling the create button? To bring their attention to the matter?

**Comment by LefterisJP** [comment]
@kelsos Perhaps. Something like:

"I understand that if I lose my password I lose access to my data. I have created a backup of the password"
