### ISSUE TITLE
Polkadot/Kusama support

### ISSUE THREAD

**Issue by yangwao** [rotki/rotki#1081]
## Abstract

As [Kusama](https://kusama.network/) growing bigger I see the potential for Rotki to capture new userbase and it will help to adapt for other para/solochains based on [Substrate](https://substrate.dev/)

[I know I'm still the one 😅](https://twitter.com/yangWao/status/1271007756967911424) and also that bothers me 🤗, let's change it.

## Motivation

I'm going to stake KSM and I would like to see P/E for example, account commission fee and yield :)

[Actual Staking Interface from polkadot.js.org](https://polkadot.js.org/apps/#/staking)
![image](https://user-images.githubusercontent.com/5887929/84368895-70ada280-abd6-11ea-96b2-84906477687d.png)

## Specification

This could be really wild and I don't have anything specific in my mind right now!
Just created this as coordination issue so it could potentially attract others to play with it 😇

---

# Grant

For Kusama support we are receiving a grant to implement it in two milestones. Once both milestones are finished we can close this issue. Source: https://docs.google.com/document/d/1OwdIcrAqDxMpDcIRTE7wbJU0aO2gGfZplyEI7s1oWPo/edit#

I will link all sub-issues here and in the OP so they can be easily followed:

## Milestone 1

* Have the Rotki team study and understand Kusama Network better, so that we can figure out what is needed from a technical perspective in order to accomplish the following objectives.
* [#1919] Add a new blockchain type (KSM) in Rotki and allow import of addresses for it. Use the default nodes ran by web3 foundation and Parity: https://guide.kusama.network/docs/en/kusama-endpoints
* [#1920] Add a new setting for the users to provide a custom endpoint if they run their own node and use it for balance query instead of the defaults.
* Perform balance queries for the imported addresses and show them in the Rotki UI 

## Milestone 2

* Perform transaction history query for the imported addresses by using the a KSM node and show them in the Rotki UI in the blockchain transactions component
* Detect if any of the user’s addresses are actively staking, and if yes show how much profit they have made (counting historical KSM prices) and show expected profits in the UI. Also calculate profit for addresses that have staked so far in the past.
* Create a new UI component for staking in Rotki. There multiple blockchains that allow staking would be shown and KSM would be one of them. Show staking details in this component.

**Comment by LefterisJP** [comment]
Hey @yangwao, thanks for the issue!
As I asked in Twitter isn't Kusama a testnet? Shouldn't this issue be for polkadot mainnet instead? Perhaps there is something I am misunderstanding but why would you want accounting/portfolio tracking for a testnet?

**Comment by yangwao** [comment]
@LefterisJP Well, technically it's Litecoin to Bitcoin, but it has users. 😅 
KSM went from $2 to almost $5 and over, so I think if there is value, it's worth accounting it.

There is bleeding-edge governance tested at Kusama first. A lot of integrations are being set there. Polkadot will eventually adapt those things latter.

I think it's a test net with value.

**Comment by LefterisJP** [comment]
I was not aware of that. If it has value it definitely makes sense to be tracked. Thank you for that info @yangwao.

**Comment by adrien-be** [comment]
+1

**Comment by LefterisJP** [comment]
This issue is for blockchain integration with Substrate-like blockchains. Not simply for querying balance of DOT/KSM if it's in an exchange. If it's just the latter it's supported in develop and will be in the next release.

**Comment by adrien-be** [comment]
Great news. Thx for the update.

**Comment by LefterisJP** [comment]
For Kusama support we are receiving a grant to implement it in two milestones. Once both milestones are finished we can close this issue. Source: https://docs.google.com/document/d/1OwdIcrAqDxMpDcIRTE7wbJU0aO2gGfZplyEI7s1oWPo/edit#

I will link all sub-issues here and in the OP so they can be easily followed:

## Milestone 1

* Have the Rotki team study and understand Kusama Network better, so that we can figure out what is needed from a technical perspective in order to accomplish the following objectives.
* [#1919] Add a new blockchain type (KSM) in Rotki and allow import of addresses for it. Use the default nodes ran by web3 foundation and Parity: https://guide.kusama.network/docs/en/kusama-endpoints
* [#1920] Add a new setting for the users to provide a custom endpoint if they run their own node and use it for balance query instead of the defaults.
* Perform balance queries for the imported addresses and show them in the Rotki UI 

## Milestone 2

* Perform transaction history query for the imported addresses by using the a KSM node and show them in the Rotki UI in the blockchain transactions component
* Detect if any of the user’s addresses are actively staking, and if yes show how much profit they have made (counting historical KSM prices) and show expected profits in the UI. Also calculate profit for addresses that have staked so far in the past.
* Create a new UI component for staking in Rotki. There multiple blockchains that allow staking would be shown and KSM would be one of them. Show staking details in this component.

**Comment by adrien-be** [comment]
Amazing news. Congrats.

**Comment by vnavascues** [comment]
# Milestone 2
## Epic 1:  transactions history query
- Support Kusama transactions via an indexer
- Support Kusama transactions via own node
## Epic 2: staking
- Support Kusama staking via an indexer
- Support Kusama staking via own node

**Comment by bloxster** [comment]
Looking forward to be able to query also **Polkadot** network balances.

Big thanks to the team for the incredible work done so far.

**Comment by LefterisJP** [comment]
This has been implemented. Both polkadot and KSM balances are supported.

We still miss specific things such as transactions and staking info but there are issues for those.
