### ISSUE TITLE
Support ethereum NFTs

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1097]
## Abstract

There is a big market for NFTs in ethereum and an untapped need to track and account for them.

There is crypto collectibles marketplaces like https://opensea.io/

We should be able to account for them

## Task

Figure out a way to autodetect NFTs owned by an ethereum address. A good start would be ERC721 tokens. 

For ERC721 tokens etherscan offers an events endpoint to get a list of ERC721 token transactions per account: https://etherscan.io/apis#accounts

We could use that to see what ERC721 a user has and show their balance after processing them all.

There is also the ERC1155 standard for NFTs

**Comment by isidorosp** [comment]
Just offloading some resources here

sub-graphs
https://thegraph.com/explorer/subgraph/blockrockettech/nft-tokens
https://thegraph.com/explorer/subgraph/wighawag/eip721-subgraph
https://thegraph.com/explorer/subgraph/nategeier/mintbase (mintbase-specific)

Other marketplaces
https://www.cargo.build/
https://niftygateway.com/

**Comment by emansipater** [comment]
Strongly in support of this feature, especially since ENS names are also ERC721 tokens now

**Comment by yabirgb** [comment]
+1 to this

**Comment by isidorosp** [comment]
This may be a useful resource ( js-based though) https://github.com/vasa-develop/nft-tokenlist

**Comment by LefterisJP** [comment]
+1 to this  (not as product owner, but as a rotki user)

**Comment by yabirgb** [comment]
Rarible has an API endpoint to get all the NFTs that an account has https://api-reference.rarible.com/#operation/getAllItems

**Comment by rkalis** [comment]
I understand that this is a significant undertaking so don't take this as an urgent request, but something that would be great to have with NFT support would be NFT value approximation. 

The most simple version could try to see if there are NFTX/NFT20 pools (e.g. [PUNK](https://v2.nftx.org/redeem/0x269616d549d7e8eaa82dfb17028d0b212d11232a/)) for a certain NFT asset and assume that all the NFTs of that type have the value of the NFTX vault token. So in case of cryptopunks that would mean that all cryptopunks would be valued at ~50ETH (the value of the PUNK ERC20).

Of course this is not an ideal approximation, both because these pools are illiquid (so you can't trade e.g. 100 punks at the same time for that price) and because the values of individual NFTs vary greatly. But imo it would be better than not having any valuation for NFTs.

I currently add my NFTs under manual balances and use the NFTX pool tokens (e.g. 2 COOL tokens indicates I own 2 coolcats), which is a more manual version of what I proposed above.

Like I said, probably not a priority though, but wanted to throw this out there.

**Comment by LefterisJP** [comment]
Opensea has an api it seems too: https://docs.opensea.io/reference/api-overview

**Comment by LefterisJP** [comment]
This is a prime example of a premium feature. But will add it also for free verison but with a limit of X NFTs. Thinking of 5. Just to see what's possible.

**Comment by LefterisJP** [comment]
Need to think on ways to report price of an NFT. We should:

1. Manually: Let user add their own price. They know best.
2. Automatically:
    i. Take the last price of the NFT.
    ii. find the prices of the most similar items
    iii. n the NFT market, there are pools, where people deposit their NFT and receive a token. The pools have an implied price.
        Example https://nft20.io/asset/0xcccbf11ac3030ee8cd7a04cfe15a3718df6dd030 and NFTX as @rkalis mentioned.
        
 The "automatically" part is input from @bokkypoobah

**Comment by tgerring** [comment]
> 2. Automatically:
>    ii. find the prices of the most similar items

I have been building a spreadsheet of my NFT purchases/sales so wanted to weigh in on this item specifically, since--to some degree--all art is subjectively valued. However, not all NFTs are art in the purest sense, since some also have utility function. If it saves you any time, I have broadly organized my collection into a few categories:

1. Fine art (i.e. Beeple)

Because the market for fine art will be more limited, it will be more difficult to establish a price, as there is relatively little information available--even bots don't bid. The last sale price for the specific item is a decent metric, but estimating future automatically will certainly be impossible. If you buy a bundle, the issue is complicated further.

2. PFP (i.e. CoolCats)

These projects tend to be a bit easier to establish a price, since there are ~10K items trading and a floor price established.  Floor price should represent instant liquidity, even for the "worst" avatars in a collection, however, there may exist trait floors within the collection. For example, Zombie & Ape CryptoPunks fetch base prices in thousands of ETH and so it would be unfair to say these are worth the same as "standard" Punks available at the lowest prices. On the other side of things, at OpenSea, there may be items listed for near unlimited sums (i.e. quadrillions of dollars). My recommendation would be to fit some statistical model to the prices in the collection and pick a percentile you feel the item represents. In general, people have a feel if their PFP is a 0/20/40/60/80/100% item.

3. Game (i.e. Parallel)

Games can have collection sizes in the hundreds of thousands or millions, and tend to have far more liquidity due to the high edition size on each game piece. Here, relying on last sale price for individual items is more reliable and there is no need to find "similar", since there tend to be multiple copies of the same item available for sale at a variety of price points. There is a true order book in many cases and prices can move within hours or minutes.

I hope this is helpful in avoiding implementing some incorrect assumptions about how easy it will be to implement automatic art pricing, especially as some items may have utility, such as creating other items. Whatever you end up implementing (even just manual pricing) would be greatly appreciated!

**Comment by isidorosp** [comment]
This site/app seems to be doing NFT valuation and also provide an API, might be interesting to potentially integrate
https://nftbank.ai/landing
![image](https://user-images.githubusercontent.com/27592/129195978-8bb9d006-b503-44a2-b3ad-0003f48fc381.png)

![image](https://user-images.githubusercontent.com/27592/129195959-0fe26d79-2e39-4f69-a980-7416e9acca2e.png)

**Comment by LefterisJP** [comment]
# Tracking NFT balances in the dashboard

As discussed in the standup we still also want to track nft balances in dashboard and statistics for this release. So reopening the issue with some more things to do.

WIP -- will still edit more.

## NFT Ids

Figuring out a unique id for each nft. Since they will be saved in the user DB we can probably have even a user specific id, but probably should look it up in more detail to find a unique id per nft

## Show balances of NFTs

### Request

GET /api/(version)/nfts/balances

parameters: async_query - optional

### Response

```json
{
    "result": {
        "0xeE3766e4F996DC0e0F8c929954EAAFef3441de87": [{
	    "id": "unique id",
            "price_eth": "0.025",
            "price_usd": "250"
	}, {
	    "id": "unique id 2",
            "price_eth": "0.015",
            "price_usd": "150"
	}],
    },
    "message": ""
}```
