### ISSUE TITLE
Rotki does not follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by monomachos** [rotki/rotki#1105]
Rotki uses a non-standard ~/.rotkehlchen directory. The [standards compliant](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) directory to use is  $XDG_DATA_HOME/rotkehlchen (default: ~/.local/share/rotkelchen).

A [growing number](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Support) of projects have adopted this standard because of its cleanliness and portability.

Rotki should use the XDG compliant directory for new installations. For compatibility, it should detect the non-XDG directory as a fallback.

**Comment by LefterisJP** [comment]
Fair point. We should implement this at some point!

**Comment by LefterisJP** [comment]
Perhaps we should consider the equivalent OSX directories for this too. And same for Windows whenever we handle this issue

**Comment by kelsos** [comment]
I am guessing also an automatic/or manual migration to the new structure would also make sense right?

**Comment by LefterisJP** [comment]
Yes it would be an automatic migration, based on some DB flag. As a "hack" we can just +1 the DB version and utilize the DB upgrade logic. At that upgrade the directory should be automatically moved to the new location.

Which is why it would be preferrable to figure this out for the other OSes too. Even though we can have multiple upgrades for multiple OSes.
