### ISSUE TITLE
[website] can't change password?

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1139]
I've logged in online (thanks a lot @LefterisJP for help resetting my password, since I never got an email from the automated reset), but now I don't see anywhere under https://rotki.com/home/ to change my password - am I missing something or is it not implemented yet?

**Comment by LefterisJP** [comment]
@aspiers This should be fixed in the website now. Please let me know if this is the case or not.

You should now find a password editing field in your account details, requiring to input the old password and the new password two times.

Also I checked and the password reset via email seems to "work fine for my account" ™

**Comment by aspiers** [comment]
Worked great, thanks!
