### ISSUE TITLE
Document tax calculations

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#1240]
A friend of mine (who is a tax accountant) and I recently took a look at rotki to analyze its usefulness for reporting taxes in Germany. We really liked that fact that a user's privacy is preserved, that the code is open source and the many exchange-integrations. However, once we took a closer look at the reports, many questions arose. Just so you're aware: Our tax reporting test account mainly used exchanges and no defi or manual balances.

- What accounting strategy is rotki using (e.g. LIFO, FIFO, etc.)
- Does rotki assume a start balance of 0 coins?

Additionally to these rather simple questions, we also asked ourselves:

## start balance of a successive year

Say we bought and sold some crypto in 2017 and did some trades on Coinbase. We did similar things in 2018.
Now, when we ask the tax reporting tool to calculate 2018, is 2017's end balance (so the balance on 31.12.2017) being taken into account when e.g. FIFO is used? Or, is the tool simply assuming to start its balance from zero again?

## Unclear calculation in csv exported data sheet

We then took a look at the csv file. Unfortunately, we weren't able to find an explanation about what the different columns meant. Point in case, the `is_virtual` column. We noticed that it's checked as `TRUE` in trades where no fiat is exchanged.
It would have been nicer to find an explanation on the website for example. Also: From what I understand, `is_virtual` is German tax-law specific, right?

We were also quite surprised, about the differences in `received_in_asset`  and `taxable_received_in_EUR`. Mainly, because in our export `taxable_received_in_EUR` usually was a little less than `received_in_asset`. We ended up having to manually check transaction on an exchange to find out that the exchange's transaction fee had automatically be subtracted from `taxable_received_in_EUR`. In our opinion, it would have been nicer if e.g. the transaction fee had been included in the csv or if the documentation had explained this explicitly.

## Arriving at rotki's general profit loss calculation

We were able to figure out most to ourselves. However, when it came to reproducing rotki's general profit loss calculation, we failed. We converted the csv to an excell spreadsheet and then applied the following calculation

`=SUM(taxable_received_in_EUR)-SUM(taxable_bought_cost_in_EUR)`

However, this value turned out to be different from what rotki calculated us.

## Proposal

What I guess would be kinda useful from a tax accountant and user perspective is adding a document, either to the rotki app or its documentation, outlining its tax calculation and explaining the fields involved.

I'd be happy to contribute to that proposed effort. In total, we really liked rotki and would like to use it in the future! So if you're able to answer some of the questions above, we can start writing some docs.

**Comment by LefterisJP** [comment]
Hey @TimDaub!

Happy to hear you like and are trying Rotki out. Just so you know we are also in Berlin and Rotki was started as a tool to deal with German taxes.

We are trying to gather feedback and requirements from accountants too in order to improve the tool and make it useful also for them as we would like to expand into the non-retail market at some point.

So now to your questions:

> What accounting strategy is rotki using (e.g. LIFO, FIFO, etc.)

It's FIFO. We want to offer LIFO customization too but that's not implemented yet: https://github.com/rotki/rotki/issues/44
 
> Does rotki assume a start balance of 0 coins?

At which point in time? At the beginning it's all zero yes. But you should somehow give a trade with which it all started. So if your crypto journey started by buying into the Ethereum sale then you should enter a manual trade for this.

> Say we bought and sold some crypto in 2017 and did some trades on Coinbase. We did similar things in 2018.
Now, when we ask the tax reporting tool to calculate 2018, is 2017's end balance (so the balance on 31.12.2017) being taken into account when e.g. FIFO is used? Or, is the tool simply assuming to start its balance from zero again?

It is taken into account. If data exist from 2017 but you asked 2019-2020, Rotki will first process all historical data it can find, but then start calculating for your tax report from 2019. This is a requirement as you need to be able to account for where the coins came from and at which price.

Additionally as you probably know in Germany there is the 1 year rule for holding crypto in a FIFO order after which it is no longer taxable. Rotki takes that into account.

> Point in case, the is_virtual column. We noticed that it's checked as TRUE in trades where no fiat is exchanged.
It would have been nicer to find an explanation on the website for example. Also: From what I understand, is_virtual is German tax-law specific, right?

Very good point. This information should be put into the usage guide, and specifically into the [tax report section](https://rotki.readthedocs.io/en/latest/usage_guide.html#creating-a-tax-report). But it's not there right now.

So `VIRTUAL` is the way we are trying to deal with the crypto to crypto trades. In Germany and in many other countries (even the US afaik) trades between crypto are taxable. The rate at which profit is calculated should be the rate of that crypto coin against your profit currency. For us the EUR.

So say you sell ETH for BTC at some point. This creates two virtual trades. Selling ETH for EUR, and buying BTC for EUR.


> We were also quite surprised, about the differences in received_in_asset and taxable_received_in_EUR. Mainly, because in our export taxable_received_in_EUR usually was a little less than received_in_asset. We ended up having to manually check transaction on an exchange to find out that the exchange's transaction fee had automatically be subtracted from taxable_received_in_EUR. In our opinion, it would have been nicer if e.g. the transaction fee had been included in the csv or if the documentation had explained this explicitly.

Good point.

> We were able to figure out most to ourselves. However, when it came to reproducing rotki's general profit loss calculation, we failed.

For this I would need to actually go through the logs and the report to see how you calculated and what the difference may have been.

> What I guess would be kinda useful from a tax accountant and user perspective is adding a document, either to the rotki app or its documentation, outlining its tax calculation and explaining the fields involved.
>
>I'd be happy to contribute to that proposed effort. In total, we really liked rotki and would like to use it in the future! So if you're able to answer some of the questions above, we can start writing some docs.

Thank you! That sounds like a great idea. As I said above that would belong in the usage guide. Perhaps in the tax reporting section: https://rotki.readthedocs.io/en/latest/usage_guide.html#creating-a-tax-report

But it would need to be expanded with more details. The source for this is in github in this repo: https://github.com/rotki/rotki/blob/develop/docs/usage_guide.rst


-----

Thanks a lot for all the feedback you provided! We want to work on the tax report section as it has been ignored a bit in the past releases. We have focused a lot more on the portfolio tracking and especially DeFi as this is what most of our users are asking at the time.

**Comment by A2be** [comment]
I'll just offer that this ^^^^ is the kind of thing that I think is important to my own potential (am subscriber; but haven't really used it yet) use of Rotki.  The tax issues, accounting issues, etc. are all more important for me than is portfolio tracking and DeFi wonderfulness.

Not to say which set of interests should have which weight.  Just wanted to log that Tim Daub and his accountant aren't the only users who are currently finding this aspect of Rotki quite important.
