### ISSUE TITLE
Premium user API Credentials fail 

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#1245]
## Problem Definition

Premium user API Credentials fail on "API Keys" page, "Exchanges" tab in rotki app v1.6.1 (running on Win10 PC), yet the same API Key and API Secret were accepted successfully on the "Rotki Premium" tab in the app, when using the "Setup" function.

Error msg given by the app is 
```
Exchange Setup Error     
Error at setup of [REDACTED]: Provided API Key is invalid
```

Expected behavior was that the valid API Key and Secret would be accepted, and allow me to test populating Rotki app with data from an exchange via the API.

This error sequence is easily repeatable.

Re your request here: 
```
Rotki also logs debug information to the `rotkehlchen.log` file. Please attach it to the
issue as it may help us find the source of the issue faster.
```
I would be happy to do so, but don't know how to find the log file you mention.

### System Description

I'm not sure how to get this stuff on my Windows machine.  Frankly, not even sure if Rotki app installed somewhere when I clicked the downloaded .exe file, or is merely running out of my `downloads` folder, and never installed like an installed program (or more modern) Windows app.

Here's some info from "systeminfo"
```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

**Comment by LefterisJP** [comment]
Hello @A2be. Thanks for using Rotki and for getting a premium subscription~

Let me see if I understand correctly.

(1) You have purchased a premium subscription
(2) You succesfully set the rotki api keys on the premium part of the app? As seen below in the screenshot

![2020-07-30-202420_476x606_scrot](https://user-images.githubusercontent.com/1658405/88959792-dc40f180-d2a2-11ea-9c48-0936819ae572.png)

(3) You tried to setup an API exchange key so that you can pull data from an exchange.

Step 3 fails for you? What exchange did you try to setup an API key for? Are you sure it's a valid API key?

> I would be happy to do so, but don't know how to find the log file you mention.

You can find the log location on the top menu. `Help -> Logs location`

**Comment by A2be** [comment]
Yes, your restatement is correct on nos. 1, 2 & 3.

Also, found the logs.  Can I send those to you over a more secure channel?  Say, Telegram?

**Comment by isidorosp** [comment]
@A2be You need to get a specific set of API Key + Secret from each exchange you want to connect. You cannot plug in the "rotki premium" API Keys to connect an exchange. The rotki premium API Keys are simply to enable the enhanced features within rotki that correspond to a premium subscription (e.g. the "Statistics" components).

For example, if you want to connect Kraken to rotki, you need to go to your kraken account and generate a set of API Key + Secret (make sure it's read-only, rotki doesn't want "execute" privileges), and then input those details into the kraken sub-page of Api Keys -> Exchanges.

**Comment by LefterisJP** [comment]
@A2be for the exchanges it's exactly as @isidorosp described.

You can send the logs over telegram for sure, or a discord pm. Telegram: https://t.me/rotkichat. Discord: https://discord.gg/aGCxHG7

But if you tried to use the same keys we have for the Rotki premium features to pull in data from exchanges then it indeed would not work.

**Comment by A2be** [comment]
Thanks @isidorosp 

That helps immensely.  

It seemed to me that, as Rotki is asking for  "API Key" and "API Secret", I should just give them the one I got from signing up to be a premium subscriber.

Did not know they are (or were) exchange specific.  Who knew?

**Comment by A2be** [comment]
So, I can just close this issue.

But from a Rotki "user feedback" point of view, I think you have yet another instance of overloaded terms.  You are using exactly the same two, two-word terms, to mean two entirely different things, on each of two tabs within the Rotki app.

You might want to write up a UX bug on that one.

**Comment by LefterisJP** [comment]
Thank you for the feedback @A2be! But not sure how "Exchange API Key" and "Premium API Key" can be further disambiguated.

We can not introduce new terminology that describes something as fundamentals an an API Key as that would actually be counter-intuitive and further confusing. This is why we prepend the descriptive adjective, "Rotki Premium", "Exchange", "Etherscan", "Cryptocompare" e.t.c to the word API Key.

All of the services you use out there have API keys so that they can connect with applications like Rotki in a secure manner.

Anyhow I am happy that you are not facing any trouble with this anymore. As I said above you can also find us in Telegram and Discord for more direct chat.

**Comment by A2be** [comment]
Oh, let me add one more comment.  , intended to be helpful to improving Rotki.

Since I spent decades in hardware and software product development, as an engineer, product architect, manager, project mgr, etc., I (eventually) got a bit experienced in the whole topic of "requirements engineering."  

Learned a lot about unstated requirements, and the importance of stating them, or trying to.  Generally, the importance of "making the implicit, explicit" in defining products and product behavior.

Since I've run into the topic of "overloaded term", descriptors meaning different things in nearly adjacent parts of a product twice (just today), I should tell you that I give credit to a bunch of my learning on that to Michael Jackson's book (not that Michael Jackson ;) )  **Software Requirements and Specifications: A Lexicon of Practice, Principles and Prejudices** 

All tightly written, in short/brief helpful single-topic prose.

He has an awesome section on "Descriptors".  @isidorosp   @LefterisJP 
I think it is just a page or two long.

**Comment by LefterisJP** [comment]
Thank you for the reading recommendation @A2be. Will have a look.
