### ISSUE TITLE
 Coinbase Pro: allow for multiple accounts with the same exchange

### ISSUE THREAD

**Issue by grooveuser** [rotki/rotki#1268]
## Abstract

Coinbase pro allows users to create multiple 'portfolios' under one account, each with their own api keys. 
In order to support accounts with multiple portfolios, Rotki would have to allow users to add these api keys as multiple separate Coinbase pro exchange integrations.

## Motivation

In order to get a full picture of the account, it is necessary to have multiple exchange integrations.
These portfolios cannot see into the other portfolios. Each can only see it's own balances.

I would love to use Rotki, but without support for multiple portfolios, I'm stuck with manual trade imports.
I'm peeking at the code now to see how difficult this might be to add.

**Comment by LefterisJP** [comment]
Hey @grooveuser thanks for using Rotki!

Unofrtunately, at this moment, the only way around this for you would be to make a new rotki account for each portfolio. Or to use a single portfolio in coinbase pro.

There actually is a very old issue asking for multiple accounts from the same exchange but it's not been worked on since not too many people asked for it: https://github.com/rotki/rotki/issues/47

If you would like to take a try at it feel free. I can help with any questions. But it's not an easy issue. It would touch many parts of the code.

**Comment by LefterisJP** [comment]
Closing this in favor of working on #47
