### ISSUE TITLE
User should be able to set a crypto asset as their main currency

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#1270]
## Abstract

Users should be able to set a crypto asset (e.g. BTC / ETH) as their "main currency". Instances in the application where "USD Value" / "EUR Value" etc would then be replaced by something like "BTC Value".

The ideal way to do this would be to actually calculate prices from the original asset to the crypto "main currency" using corresponding trading pairs, but the reality is that this is possible only for some assets (and then the actual price of the pair may fluctuate a lot depending on the source). As a result the most feasible way of implementing this would be to just convert the total "usd value" of all assets except the main one from "usd" to that crypto currency.

Historical prices will need to be obtained for the tax report and graphs to work properly.

**Comment by LefterisJP** [comment]
I am scheduling a simple version of this as discussed in discord in the next release.

Essentially we will add the current [BTC, ETH, XXX... ?] price in the exported current prices along with the fiat currencies. And the frontend will treat the profit currency as it's already doing but just use a different symbol and price

Complications may arise in the backend code while implementing since we expect a FIAT currency for the profit currency.

---

The more generic solution is here and pushed for later: https://github.com/rotki/rotki/issues/1790
