### ISSUE TITLE
No Sells in Tax Report when "crypto to crypto" is disabled

### ISSUE THREAD

**Issue by david-dankelmann** [rotki/rotki#1393]
Hi. I just found Rotkehlchen and think it is awesome, thanks for the good work.

## Problem Definition
When testing the Tax Report with the Setting "Take into account crypto to crypto trades" DISABLED, the resulting Tax Report includes only Buys and no Sells. When i re-enable the above setting, it works fine again.
I tried to study the logfile, but failed to understand why all Sells are omitted. The logfile shows, that they are generally processed. 

I tested switching main currency from USD to EUR with the same results. 

### System Description

Exchange: Binance
Assetpair: LINK/USDT
OS: Windows
[rotkehlchen.log](https://github.com/rotki/rotki/files/5143825/rotkehlchen.log)

**Comment by LefterisJP** [comment]
Hey David thanks for being a Rotki user and for your kind words!


Can you give some examples of trades that were there with the "crypto to crypto" trades setting on and were no longer there after it is off?

> Assetpair: LINK/USDT

Keep in mind that USDT is also a cryptocurrency. So it should not appear at all.

After some testing I see that (even though they are not taken into account in profit calculation since they are buys) the buy part of the split between crypto to crypto trades still appeared in the tax report. I will fix it.

For example if you exchanged 10 ETH for 1 BTC and 1 ETH was $100 at the time, it would still show you that you bought 1 BTC with $1000. I am gonna fix this.

**Comment by david-dankelmann** [comment]
Hi Lefteris, thanks for the quick and kind respond. 

I read the documentation on "crypto to crypto" setting that says:

"Specify whether crypto to crypto trades are taxable and should be taken into account. If yes then each crypto to crypto trade also creates a “virtual” trade that sells or buys the crypto asset for fiat and then sells or buys the fiat for the other crypto asset."

As Buy's were included in the tax report i understood the documentation in the way, that it would just omit the virtual trade calculation, but still show the trades although they would not be taxable. Now i see that the the issue was to include the Buy's in the first place and not only the virtual trades are ignored, but all crypto to crypto trades which includes my pair LINK/USDT.

Originally i wanted to produce an overview of my actual trades to check them against my binance output first (just for testing Rotki), which i can easily do with creating a tax report including crypto to crypto trades and then sorting by/ignoring all virtual trades.

Thanks again.

**Comment by LefterisJP** [comment]
Thank you for pointing out this hiccup with the report for us. It will be fixed in next release when the merged code gets published.
