### ISSUE TITLE
Unable to delete a "Manually Tracked Balance" entry when label is missing

### ISSUE THREAD

**Issue by KevinVitale** [rotki/rotki#1430]
## Problem Definition

After creating a new _Manually Tracked Balance_, I'm unable to delete it. I believe this is due to the fact that the entry was created without a label (see screenshot). 

I do not remember what sequence of steps allowed for me to create an entry without a label (possibly entering something in, but later deleting it?); however, in the app's current state, I'm unable delete the label-less entry.

<img width="207" alt="Screen_Shot_2020-09-02_at_11 19 35_AM" src="https://user-images.githubusercontent.com/276137/92028036-61e80f00-ed31-11ea-89cf-1bebb188e2b0.png">

**Comment by LefterisJP** [comment]
Thanks for the issue @KevinVitale!

Indeed as discussed in Discord the issue is reproducable. We will fix it in the next release.

In the meantime there are two options to get around it.

### From the UI

Just edit the label-less entry to track an asset that you don't care about and give it a very small amount. This way it won't affect your accounting

### From the console

Rotki's data is all local. If you can get access to your console, dependin on your operating system (Linux or OSX -- windows is harder).

Navigate to the DB:

1.1. **Linux**: `cd ~/.local/share/rotki/data/YOURUSERNAME`
1.2. **OSX**: `cd ~/Library/Application Support/rotki/data/YOURUSERNAME`

Open it: `sqlcipher rotkehlchen.db`

And then delete the label-less entry. Here is an example with a label-less entry and another one, and how you can delete only the label-less one.

```
sqlite> PRAGMA key="YOURPASSWORDHERE";
ok
sqlite> SELECT * from manually_tracked_balances ;
BTC||1E-9|A
ETH|a label|1|B
sqlite> DELETE from manually_tracked_balances WHERE label='';
sqlite> SELECT * from manually_tracked_balances ;
ETH|a label|1|B
```

**Comment by KevinVitale** [comment]
@LefterisJP thanks for the workarounds. It's worth mentioning that **"From the UI"** will not work: the text field refuses to accept focus/input in this state.

However, I may give the SQL one a shot. 👍

**Comment by LefterisJP** [comment]
> hanks for the workarounds. It's worth mentioning that "From the UI" will not work: the text field refuses to accept focus/input in this state.

Interesting. It worked when I tried. @kelsos Any ideas here?

**Comment by kelsos** [comment]
If the label is an empty string it will not work I confirmed it. For the vue component, an empty string is treated as not having anything selected.

**Comment by kelsos** [comment]
@KevinVitale Another question, other than not being able to delete the entry or edit the label, does the tag/value editing work for you properly?

**Comment by KevinVitale** [comment]
@kelsos appears so

<img width="400" alt="Screen Shot 2020-09-03 at 12 25 03 PM" src="https://user-images.githubusercontent.com/276137/92141525-8d760280-ede0-11ea-8711-cf8b3ceaf32c.png">
