### ISSUE TITLE
Sync Error dialog could have better layout

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1464]
I just logged in to Rotki after a while and saw this:

![image](https://user-images.githubusercontent.com/100738/93016319-41814580-f5b8-11ea-9761-16dc292db5bb.png)

It would be a lot easier to read, and to compare the pairs of file sizes and modification times, if line breaks were used to align each pair on two lines, one below the other:

    Sync Error

    Detected newer remote database!
    Local size: 5936
    Remote size: 23456
    Local last modified time: 30/07/2020 11:52:38
    Remote last modified time: 30/07/2020 16:10:53

    Would you like to replace the local DB with the remote one?

**Comment by kelsos** [comment]
@LefterisJP this is a bit tricky since the message comes directly from the backend, and there is no easy way to format the response in the frontend. Maybe we could also include the values (sizes and dates) there as payload to the response along with the message and then have the fronted render a message instead.

**Comment by LefterisJP** [comment]
@kelsos This is fixed, right? We followed your suggestion. If yes please close.

**Comment by kelsos** [comment]
Yes this should be fixed in the next release.
