### ISSUE TITLE
Consider using "name" instead of "label"

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1466]
Currently accounts can be given descriptive names by the user, however these are referred to as "labels".  IMHO this is slightly confusing to some (especially developers), since the word "label" is often used to imply that multiple labels can be attached to the object.  For example, this is the case for GitHub issues and PRs.  Rotki already uses the word "tags" to allow multiple tags to be attached to an account, which is great.  However to minimise confusion I would suggest considering using the word "name" instead of "label" for accounts.

**Comment by LefterisJP** [comment]
In my understanding label and name are synonymous, but that's probably because I am not a native English speaker. 

Changing it is totally fine at some point. Would change it both in the code and in the UI though so at to not leave code hanging around with old names.

Would probably only leave out any DB column changes as they would require a DB upgrade which would be probably an overkill for such a change.

@kelsos If we want to do this, for the frontend this should be easy, right?

**Comment by aspiers** [comment]
They are very similar but not quite synonymous.  Generally "name" implies something more canonical, i.e. a "primary" description, whereas "label" tends to be more of a secondary description, and like I said it is more expected for things to have multiple labels and a single name, or at least fewer names.

**Comment by kelsos** [comment]
This is easy to change yes. It should be really minor.
