### ISSUE TITLE
Add Binance.US support

### ISSUE THREAD

**Issue by VoR0220** [rotki/rotki#1515]
## Abstract
Add Binance.US support for their API keys

## Motivation

Due to the annoyances of US regulations surrounding financial laws, Binance had to split themselves up a bit and create a separate entity purely to handle their US customers. In theory the API should be the same but it's a different set of servers that need to be contacted. Otherwise API keys cannot be added for US binance users. This is quite an annoyance to an otherwise brilliant piece of software.

**Comment by LefterisJP** [comment]
Hmmm that's interesting. 

If the API is the same it should be trivial to add support. Will check.

**Comment by VoR0220** [comment]
APIs are here. 

https://github.com/binance-us/binance-official-api-docs

**Comment by LefterisJP** [comment]
Hmm since you said you would also like to see if you can contribute, this issue may be the best for you to start with @VoR0220!

Checking the binance-us API it seems identical (with a quick look) to the binance one. So .. in theory ... if you simply change the base URL it should work. Since I am not a US resident and not have a binance US account I can't test it myself but sounds like you have data to test with.

If you can build rotki by source and change this line:

https://github.com/rotki/rotki/blob/62cd1fb042a3a29b05d421a606278b1e4b73547d/rotkehlchen/constants/misc.py#L23

to `https://api.binance.us` according to their docs, then it should in theory work for binance us.

If that indeed works then I suppose we can add it as a different exchange location. BinanceUs, just using the same python Binance Object but with configurable base URL.

@kelsos From the frontend point of view would that make sense?

**Comment by kelsos** [comment]
If Binance.US will be a new entry, then it should be pretty easy to add it to the frontend.

**Comment by LefterisJP** [comment]
Hey @VoR0220 can you download a nightly release containing this feature, test it and tell us if it actually works?

The first nigthly with the fix should be here: https://github.com/rotki/rotki/actions/runs/431633578

Scroll to the bottom and get the appropriate release for your OS.
