### ISSUE TITLE
Addresses have disapeared

### ISSUE THREAD

**Issue by GregTheGreek** [rotki/rotki#1518]
## Problem Definition

It seems that my addresses have been removed from the dahsboard and accounts&balances page. But if i navigate to settings > DeFI I can see the addresses under `selected address(es)` section.

### System Description
```
rotki version 1.8.0
```

**Comment by LefterisJP** [comment]
Hmm okay that sounds super weird.

What did you do to get this result? Have you ever used a develop version before using v1.8.0?

What's your operating system? Do you know how to access the DB manually so that you can explore the data in there? This is the first thing I would check. if the data is still in the DB and somehow is not shown in the UI.

It would also make sense to see the logs. You can get the logs for your OS by going to the top menu Help -> Logs directory.

Since some of these stuff may contain sensitive data you can also DM me in TG or discord: https://discord.gg/aGCxHG7

**Comment by GregTheGreek** [comment]
System: Ubuntu 20

Went from release v1.7.0 -> v1.8.0

No idea how to scrape the db, mind giving me some pointers?

**Comment by GregTheGreek** [comment]
Seems I can't get access to the logs, do you know where its manually stored?

**Comment by LefterisJP** [comment]
Logs for ubuntu should be: ` ~/.config/rotki/logs/rotkehlchen.log`

**Comment by GregTheGreek** [comment]
it appeared i was rate limited

**Comment by LefterisJP** [comment]
Interesting. But if you were rate limited did you not see an error somewhere in the UI?

**Comment by GregTheGreek** [comment]
No errors in the UI, but it wouldn't show me any of my accounts/balances. Loading bars even stopped

**Comment by LefterisJP** [comment]
There must have been some kind of error. I tried to reproduce in ones of my accounts which tracks ~20 eth accounts with lots of tokens and some BTC accounts.

Without an etherscan API key it takes quite a long time but it completes fine.
