### ISSUE TITLE
Adding Custom Ethereum Tokens/Assets

### ISSUE THREAD

**Issue by Souptacular** [rotki/rotki#1519]
## Abstract

Add support for custom tokens. New tokens are being released all the time and as a user I want the ability to record my transactions manually into Rotki immediately after I make them.

## Motivation

There is a trend of versioning tokens on Ethereum when they are transitioned to new versions of smart contracts. Two examples are DAI and YAM.

The Maker DAI cryptocurrency transitioned from DAI tokens to (newer) DAI tokens and renamed the original DAI tokens SAI. YAM has had 3 versions of their token v1, v2, v3 (now just called YAMs)

## Specification

I want to be able to put a name/ticker symbol into the system. I would need to manually add a price for each token transfer/trade/etc., but that can be accomplished in [this issues](https://github.com/rotki/rotki/issues/1520). As an advanced feature, I would like integration with Etherscan/CoinGecko so I can just input the token address and it autofill properties about the token such as name and symbol.

**Comment by mgarciate** [comment]
I am also interested in this feature. I think about this feature in the same way that Metamask allows adding custom tokens by copying the contract address.

**Comment by aspiers** [comment]
It's worth noting that [EIP-747](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md) was an attempt to improve the UX of adding custom tokens to web3 providers like Metamask, since copying and pasting smart contract addresses is clearly terrible UX.  The idea was to transition away from a centralised list of tokens such as [`eth-contract-metadata`](https://www.npmjs.com/package/eth-contract-metadata) towards a system where dApps could automatically provide the information for a specific token. *Maybe* some similar approach could work with Rotki, although of course there'd still be the question of how to bridge the gap between the website and Rotki, since Rotki is not a browser extension and therefore can't act as a web3 provider.

Having said that, it seems that EIP-747 never really succeeded in gaining adoption, and that [Ethereum token lists](https://tokenlists.org/) won that particular battle.  Given that [anyone can author their own list](https://github.com/Uniswap/token-lists#authoring-token-lists), maybe that's a better way forward.  I'm not really sure - just offering food for thought.

**Comment by LefterisJP** [comment]
What we will do for this issue is allow addition of custom token entries via the UI, with optional coingecko/cryptocompare link. There is no other unique way apart from entering an address. Everything else can be faked and duplicated.

If we can't find a price, no price will be shown. But then eventually #1520 would come to the rescue.

The biggest change this issue will do in the code is try to make the current code work also with those custom assets and not always depend on having an entry in all_assets.json.
