### ISSUE TITLE
Add a option to disable etherscan as a fallback for local node users

### ISSUE THREAD

**Issue by jimjimvalkema** [rotki/rotki#1526]
## Abstract
Currently rotki queries etherscan as a fallback when it isn't able to connect to the users local node. 
A option to disable this fallback would make maintaining privacy easier.

## Motivation
The current fallback behavior can weaken privacy because:

- etherscan can then link addresses with the users ip address

- etherscan can link public user addresses with private user addresses

## Specification
A button in the settings next to/after the "eth RPC endpoint" setting, that says: "disable etherscan fallback"
Which will force rotki to only use the users local node.
Perhaps a error when it fails to connect explaining to user that the this setting is turned on.

**Comment by LefterisJP** [comment]
We also query other public nodes, not just etherscan. For now these are the public nodes we query:

```
        elif self == NodeName.ETHERSCAN:
            return 'etherscan'
        elif self == NodeName.MYCRYPTO:
            return 'mycrypto'
        elif self == NodeName.BLOCKSCOUT:
            return 'blockscout'
        elif self == NodeName.AVADO_POOL:
            return 'avado pool'
```

Do you want an option to disable all of them? Or an option to disable them selectively? Say you only want to avoid etherscan?

But be warned that not using etherscan will probably not work for log queries. Log querying is broken in ethereum. Etherscan (and Infura) have indexed log queries which is what makes it possible to work for older contracts.

We also query the graph. Which is indexed by various indexers (for now only a centralized service but very soon with their mainnet launch will be asking many different machines). We can also add an option to disable the graph queries too but then half of the functionality will probably not work.

**Comment by xwvvvvwx** [comment]
> Log querying is broken in ethereum

Curious about this, what do you mean by broken? I am also very interested in avoiding any queries to 3rd party services. I have an archive node running, and ideally this would be used for all queries.

**Comment by LefterisJP** [comment]
Sure, I can explain. It's impossible to avoid queries to any 3rd party services, even if you have an archive node. 

### Log Querying

Log querying (archive or not) is broken in ethereum due to the way the ethereum clients are coded. There is too many random reads to find log entries and the database of a normal geth node responds way too slow to a big log query. Even in my own node it would time out at 1-2 mins after a big log query. And for data that we need in Rotki we would make 100s of log queries per protocol, per account.

We are monitoring the progress Turbo-geth is making where they try to improve on this problem. Perhaps with them it will be easier to make it work faster. But still, can't rely on the user having only 1 type of node for rotki to work reliably.

If you use infura, or if we leave it at etherscan, then they actually seem to have an indexing middleware on top (an extra database) which makes all log queries really fast.

### Subgraphs

Subgraphs are the fastest way to query data from the chain. We use it for premium users, and per protocol this is the only way to get historical data in something close to real time.

In theory the user could have their own archive node, and run their own graph nodes and index subgraphs. We could add support for that at some point, but it's a really corner edge case.

### Miscellaneous stuff not retrievable by an ethereum node

The most obvious problem with ethereum is that there is no way to get the list of an ethereum account's transactions. We use etherscan for that. Would love to have other ways, but there simply is none (yet).

Another thing missing is ways to match timestamps to blocks. So if have a time range, match it to a block range. Etherscan offers an endpoint for this.

And probably more that I can't think of.

----

Conclusion is that even if you run your own node, the way ethereum nodes are made we can't get all of our information from it. 

We do try to query your own node as priority for everything we can though. And now we are also setting up a local archive node ourselves and perhaps we can even find more awesome ways to use it and enhance the user experience.

**Comment by xwvvvvwx** [comment]
Thanks for such a detailed answer :slightly_smiling_face: 

> In theory the user could have their own archive node, and run their own graph nodes and index subgraphs. We could add support for that at some point, but it's a really corner edge case.

Would this be sufficient to avoid all queries to 3rd party services, or would further indexing layers be required?

**Comment by jimjimvalkema** [comment]
Sorry i missed the updates on this one. But yes my intention was initially to have a option to disable all 3rd party queries services. But if missing log queries and the graph would disable half of rotki's function then it would make more sense to have separate options for those. 

But i saw issues #817 which might achieve close to the same privacy features.

**Comment by LefterisJP** [comment]
Closing this as this is now possible for the queries that can be replaced by normal nodes.

You can remove etherscan from your node queries, or put it at the bottom of the list or edit it's priority to 0 or whatever you want. https://rotki.readthedocs.io/en/latest/usage_guide.html#rpc-nodes

For stuff mentioned above that are only available via etherscan we can't do anything unless a different methodology arises. When it does a setting canbe added.
