### ISSUE TITLE
Syncing the premium account, doesn't sync addresses, only exchange accounts.

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1542]
## Problem Definition

I expected when I fed in a bunch of addresses on one of my Rotki installations, that it would auto import them into another computer that was also connected to my Rotki premium account, but it didn't.

this would be frustrating if it can't sync the addresses across installations, especially as there's no automated way to enter in a lot of addresses from a seed.

**Comment by JezSan** [comment]
as a hack, if we can't sync addresses across Rotki installations, then at least provide an export function (or is there one already and I missed it?), so that all the time ive taken adding addresses to one Rotki installation can be imported into another one.

**Comment by LefterisJP** [comment]
The entire database should be pulled. Are you sure that it was pulled and synced succesfully? To be sure you should check the rotki logs.

**Comment by JezSan** [comment]
so if the blockchain addresses are definitely in the database on one computer, but on my 2nd computer, they're not being pulled, what shall I do?

I have my laptop open, and it has more than 100 blockchain addresses in it, that are showing up in the balance.   and on my desktop, which has indeed synced the exchange accounts, but its showing no blockchain addresses at all, thus hasn't synced those.   is there any way to force it to sync?

**Comment by JezSan** [comment]
It doesn't sync manual balances either.  the only thing it seems to sync are Exchange API keys.

**Comment by LefterisJP** [comment]
Okay let's see how to debug this JezSan! I suspect you have manually put the exchange api keys and forgot about it and syncing in general does not work in your case yet. But we will figure it out.

First things first. By default even if you have premium api keys syncing is disabled (as it may overwrite stuff you don't want to lose). Please always keep backups of you rotki database.

Have you enabled premium syncing for the machine that has the data (1st computer)?
![2020-10-04_23-46](https://user-images.githubusercontent.com/1658405/95027844-01375380-069c-11eb-8288-d68b03063c7f.png)

Then in the second machine you need to create a new account and at the time of creation of the account enable premium.
![2020-10-05-000044_584x559_scrot](https://user-images.githubusercontent.com/1658405/95028129-58d6be80-069e-11eb-93be-1d1ab1703629.png)

That new account **must have the same password** as your machine in the 1st computer. The reason is that this password is what decrypts the database. If it is not the same syncing will not work as the 2nd machine will fail to open the database.

You can also do it with an already existing account on the 2nd computer but it's more complicated. You would need to add api keys to that 2nd account, enable syncing, and if the password is not the same as the one on the first machine change it.
![2020-10-05_00-11](https://user-images.githubusercontent.com/1658405/95028266-59bc2000-069f-11eb-9a06-bc5c7dcc806b.png)

At that point restarting rotki on the 2nd machine should pull and sync the database. There may still be a small hiccup there but we are fixing it this week in v1.8.1.

So @JezSan if all the above does not work please provide the rotkehlchen.log for both machines so that I can check what happens and what the problem may be.

**Comment by LefterisJP** [comment]
@kelsos Can you add a note to improve our user guide for the above? ^ I am not sure if it's properly documented how to sync the DB properly for premium users between machines.

**Comment by JezSan** [comment]
thanks for all the hints.  can we switch to direct email for the rest of the support, cos if I'm going to disclose more info I don't want to do that publicly.

for the record, both instances of my Rotki were set to premium when the account was created, and I already had premium turned on and syncing turned on on both of them (and I checked and its still turned on, now), and both had the same Rotki premium api keys entered.  but the only thing that got synced was the exchange api keys, and nothing else.   I did have to create a new (identical) account on the 2nd machine, ie, it wouldn't let me use the login from the 1st account as the login for the 2nd, so presumably the account that you create is only locally, and only the api keys are the connection for the Rotki premium server that syncs data between both Rotki instances, and not the account login itself.

ive tried restarting Rotki on both machines, and that didn't do anything different.

**Comment by JezSan** [comment]
I found the log file.  what information am I sharing if I provide you the log file?  if it contains any private information, for instance my exchange api keys, and my blockchain addresses, then we'll have to figure out some other way to debug this, as it would be insecure to share it.

**Comment by JezSan** [comment]
Just to confirm, I did create a new account on both machines, with the same password.  and both are set to premium and both are set to sync.  and it did sync the exchange api keys.   but nothing else.

**Comment by LefterisJP** [comment]
> thanks for all the hints. can we switch to direct email for the rest of the support, cos if I'm going to disclose more info I don't want to do that publicly.

Naturally you can email us: support@rotki.com

> so presumably the account that you create is only locally, and only the api keys are the connection for the Rotki premium server that syncs data between both Rotki instances, and not the account login itself.

That is correct. The username does not matter whatsoever. But the password does. **The two accounts need to have the same password.** And I just noticed that in the code we don't throw a big error if there is a password mismatch for an existing account, but silently ignore it. (will fix that now)

> I found the log file. what information am I sharing if I provide you the log file? if it contains any private information, for instance my exchange api keys, and my blockchain addresses, then we'll have to figure out some other way to debug this, as it would be insecure to share it.

It does contain private information. No exchange api keys are there, but addresses would be. If you don't trust us with them I understand. The other way is for me to tell you what info I need from the log and you give them to me. That will naturally take more back and forth.

> Just to confirm, I did create a new account on both machines, with the same password. and both are set to premium and both are set to sync. and it did sync the exchange api keys. but nothing else.

The only other problem I can imagine is that since you open the 2nd account, the locally saved DB has a newer timestamp than the remote and as such does not pull it. I am pushing a fix which will get included in 1.8.1 (hopefully tomorrow) and will actually ask the user if they want to pull and replace the DB or not.

---

To be 100% sure syncing works please in the 2nd machine follow the guide I posted [above](https://github.com/rotki/rotki/issues/1542#issuecomment-703323745) where you create a new account in the 2nd machine with the same password as the first and enable premium keys at the time of acount creation. This should pull and sync the DB.

**Comment by JezSan** [comment]
that could be the issue.

the 1st machine's account had the exchange api's entered into it, and the 2nd machine's account, had all the addresses entered into it... so the 1st machine isn't syncing the 2nd machine's data... so maybe the sync is only one-way, from the 1st to the 2nd and not both ways.

you may have fixed this in 1.8.1, so I shall try that and if it doesn't work then we'll need to figure out what else could be wrong.

**Comment by LefterisJP** [comment]
Yes the syncing does not combine data. It's destructive and only 1 way. It either syncs all or nothing. Please keep backups of the databases to make sure you lose no data.

This is not fixed in 1.8.1 as it's not possible with the current system. In order to be selective about what we sync we would need a much more sophisticated syncing system which we don't have at the moment.

To achieve what you want I would say just manually add the exchange api keys in machine 2, as it's probably the least amount of manual work. This way the master account becomes machine 2. Then create a new account in machine 1 with the same premium api keys and password and sync the DB there as per the instructions given above.

**Comment by JezSan** [comment]
can we have a button that says 'Overwrite DB SYNC from this copy', and then it overwrites the sync master with whatever u have in the local database at that time.  that way, its much more flexible and doesn't need to do a differential sync.

**Comment by LefterisJP** [comment]
Yes we should do that!

@aspiers has also asked for exactly that in this issue: https://github.com/rotki/rotki/issues/1194

Thank you for reminding me about it. Will see if we can push it a bit faster.

**Comment by LefterisJP** [comment]
So can I close this issue @JezSan and consider as the one thing to improve out of it the requested button for which there is already #1194?

**Comment by JezSan** [comment]
sounds good, thanks

**Comment by JezSan** [comment]
still keen on seeing that button to force a local db to update the sync version.  what's the eta for this?

**Comment by LefterisJP** [comment]
This is what @kelsos is working on here: https://github.com/rotki/rotki/pull/1593

I will let him confirm the ETA but should also be next version (v1.8.2)

**Comment by kelsos** [comment]
I should have completed with the requested feedback changes, I just changed the status to ready for review. let me know if everything is ok on your side @LefterisJP

**Comment by JezSan** [comment]
did this make it into 1.8.2?  and if so, how do we operate it?

**Comment by kelsos** [comment]
hey @JezSan at the moment you can find the manual sync buttons in the rotki Api Keys page in the lower right corner
![image](https://user-images.githubusercontent.com/2269732/97408292-2c5c3e00-18fc-11eb-829c-d760716c77d8.png)
We plan to move the for the next version though to the disk icon on the toolbar
