### ISSUE TITLE
Logs are not encrypted and show complete address and balance

### ISSUE THREAD

**Issue by spaceblankey** [rotki/rotki#1561]
## Problem Definition

The logs stored in [Windows] C:\Users\USER\AppData\Roaming\rotki\logs can be accessed by anyone with access to the machine. The logs show a complete address and balance, along with bank balances or other manually inputted balances. 

Is there a way to obfuscate the balances and addresses in the logs? The developers don't always need to know this for debugging, maybe add a high level permission to show these if it is required, but it should not show by default as it defeats the purpose of using Rotki. 

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
uname -a
command -v geth && geth version
command -v parity && parity --version
command -v rotki && rotki version
[ -d .git ] && git rev-parse HEAD
```

**Comment by LefterisJP** [comment]
As per the twitter conversation the anonymizer anonymizes some values: https://github.com/rotki/rotki/blob/f8f7f4545c79bad3dbb5e9ace3fe1b380240eaab/rotkehlchen/logging.py#L14-L52

But it needs continious work as the app develops and will as such miss lots of stuff.

If you really feel this is important then the easiest way is for us to allow for customization of the logs on the user side even leading up to complete disabling. It should be easy to implement. But each time the user who disabled them has a problem they would need to re-enable it so we can have something to debug.

Encryption is another thing we could try but this is a lot more work and would make little sense since the intended recipients of logs are the developers so they can debug your problems and fix the bugs.

**Comment by LefterisJP** [comment]
So for this as discussed with @kelsos we will just by default log only critical errors and the user can customize the log verbosity via somewhere in the login-screen.
