### ISSUE TITLE
"Blockchain Balances" not sorted by value

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#1564]
## Problem Definition

"Exchange Balances" & "Manual Balances" are sorted descending by FIAT value, so should "Blockchain Balances". Currently this seems to have Ethereum as sticky #1, no matter the value.

### System Description

rotki v1.8.1
ubuntu 20.04.01

**Comment by kilrau** [comment]
Still persists in 1.8.2, please reopen

**Comment by LefterisJP** [comment]
In what sense does it persist Kilian? Perhaps we misunderstood what you meant by the issue then? Can you maybe give a screenshot with the data blurred or something?

**Comment by kilrau** [comment]
Descending sort by fiat value (large amount row 1) works well for `Exchange Balances` and `Fiat Balances`, just not for `Blockchain Balances`.

ETH: small amount expressed in EUR, row 1
BTC: large amount expressed in EUR, row 2

![image](https://user-images.githubusercontent.com/19181985/97328043-e361a680-1875-11eb-9011-fe82441bb35e.png)

**Comment by LefterisJP** [comment]
AH! I see. This is a different blockchain balances. We had a problem in the actual blockchain & accounts section that was fixed with #1575 

But you meant the one in the dashboard. So we had completely misunderstood your problem. Since this is (at least for us) a different issue can you just open a new one, specify Dashboard and put what you wrote above there. We will handle it :+1:

**Comment by kilrau** [comment]
Done: https://github.com/rotki/rotki/issues/1638
