### ISSUE TITLE
Support Adex Network staking

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1681]
## Abstract

Support Adex Network staking. https://staking.adex.network/#/

That means:

- See how much is staked and where (which pool)
- See staking history per user who used Adex

## Motivation

It's one of the few protocols that have steady high yield and some people are using it. Support it will add value to Rotki. Also our friends from Adex will be happy.

## Specification

Should not really be hard. There is also a subgraph for historical events: https://thegraph.com/explorer/subgraph/adexnetwork/adex-protocol

**Comment by Ivshti** [comment]
While we do maintain the subgraph and it is up to date, you can very easily get this info through ethereum logs too in case you don't want to depend on thegraph which is known to go down leaving you without a viable alternative

here's an example of how to do that in JS: https://github.com/AdExNetwork/adex-staking/blob/af735d4e141cd160db91a97086582e34c8877e20/src/actions/actions.js#L353 

And here's an explanation:
1. Request all logs for the staking contract for this user https://github.com/AdExNetwork/adex-staking/blob/af735d4e141cd160db91a97086582e34c8877e20/src/actions/actions.js#L334 - a slight complication is that you can't just request by the user's wallet, instead you have to calculate their identity smart contract (that's a contract that gets deployed the first time they stake). Calculating this is a matter of `keccak256` on a string: https://github.com/AdExNetwork/adex-staking/blob/7952259e229f443fa6f4bf2c4b39d859b35366ef/src/helpers/identity.js#L6-L20
2. Slashing can be ignored as it won't happen with this staking contract
3. Now aggregate the logs: take a new BigNumber with the value 0, and just add the ADX value for each `LogBond` and remove it for `LogUnbondRequested`; because `LogUnbond` only contains a bond hash, you have to keep track of individual bonds and their amounts at `LogBond`
4. The resulting value is the total ADX locked up in staking

**Comment by LefterisJP** [comment]
This is fixed by @vnavascues and #1880
