### ISSUE TITLE
Support for Australian Exchange IndependentReserve

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#1692]
## Abstract
Support for Australian Cryptocurrency Exchange https://www.independentreserve.com/

This would be my first pick.
## Motivation
In order to make Rotki more useful for Australian users, support for the main Australian cryptocurrency exchanges is needed. Especially for tax calculations.

## Specification
https://www.independentreserve.com/products/api

**Comment by drgonzo31** [comment]
Hello again,

I'm happy to donate on top of premium to rotki if that will help with pushing this up the queue. 

Regards
Dylan

**Comment by LefterisJP** [comment]
Hey @drgonzo31 thanks for bumping this. As we are a small team we are prioritizing what most of our users are asking and there is some exchanges that are higher in the queue due to their popularity among most of our users.

Donations, especially in gitcoin during a matching round like there is now, are really appreciated and do help us cover some of our expenses but can not guarantee an inclusion of a feature in a particular time.

I understand that this is an important feature to you as someone who lives in Australia(?) and is probably the best fiat on/off ramp for AUD.

I will tentatively schedule it in a release so it does not fall through the cracks. But no guarantees on exactly when it would be included.

As a sidenote, a good way to guarantee a feature inclusion is to find also someone who can code and contribute the code for the inclusion to rotki. Our code, especially exchanges, is modular and should be easy for an external to create a module for a specific exchange.
