### ISSUE TITLE
Support for UK tax base; make tax base transparent

### ISSUE THREAD

**Issue by dankrad** [rotki/rotki#1783]
As a further complication to #44, the UK actually requires the computation of the tax base as the *average* of all previously bought assets.

Also, when I created the report, it was very intransparent to me how it was computed. Only when going through the issues here I noticed that it is probably based on the FIFO method. It would be great to (1) clearly show this in the user interface and (2) add the tax base as a column in the exported files for easy checking and debugging.

**Comment by LefterisJP** [comment]
Thanks for reminding me of the tax report customization. Generally that part of the project needs more love. We will get to it as soon as we find some dev cycles.

Some questions to better understand what you need. Tell me if I understand correctly:

1. Transparency in the tax report UI: Somehow show the accounting settings (that's where you can customize stuff) in the actual tax report page so that it's obvious with what settings it is made?
2. Want a new calculation method for taxes, not fifo, not lifo, but average of all previous buys of an asset?
3. You want the tax base in each row of the exported files. And by tax base you mean the method (fifo/lifo/average) or the actual amount that is matched to? For average it would be easy to add. For FiFo/LiFo since a sell can be partially matched to multiple buys the number may be something like the average of the part of the buys that was used. Would that be okay? Ideally we would  find a way to visualize which sells were used in a buy. We have an old issue for that: https://github.com/rotki/rotki/issues/1364

**Comment by dankrad** [comment]
1. Yes, that would be pretty great to show the method, because currently it's not clear how it's calculated at all until you go through the issues here.
2. Yes, to be more precise, the average value of all your units of a given asset. So go through an example:
 * buy 1 ETH at 100 $. Your tax base is now 100 $
 * buy 1 ETH at 200 $. Your tax base is now 150 $ for your 2 ETH
 * Sell 0.5 ETH at 400 $. Your profit would be 200 $ - 75 $ = 125 $. The remaining ETH still have the same tax base of 150 $
 * Buy another 0.5 ETH at 500 $. The tax base would now be (1.5*150$ + 0.5*500$) / (1.5 + 0.5) = 237.50$
3. Yes, I think for transparency it would be really nice to show the tax base in the export files. Currently it only shows the profit, but I think any accountant would probably want that split up into the revenue from the trade and the tax base. It would also make it much easier for a user to debug this.

A separate, related question: How does rotki currently get the tax base for coins for which it does not have the corresponding exchange trace, e.g. because that exchange is missing integration or they were from an OTC trade etc.? It would be nice to be able to enter the tax base manually for these.

**Comment by mcplums** [comment]
I do not think it is advisable to try and implement UK tax laws without a formal process which involves consulting with a professional. For example, it is not just the average cost that is relevant, it is also the bed and breakfasting rules that would need to be taken into account: https://www.gov.uk/hmrc-internal-manuals/capital-gains-manual/cg13370#

**Comment by LefterisJP** [comment]
@mcplums 

Rotki does not implement tax laws of any specific country. As per our [disclaimer](https://rotki.com/terms_of_service/) we are not tax accountants under any jurisdiction. Everything provided is informational only.

That said we will provide as many options as our users need in order to do their calculations under their jurisdiction. Rotki is a portfolio tracker and accounting tool first and foremost. Tax reporting is something we would love to help with but not something we (at least yet) natively support.

I would consider native support to be able to select your jurisdiction and then we just calculate everything depending on your current tax law and even with the ability to directly transmit results to your tax office.

And that's not something we can do at the moment nor is it in our roadmap.

----

@dankrad 

Here are three separate issues to track what you mentioned:

#1794 - Add cost basis of each trade in tax report export
#1793 - Add the average cost basis as an accounting method
#1792 - Show the selected accounting settings in the tax report section


> A separate, related question: How does rotki currently get the tax base for coins for which it does not have the corresponding exchange trace, e.g. because that exchange is missing integration or they were from an OTC trade etc.? It would be nice to be able to enter the tax base manually for these.

All trade prices are taken from cryptocompare.com. At least in Germany the accountant here wanted the same source for all data.

We have an issue to add coingecko as historical price source since cryptocompare has unfortunately been lagging behind in a lot of things and having a lot of problems lately.

Manual input of price for a historical trade is not possible at the moment.

@dankrad if the issues I made would satisfy your needs then please close this issue and let's focus on the newly created action items represented by the three issues.

**Comment by dankrad** [comment]
> Manual input of price for a historical trade is not possible at the moment.
So what base does rotki assume for coins that come from no exchange trade? Does it use the price when it was first transferred into the wallet (that may be roughly acceptable) or how does it work?

> @dankrad if the issues I made would satisfy your needs then please close this issue and let's focus on the newly created action items represented by the three issues.
Yes that should be fine

**Comment by LefterisJP** [comment]
> So what base does rotki assume for coins that come from no exchange trade? Does it use the price when it was first transferred into the wallet (that may be roughly acceptable) or how does it work?

Very good question. 

If no buying event for the asset can be found then it assumes something is wrong, logs a warning in the logs and at the moment the default behavior (non configurable) is to count the entire trade as pure profit (with a warning in the logs).

It's far from ideal and I am not sure how to make this (with the current way the tax report works) more easy for the user to set a custom buy price. Any feedback here is appreciated. We could push this warning to the warnings on the top right ... but people have complained they are already annoying. @kelsos any idea here are appreciated.

The current way to address the problem of non-exchange asset providence (and how the people who have used rotki to do tax reports did it so far) is to go the "Trades" section and add a manual trade for the asset for which they want to inform rotki they bought.

So you go there, make a manual trade and specify how much was bought, at what time and at what price. Then this manual trade is also taken into account by rotki during the accounting phase of the tax report.

**Comment by kelsos** [comment]
As we discussed a few times, I find the manual trade cumbersome and not really user friendly. 

Ideally, for me instead of a warning, you get some kind of a wizard every time new assets are detected. You can choose to either ignore and rotki does what it does by default or you are guided by the application to insert values. The wizard should only bother you ever again if new assets without buy events are detected.

**Comment by LefterisJP** [comment]
Manual actions (trades/losses/mining/icos etc.) can be and should be added somewhere by the user. Not everything can be autodetected.

The problem with the current accounting architecture is that the entire thing is a monolithic task that only runs if the user requests a tax report and with so many protocol additions has become extremely heavy.

We should split all the backend tasks into continuous tasks running whenever the user runs rotki. They would detect everything they could about the user's assets and push all "human help needed" to the queue for processing by the user. Then the frontend would query this queue of tasks and present them to the user in anice user friendly, wizard way. How does that sound @kelsos ?

**Comment by kelsos** [comment]
Sure sound good to me.

**Comment by dankrad** [comment]
Yes, that would be pretty good -- basically identifying where trades are missing and querying the user for it.

**Comment by LefterisJP** [comment]
All right great. So here is the last issue: https://github.com/rotki/rotki/issues/1797

With that I can think we can close this one as we have quite a few action items. Thanks a lot @dankrad.

Your feedback is pretty valuable. If you are not there yet pass by the discord and say hi some time:  https://discord.gg/aGCxHG7
