### ISSUE TITLE
Rename Tax Report to Profit and Loss Report

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1866]
## Abstract

We are not really creating a tax report since it's not something you can immediately file in any specific jurisdiction.

What we are creating is a customizable profit and loss report. Naming here matters to manage user expectations.

## Task

- [x] (**Priority**) Change the language in the frontend
- [ ] for consistency where possible change the language in the backend

**Comment by chevdor** [comment]
I would also suggest (not adding a new issue as it is very much inline with this one) to change the order of the fields in the overview and have `Taxable Trade Profit Loss` and `Total Taxable Profit Loss` as the last fields in the table.

I must admit that my experience using Rotki is till limited so my reflexes are probably not the right ones but as a naive user, I almost took the last field of the table `Total Profit Loss` as "total taxable profit loss". Since we are in this page, I considered the last number to be the correct one. My heart missed a bit and I decided to double check those values that did not match my expectations let's say :)))

Since this page is about Tax report mainly, I would suggest to highlight the "Taxable" totals to ensure and help the user NOT take the much bigger other numbers (and end up pay way more taxes...).

**Comment by LefterisJP** [comment]
> My suggestion would be to replace the current by:

Very good feedback. Thank you!

> General Trade Profit Loss

So for this, you suggest no change?

**Comment by chevdor** [comment]
> So for this, you suggest no change?

I think users are mostly interested in the "taxable" values so I would leave it as it is indeed.

**Comment by LefterisJP** [comment]
The thing with the profit/loss report is also there is people who don't care about taxes, but would love to have a good overview of how much they made or lost in a given period of time. So would like to cater to both sets of people.

**Comment by chevdor** [comment]
If there are 2 profiles, the best options may be to have 2 tabs, one for each profile.

**Comment by LefterisJP** [comment]
Or perhaps an option in the accounting options.

**Comment by kelsos** [comment]
@LefterisJP should I open a new issue about the backend refactoring?

**Comment by LefterisJP** [comment]
> @LefterisJP should I open a new issue about the backend refactoring?

nah it's fine we may do it at some point or not. If we think of it as a must do will open an issue then.
