### ISSUE TITLE
SOL token is Solana, not Sola

### ISSUE THREAD

**Issue by JezSan** [rotki/rotki#1868]
## Problem Definition

The SOL token on the exchanges is reported with the correct value but the wrong name.  Its Solana, not Sola.

**Comment by LefterisJP** [comment]
Hey @JezSan that is actually an exchange mapping error then.

Which exchange are you referring to?

As you probably know cryptocurrency tokens don't have an existing registry of symbols that governs which symbol each token can take. So multiple tokens with the same symbol can be found.

To solve that we have our own registry of tokens with a unique identifier for each token (in all_assets.json). The unique identifier is essentially the same as the symbol, unless another identifier with the same symbol exists. In which case we start appending a counter. 

Rotki supports the following (from all_assets.json):

```json
    "SOL": {
        "coingecko": "",
        "ethereum_address": "0x1F54638b7737193FFd86c19Ec51907A7c41755D8",
        "ethereum_token_decimals": 6,
        "name": "Sola Token",
        "started": 1514467063,
        "symbol": "SOL",
        "type": "ethereum token"
    },
    "SOL-2": {
        "coingecko": "solana",
        "cryptocompare": "SOLAN",
        "name": "Solana",
        "started": 1586494758,
        "symbol": "SOL",
        "type": "own chain"
    },
```

You are interested in Solana I guess, but for some exchange we must be having the wrong mapping. Can you tell me for which exchange you saw it?

It should not just be the name that's wrong, but also the price.

**Comment by JezSan** [comment]
SOL on binance is solana.    It shows the correct price on Rotki but not the right name

I know there’s a legacy sola token but it’s not listed anywhere and has no price. 

So this issue does look like a misnamed token and not a confusion between two similarly named tokens

**Comment by LefterisJP** [comment]
That's really weird if you actually do see the correct current price.

If Binance returns a token as SOL and we don't have a special mapping arranged for it (can't see anything), then it should default to the legacy one. And the price feed is coming from cryptocompare: https://min-api.cryptocompare.com/data/pricehistorical?fsym=SOL&tsyms=USD&ts=1607205381

Price of that is  0.001904 while SOL is 1.96.

>I know there’s a legacy sola token but it’s not listed anywhere and has no price.

It's in cryptocompare: https://www.cryptocompare.com/coins/sol/overview. It's only historical data. We can't delist/remove tokens since we do historical accounting. Even if something has no price now it had at some point in the past when you traded it.


Let me look into this a bit further. The fix is super easy. What I don't get is why you get the right price.

**Comment by LefterisJP** [comment]
Okay the price reason is that cryptocompare seems to have SOL, listed as SOLA, but actually return Solana's price.

Oh boy ...

**Comment by LefterisJP** [comment]
Fixed by https://github.com/rotki/rotki/pull/1873

**Comment by JezSan** [comment]
Awesome

What was the fix?

**Comment by LefterisJP** [comment]
Mapping to the proper token from Binance.
