### ISSUE TITLE
Switch more towards a plugin architecture for most components of the app

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1874]
## Abstract

It has been suggested to us by multiple people to try and become even more modular and introduce some form of plugin architecture for different parts of the app. This would make it easier to have external contributors and could turn Rotki into the standard opensource protocol for portfolio tracking and accounting since everyone could just plugin their own addition to it easily.

This is an epic issue which will be comprised of multiple smaller ones.

## Specification

Components that each could have their own plugins are:

- Exchange integrations
- DeFi protocol integrations
- Blockchain integrations
- Accounting modules

## Task

This should probably include all of the subtasks we would need to implement this.

**Comment by isidorosp** [comment]
As discussed before I think this is a great idea and would be a huge multiplier in terms of potential network effect. As I've mentioned previously, I think if there ever is a "rotki token" this is probably one way that it would make sense to tie it in. The idea doesn't require it, but it might work well with it.

Basically you would be able to create something like an "app store" (aka plugin store) for rotki, and allow 3rd parties to write plugins that users could even pay for (rotki could get a cut, just like any store). This would be great because a) it would make it easier to others to create plugins for new chains/protocols/the above listed as opposed to putting the entire burden on the rotki team, b) it would organically grow the community by introducing members who will need to be active in the community and it will probably lead to users/teams who create plugins (e.g. some new defi protocol) bringing in even more users to the platform.

A token isn't necessary for such an implementation, but it could be used in the following manner:
* Reward users who are active in the rotki community and store with tokens based on their activities, e.g.: project contributions / plugin creation / plugin reviews / plugin audits / etc. (a sourcecred like system)
* Tokens could be used for rotki governance (e.g. milestone feature voting), or to create bounties for plugins (either for feature additions for existing plugins or to be put towards new plugins)
* Tokens could also be used in lieu of payment in DAI/ETH/etc for the monthly subscription and for plugin subscription/purchases, for gifting rotki subs, etc.

**Comment by kelsos** [comment]
On the frontend part, we could expose a similar mechanism used in our premium components to make dynamic feature specific micro-frontends that load per feature on each module.

**Comment by LefterisJP** [comment]
This is a general direction we have for the app and is not really an actionable issue. Exchanges are modular. With the new decoders so are the protocol modules. We still need to do a lot of work, especially making the frontend part of the modules, but this issue does not serve a purpose other than reminding us to "be modular" so closing it.
