### ISSUE TITLE
Add support for XFI token from dfinance

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2041]
ethereum balances isn't picking up XFI from dfinance.co

Contract address 0xe4e822c0d5b329e8bb637972467d2e313824efa0

These tokens were converted from WINGS tokens  into XFI

**Comment by LefterisJP** [comment]
Hey @Blackswan122 I can't find XFI from dfinance.co at all in either coingecko or cryptocompare.com. The only one that can be found there is: https://www.coingecko.com/en/coins/xfinance

If this dfinance.co XFI is an 1:1 swap from WINGS, then is it like an upgrade? Because we do support WINGS, and it's also on coingecko and cryptocompare: https://www.coingecko.com/en/coins/wings

If the price is the same then we can just query the price of wings for this XFI. If not, then we have no way to query the price if it's not listed in coingecko or cryptocompare at the moment.

**Comment by Blackswan122** [comment]
It’s listed on Coinmarketcap as being traded on UniswapV2 admittedly with very low volume. The swap from Wings to XFI gets release slow over a year period. It would be nice if someone could add it soon. I wrote to COINGEKO asking. 

https://link.medium.com/7MEZ8Zg0Rcb

**Comment by LefterisJP** [comment]
Fair enough. When either of them add it we will also add it. Keeping the issue open until then.
