### ISSUE TITLE
Importing IOTA trades from bitcoin.de throw errors

### ISSUE THREAD

**Issue by franzkugelmann** [rotki/rotki#2168]
## Problem Definition

On importing exchange data from bitcoin.de an error is thrown:
"Query trades of bitcoinde exchange died with exception: Unknown asset IOT provided.. Check the logs for more details"
This is probably the same issue as in https://github.com/rotki/rotki/issues/299 -> IOT needs to be mapped to IOTA

## Logs

The log is empty.

### System Description

Operating system: 
Rotki version: 1.12.2

**Comment by LefterisJP** [comment]
Hey @franzkugelmann thanks a lot for the bug report!

 Sounds like a mapping issue. Will get it fixed and include it in the next release.

> The log is empty.

Sidenote for that: We probably need to include it in the issue template but the log is always empty by default. You would need to activate the debug log mode as per the [docs](https://rotki.readthedocs.io/en/latest/contribute.html#id2) in order to get anything in the logs.

The reason is simple. The logs are unencrypted and when we had them on by default many of our users complained that sensitive data were kept unencrypted and in plain text in their system. So they are now off by default.

Here probably logs are not needed though, as it does indeed sound like a mapping issue.

-----

re: testing

I don't have any bitcoin.de account with trades so can't do a real integration test it so you would be the one to verify the fix works at the end. I can also provide you with a nightly once fixed so you can try it before the release if you would like. Best way to communicate would be via our discord: https://discord.gg/aGCxHG7 but can also use this issue.


----

@coinyon another note here. For other exchanges we have mapping tests to make sure such errors never hit our users and that there is a properly mapped asset for each exchange asset. Such as [here](https://github.com/rotki/rotki/blob/9aebabfe58c7f0385f6d5fcf7123e68ce7644adb/rotkehlchen/tests/exchanges/test_binance.py#L163-L191) for binance.

Can we make such a test for bitcoin.de too? I can't find an api call that can accomplish that when looking at their [API docs](https://www.bitcoin.de/de/api/tapi/v4/docu) but perhaps that's due to my non-native German knowledge.

But what's strange is that [here](https://www.bitcoin.de/en/api/tapi/v4/docu#handelspaarliste_c2f) in the docs they have a list of pairs and there `IOTA` appears as `IOTA` and not `IOT`.

**Comment by coinyon** [comment]
@LefterisJP Yea a test like that is included here: https://github.com/rotki/rotki/blob/9aebabfe58c7f0385f6d5fcf7123e68ce7644adb/rotkehlchen/tests/exchanges/test_bitcoinde.py#L80

I could find any API endpoint either so I hardcoded the pairs. IOTA support is still missing.

**Comment by coinyon** [comment]
Ah ok, I only added the EUR pairs from the docs. Will add the BTC pairs as well.

**Comment by LefterisJP** [comment]
> Ah ok, I only added the EUR pairs from the docs. Will add the BTC pairs as well.

Thanks :+1: 

> I could find any API endpoint either so I hardcoded the pairs. IOTA support is still missing.

What is missing for it? Just the mapping? That should be trivial to add it it's just (bitcoin.de)IOT -> IOTA (rotki)

**Comment by franzkugelmann** [comment]
Thanks @coinyon, the import is running without issues now in 1.13.1. However in the trades list i see "bitcoin.de buy IOTA_BTC", but i sold IOTA for BTC.

**Comment by LefterisJP** [comment]
Hey @franzkugelmann thanks for reporting. This sounds like a mistake in the deserialization of the pair for iotabtc. @coinyon Do all your pairs work properly for your own data? Does each pair need special handling or is there a bug in the way it's done at the moment?

@franzkugelmann We will have a look. @coinyon is the best person to do since he has bitcoin.de data. Nobody else I know does.

I could also help if you provided me with a read only api key and told me exactly what you expect to see. If you are comfortable with this you can simply DM me in discord and I will find the problem for sure since we won't need to guess but have actual data.

**Comment by coinyon** [comment]
Hi, yes all my pairs work correctly. But I only have fiat trades, maybe there is a mixup on Bitcoin.de's side when doing non-fiat trades.
