### ISSUE TITLE
Alt coins - ERC20 or ERC677

### ISSUE THREAD

**Issue by ciprianiacobescu** [rotki/rotki#2218]
In the Dashboard I'm missing coins like STAKE, SORA or DexTools. I've scanned the docs but I couldn't find a way to add them. Data about price is available on coingecko and cryptocompare.

A nice feature would be to add ETH (ERC20 or ERC677) coin id and symbol and check if coingecko has it listed. 
Show success and add price data to dashboard, otherwise  show an error. 

Is there a file I could modify to include coins in my portfolio?

**Comment by LefterisJP** [comment]
Hello @ciprianiacobescu welcome!

To answer your questions:

> 've scanned the docs but I couldn't find a way to add them. Data about price is available on coingecko and cryptocompare.

1. Yes you can add new coins to rotki, open a Pull Request and if there is a price history in any of the oracles the PR will be accepted. We have a how-to here: https://rotki.readthedocs.io/en/latest/contribute.html#adding-new-assets-to-rotki

> A nice feature would be to add ETH (ERC20 or ERC677) coin id and symbol and check if coingecko has it listed.
Show success and add price data to dashboard, otherwise show an error.

So something similar to what we need to implement for this issue: https://github.com/rotki/rotki/issues/1519
We want to do this, it's on the roadmap.

---- 

If the above answers satisfy your questions please close the issue.

**Comment by ciprianiacobescu** [comment]
Thanks!
