### ISSUE TITLE
DivisionByZero when generating Profit and Loss Report

### ISSUE THREAD

**Issue by jenkadit** [rotki/rotki#2220]
## Problem Definition

Generating a Profit and Loss report results in the following error:

```
An unexpected response was received while generating the profit and loss report. This might indicate an issue with the generation mechanism. Please check the logs for any error messages (you might have to enable debug logging first) and create an issue.

The backend query task died unexpectedly: [<class 'decimal.DivisionByZero'>]
```
## Logs

```
[30/01/2021 14:58:00 CET] DEBUG rotkehlchen.accounting.events: Processing sell trade of ETH for EUR at 1587032943
[30/01/2021 14:58:00 CET] ERROR rotkehlchen.api.rest: Greenlet for task 8 dies with exception: [<class 'decimal.DivisionByZero'>].
Exception Name: <class 'decimal.DivisionByZero'>
Exception Info: [<class 'decimal.DivisionByZero'>]
Traceback:
   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen/api/rest.py", line 268, in _do_query_async
  File "rotkehlchen/api/rest.py", line 1300, in _process_history
  File "rotkehlchen/rotkehlchen.py", line 571, in process_history
  File "rotkehlchen/accounting/accountant.py", line 332, in process_history
  File "rotkehlchen/accounting/accountant.py", line 597, in _process_action
  File "rotkehlchen/accounting/accountant.py", line 241, in trade_add_to_sell_events
  File "rotkehlchen/accounting/events.py", line 442, in add_sell_and_corresponding_buy
  File "rotkehlchen/accounting/events.py", line 509, in add_sell
  File "rotkehlchen/fval.py", line 88, in __truediv__
```

### System Description

Operating system: Fedora Linux 33
Rotki version: 1.13.0 appimage

**Comment by LefterisJP** [comment]
Hey @jenkadit thank a lot for the issue. This is unexpected and super interesting! Never seen that before in either production or in our tests.

Looking at the code around the place where the exception occurs:

```python
            SellEvent(
                amount=selling_amount,
                timestamp=timestamp,
                rate=rate_in_profit_currency,
                fee_rate=total_fee_in_profit_currency / selling_amount,  # <--- here is the culprit
                gain=gain_in_profit_currency,
            ),
```

The division is with the selling amount. So it seems you somehow got a sell of 0 of something in there. Can you look at the logs around a bit more and see more information of what is being processed? Selling 0 of something makes no sense.

We should naturally handle it better, and we will thanks to you finding this, but I want to see where did that come in from.

**Comment by LefterisJP** [comment]
Looking at the code what I can I can imagine is that somehow a zero price was returned for the asset at the given time and that it was a crypto to crypto trade that also generated a virtual sell. And the sell amount there is created from the price and the amount ...  and if price is 0 the sell amount ends up being zero.

In that case it should be skipped and an error logged in the logs.

**Comment by jenkadit** [comment]
In the logs I see

`{"entry": {"fee_currency": "ETH", "amount": "0.00", "trade_type": "sell", "timestamp": 1587032943, "fee": "0.01000", "location": "bitstamp", "notes": "", "pair": "ETH_EUR", "rate": "156.65", "link": "110769053", "trade_id": "d0e91edaf3f96a57e0d632192b49681410cfe6eee4f79eef8a86c0626dc6cb61"}, "ignored_in_accounting": false}`

Seems like it's due to rounding somewhere, in the Bitstamp UI I see a corresponding transaction for 0.00000798ETH (remeinder of a partially fulfilled order)

**Comment by LefterisJP** [comment]
Interesting :thinking: 
We do not do any rounding on rotki in the calculations so a zero amount should never reach there due to that. One option is that bittrex itself returned a zero amount there.

Let's see then. Can you go to your trades history tab and find the trade there and see the amount? By default in the frontend they are displayed with 2 decimal points of accuracy but if you hover over the number the whole thing should be shown.

P.S.: For faster back + forth you can also chat with me or the other devs in our discord: https://discord.gg/aGCxHG7

**Comment by jenkadit** [comment]
I don't get a tooltip when hovering over it, so I assume it actually is 0. Might be nicer if a tooltip was always shown, even when the number shown is exact.

Is there a way to log the raw http ouput? If not, I could check what the Bitstamp (not Bittrex as you wrote) API actually returns myself if I find the time (lack of time is also why I prefer Github issues over Discord)

**Comment by LefterisJP** [comment]
So that means the number we got from bitstamp is exacly 0 then.

Or at least that's what our deserialization got. I can't see any log entry that contains raw bitstramp results. Could also be a an edge case with our bitstamp interface.

The only way to be sure is to either:

1. I create a nightly with more debug logs in bitstamp which I give you, you purge all bitstamp data from settings -> data and then query the bitstamp trades again and see the logs to see the additional output and you post it here.
2. You create a view only api key and send it to me via discord or email (lefteris@rotki.com) and I can debug and find the issue myself.


(1) is gonna take a lot more time and back and forth
(2) is gonna be much faster, but requires trust that I don't share anything I see (I won't )

**Comment by LefterisJP** [comment]
The issue is closed due to some commits I pushed into the bugfixes branch which will not allow this to happen anymore. Will be included in the next release.

But as discussed above we uncovered something that still needs more investigation about that particular bitstamp trade. The nightly with a bit more logs will be generated tonight and I can give you to try scenario (1). You can also do (2) from above to speed up the process.

Also keep in mind if you just want to get over this and keep on with the tax report you can select that particular trade and click the "ignore for accounting" button. Then it will be skipped in the profit/loss report completely and the bug won't hit.

**Comment by LefterisJP** [comment]
Hey @jenkadit here is the linux nightly for you to try: https://github.com/rotki/rotki/suites/1934134152/artifacts/38170898

Please purge all bitstamp data from settings -> data and then query the bitstamp trades again and check the logs to see the additional output containing the raw bitsamp object json response for each trade. This way we can spot where the error is.

**Comment by jenkadit** [comment]
`[31/01/2021 14:19:44 CET] DEBUG rotkehlchen.exchanges.bitstamp: Attempting to deserialize bitstamp trade: {'fee': FVal(0.01000), 'order_id': 1221418771345409, 'datetime': '2020-04-16 10:29:03.550000', 'usd': FVal(0.0), 'btc': FVal(0.0), 'eth': FVal(-0.00000798), 'eth_eur': FVal(156.65), 'type': 2, 'id': 110769053, 'eur': FVal(0.00)}`

**Comment by jenkadit** [comment]
And in fact in the Bitstamp UI I now also realized it does say 0.00 EUR. So it seems Bitstamp split a trade so that I got no money from it, but had to pay 0.01€ in fees.

**Comment by LefterisJP** [comment]
Hah that's super interesting. So this is something we need to then take into consideration. A trade for 0 amount is then possible in bitstamp. Can you open another issue for that? If not I will open one when I get into my computer.

Thank you so much for taking the time to run the nightly and provide us the additional logs.
