### ISSUE TITLE
Detect Loopring balances and display them in rotki.

### ISSUE THREAD

**Issue by MysticRyuujin** [rotki/rotki#2235]
## Abstract

Loopring deposited assets, and LP tokens

## Motivation

Gimme da loopring!

## Specification

I assume this is possible given that Zapper can display them

**Comment by LefterisJP** [comment]
Nobody has asked us for integration with any of the various L2 in ethereum yet. Would have to see how hard it is. Would be indeed cool to have. Could you DM me a test address or something?

**Comment by aspiers** [comment]
I just started using Loopring and would love to see this too.  Is it worth adding a new `Layer 2` label for this and #528 and possibly also #851?

It's easy to make a deposit into the Loopring layer 2 via https://exchange.loopring.io/ but based on what I see on Etherscan that won't be very useful as mainnet tells you nothing about what's happening in the layer 2.

**Comment by LefterisJP** [comment]
hey @aspiers I did put the label here and in the other ones. We will figue loopring balances out in the near future. Balance query should be the easiest thing, but would still require some work (perhaps an api key on the user -- still figuring it out on their discord).

 Eventually we should also support the whole exchange thing they do, but this is for another issue.

**Comment by LefterisJP** [comment]
So seems like the idea is to:

1. Ask user to get their api key from loopring and input it in Rotki: https://docs3.loopring.io/en/basics/key_mgmt.html
We have checked with them and the api key alone can do nothing without signatures, plus with rotki you can see what we do with it since we are opensource.
2. Store the loopring api key in the DB
3. From their [api docs](https://docs3.loopring.io/en/REST_APIS.html) call the endpoint to find the account id associated with an L1 ethereum account: https://api3.loopring.io/api/v3/account?owner=0xXXX. Store it in the DB. No need to query it again.
4. Using the api key + and the account id we get for each address of the user from the previous key get the current balances: https://api3.loopring.io/api/v3/user/balances?accountId=XXX

**Comment by aspiers** [comment]
Sounds great, thanks a lot!  BTW does the `ETH DeFi` label apply to this issue and also #528?
