### ISSUE TITLE
Add ledger action for airdrop, and for gift and add setting for taxability or not of each type of ledger action

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#2237]
## Abstract

Currently there is no ledger action type specifically for airdrops.

## Motivation

Airdrops are not neccessarily income. Depends on the jurisdiction and other things. Best to record those events as a special action type and decide during tax report/pnl how to deal with those.

## Specification

Add an LedgerActionType called AIRDROP or GIFT.

**Comment by coinyon** [comment]
Or `WINDFALL_PROFIT` : https://www.investopedia.com/terms/w/windfall-profits.asp

**Comment by LefterisJP** [comment]
I will change this to untaxed income. So it just does not count as taxed profit at all. Each jurisdiction handles airdrops and gift differently and we don't yet offer any customization there. So for now and until we do it proably makes more sense to have income that counts as taxable income, and income that is not counted as taxable income.

At least that's what I understood from our conversation in the chat.

**Comment by coinyon** [comment]
Sure, but then you make the decision about taxes on data entry / retrieval. I think I'm a fan of recording the event, and deal with it later based on the configuration.

But for now I can live with "untaxed income", as long as it is semantically the same as a buy with 0 costs.

**Comment by LefterisJP** [comment]
> Sure, but then you make the decision about taxes on data entry / retrieval.

That's a fair observation.

The problem then is that we would have to probably start distinguishing between the various types of airdrops, since some may be taxable, some may be not and then we would need to start adding even more categories. And on top of that we would need to add customizable options for each category.

By just separating it as taxable income/ non taxable income you can control how each event is handled by rotki. Even if it's a new event type you just ask your accountant and classify it as what it is. If at some point you learn it should be handled differently you just go and edit the type from taxable to non taxable income or vice versa.

But if we go with airdrop, gift, xxx, yyy, zzz then we also need to implement a boolean setting for each of them whether they are to be conidered as taxable income or not and add them in the app's logic.

**Comment by coinyon** [comment]
Yea, got you. However, in the future, when we think about automatic data retrieval for an ETH address, the ledger action might have to be recorded without the user's intervention. Thats why airdrop make most sense, because thats what it is.

But let's go with your proposal and re-evaluate at a later date.

**Comment by LefterisJP** [comment]
I had some time to sleep over it. I think what you suggest is in the end better.

So for each ledger action that counts as income we should also have a setting. Count it as taxable income or not. And this way each time we add new types we would need to add  new setting.

Will need a bit more work, not much, but will be more correct and easier to customize in the end.

**Comment by LefterisJP** [comment]
@kelsos I would like your opinion here on how the setting should look like in the backend and in the frontend.

Should we have a boolean setting per action type? Or just a kind of a matrix setting in ... perhaps json, with all action types and true/false for each?

Also how would the component of customizing them look in the frontend? Any suggestions?

**Comment by kelsos** [comment]
If it is per action type I would guess the matrix approach would make more sense. we can have get edit endpoints that return the type and boolean and also get the same as input. 

A simple table with a checkbox would be enough I guess.

**Comment by Michael-A-Heuer** [comment]
The centralized tax software accointing.com works with a tax consulting company and has come up with a quite extensive list of classifications.

Similarly to #1596 they discriminate between deposit/income and withdrawal/expenses.

Classifications for income transactions would be
- add funds (if you transferred it from an account you own)
- income (if you earn money for doing something e.g. working for someone or even watching ads in the Brave Browser)
- swap
- lending income
- mining
- master node
- initial coin offering (ICO)
- over the counter trade (OTC)
- margin gain
- bounty
- gift received
- airdrop
- hard fork
- gambling income

and for expenses
- remove funds (if you transferred it to an account you own)
- payment
- swap
- fee
- gift sent
- over the counter trade (OTC)
- gambling use
- margin fee/loss
- interest paid
- lost (private keys are gone)

By specifying how these transaction types are treated tax-wise, the user could adapt the tax software to a specific legislation.

**Comment by LefterisJP** [comment]
Hey Michael, this issue is closed and implemented for v1.14.0.

Do you want us to add all these other types? For now we have only added airdrop/gift/grant.
It's not hard to do so. And each one would be customizable if it's considered as taxable in the PnL or not.

The ones I see fitting in ledger actions is.


- add funds to own accounts
- lending income
- mining
- master node
- margin gain (even though we should normally support them for exchanges eventually)
- bounty
- hard fork (this we detect by considering the amount of asset you had at the time of the fork. Works for ETH -> ETH, BTC -> BCH, BCH -> BSV. But we can add it for the more generic case of non detected ones.
- gambling income (what is this? Like for lotteries?)

For expenses:
- funds sent to own account
- gift sent
- gambling use (again what is this?)
- margin loss (this should be detected eventually for most exchanges)
- interest paid (again this is mostly auto detected in DeFi)


For the rest:

- swap, ICO, OTC -> manual trade in rotki
- payment -> expense
- fee -> expense
- lost -> loss

**Comment by Michael-A-Heuer** [comment]
From my side this doesn't need to be implemented now. Just wanted to put it somewhere to close issue #2302 as you suggested. I didn't see that it was closed already yesterday.
