### ISSUE TITLE
A general classification scheme for crypto events

### ISSUE THREAD

**Issue by Michael-A-Heuer** [rotki/rotki#2302]
## Abstract
This is more a proposal than a request for a general classification scheme for crypto events.

## Motivation
Different rules exist for the taxation of crypto-related events (deposit, withdrawals, trades, in general: transactions).
Although, the treatment of such events differs heavily between specific legislations, general classification types arose in the past.

Cryptotax services like https://www.accointing.com/de implemented such classifications for automatic tax report generation.

Classification examples  from www.accointing.com are listed in the following:

**Deposits** (assets flowing into an account)
- add funds
- income
- swap
- lending income
- mining
- master node
- initial coin offering (ICO)
- over the counter trade (OTC)
- margin gain
- bounty
- gift recieved
- airdrop
- hard fork
- gambling income

**Withdrawal:**  (assets flowing out of an account)
- remove funds
- payment
- swap
- fee
- gift sent
- over the counter trade (OTC)
- gambling use
- margin fee/loss
- interest paid
- lost

and the general option to 
- **ignore** transactions 

or to specify
- **internal** transaction (between own accounts)

## Specification
After the data import from blockchains and exchanges, users see all unclassified events listed in Rotki.
Then, they can manually (or even automatically, based on a database lookup) classify these events.
Then, they can specify the tax treatment and an adapted tax report is generated.

Long term, such a feature could allow Rotki users to generate tax reports adapted to specific legislations by only changing the taxation method of how such events are treated.

For the automatic classification, users could curate a database of specific events (e.g. the [SAI to DAI migration on Coinbase](https://help.coinbase.com/en/coinbase/trading-and-funding/cryptocurrency-trading-pairs/dai-faq)) to be considered in the tax report.

I am well aware that this is a major proposal requiring complex changes and a lot of work, which might be not in line with the short- and long-term goals of Rotki.

**Comment by LefterisJP** [comment]
We already have the various ledger actions which users can enter manually. They will be classified depending on the action that the user chooses. We can add more actions as per user request: https://github.com/rotki/rotki/issues/2237

Then we will have as per the same issue a matrix setting on how to treat these events. Tax them or not. e.g. tax airdrops or not etc.

We will also allow classifying manually a part of a blockchain transaction as a specific ledger action: https://github.com/rotki/rotki/issues/1596

I don't know if we have an issue for best effor automatic classification of detected blockchain transactions. Closest thing we have is this: https://github.com/rotki/rotki/issues/1477

In the end internally and also ledger actions are all either acquisitions or spends. What you call deposits/withdrawals.

In the long run indeed what we want is very close to what you describe. This is what Rotki will become. It just takes time and money.

What I would like to have to help us get there is small actionable issues. This issue here can stay for a bit until it's linked to all the various sub-issues and all the feedback is extracted from it. But once we got all action items documented in other issues I think we could close this.

Love all feedback like that which can help us make rotki into the best accounting tool for you guys.

**Comment by Michael-A-Heuer** [comment]
It can definitely be closed. It is sometimes difficult to see the bigger picture in the plethora of issues you are getting.

**Comment by LefterisJP** [comment]
In no hurry to close. First I would like to make sure that all the things you are asking are somehow scheduled and in an issue. Can you help us make sure that is indeed so? I want to value all feedback from users.

**Comment by Michael-A-Heuer** [comment]
Sure, I think I can do it during the weekend.

**Comment by Michael-A-Heuer** [comment]
Added this as separate comments to the issues #2237 and #1477.
