### ISSUE TITLE
ETH amount too high on an address with Maker vault

### ISSUE THREAD

**Issue by koeppelmann** [rotki/rotki#2306]
## Problem Definition

I have an address that hold some ETH, WETH but also a larger amount of WETH in a maker vault.
The total amount of WETH (including the WETH from the vault is calculated). However - the amount of ETH the address hold is shown significantly larger than it actually is. It seems that the amount of WETH in the vault is counted twice for ETH and WETH.
The result is that the "Total USD value of accounts assets" is almost double then what it actually is. 

### System Description

Operating system: MacOS
Rotki version: 1.13.1

**Comment by LefterisJP** [comment]
Hey @koeppelmann this is a known issue with v1.13.1. It's already fixed in develop: https://github.com/rotki/rotki/issues/2294

The fix will either be included in v1.14.0 end of next week or in another patch release earlier than that.

Your options until then is to switch back to v1.13.0 or use develop until this happens.

To stay up to date with our developments (and issues like that) also join our discord chat: https://discord.gg/aGCxHG7

**Comment by LefterisJP** [comment]
Hey @koeppelmann the fix for this is now included in v1.13.2: https://github.com/rotki/rotki/releases/tag/v1.13.2
