### ISSUE TITLE
UX: Consider renaming "Ledger actions"

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#2464]
I found the "Ledger actions" page of the History section a bit confusing.  Of course [#2463 (Document History section)](https://github.com/rotki/rotki/issues/2463) would help with this, but I think part of the problem is the name.  From a conceptual PoV, trades, deposits, withdrawals etc. are all ledger actions, so it doesn't make much sense to me to have a section called "Trades", another section called "Deposits & Withdrawals", and then a separate section called "Ledger actions".

Instead, ideally this would be named in a way which makes it clear how it is different from the other sections.  And the essential difference between ledger entries in this section vs. all the other sections, is that entries in this section are entered manually.  

So how about renaming it to "Manual transactions" or something similar?

**Comment by LefterisJP** [comment]
Indeed ledger action is a term used as an umbrella for all events. Not only transactions. We already got the manual trades that can be added from the trades section. And in the Ledger actions section we got all the rest of the manual events.

In the backend we named them ledger actions. So we just kept the same name in the frontend, as it's well known that naming things is one of the hardest things in computer science :smile: 

But perhaps having all manual historical events under one section would make sense? I am not sure. Also naming can change easily in the frontend. Backend a bit harder since schemas would need to change names. And well ...frankly this is a UX issue, so backend can probably lag behind a bit.

**Comment by LefterisJP** [comment]
> Another point: I'm confused by the presence of 'Ethereum transactions' here, t

It's the general category of blockchain transactions that will go there. It's just that at the moment we don't automatically pull bitcoin transactions. We will soon do that. But also kusama transactions etc.

**Comment by aspiers** [comment]
[**@FrankvanCaspel**](https://github.com/FrankvanCaspel) commented on [March 2, 2021 10:06 PM](https://github.com/rotki/rotki/issues/2464#issuecomment-789254138 "2021-03-02T22:06:52Z - Replied by Github Reply Comments"):
> Another point: I'm confused by the presence of 'Ethereum transactions' here, that seems to be a bit of a category mistake. Why are transactions for one particular crypto in this menu? Why not also 'Bitcoin transactions'? It appears to me that Ethereum transactions could be either trades, or deposits/withdrawals, or other transactions - why do they need a separate category?

Agreed - I pointed out this exact point in #2469 and proposed a way to fix it and several other issues at the same time.

**Comment by LefterisJP** [comment]
I am closing this issue as the name has stayed there for more than a year and I don't; see it going away any time soon. We may consider a big redesign at some point at which case we will take this feedback with us and rename it but for now priorities are different.
