### ISSUE TITLE
External trades not reflected in balances

### ISSUE THREAD

**Issue by FrankvanCaspel** [rotki/rotki#2478]
(I'm guessing this is user error on my part, but after going through the documentation and playing around for a bit I'm at a loss.)

Problem: external trades are not reflected in my balances. From the usage guide:

> Rotki will pull all your trade history from the exchanges whenever it needs it. But most of us have probably also done some OTC trades or taxable events at some point. Such events could even just be mining tokens, depending on your jurisdiction, participating in an ICO or getting paid in crypto.

> On the left sidebar click on the trades button and select “OTC Trades” from the dropdown menu. This will take you to the OTC Trades page.

Since the OTC Trades page no longer exists, I'm assuming this is now done via the 'Add external trade' option, by clicking the big plus at the top of the order table. 

Example: 
1. I have some Nano which I added to my portfolio at the 'Manual balances' page under 'Accounts & Balances'. This shows up correctly in my dashboard under 'Assets'.
2. A friend then sends me some Nano. I want to update my portfolio to reflect this, and per the instructions above I add an external trade: a 'buy' of some Nano.
3. Expected behavior: the balance of Nano at the dashboard is changed by the amount added in the external trade. Actual behavior: the balance stays the same.

Am I going about adding non-exchange mutations to my portfolio in the right way? I feel like I'm missing something. How should I update my portfolio if I sell something for crypto, or if I buy something with crypto? Should I just update the manual balance? That means there's no record of that 'trade' / transaction.

Operating system: Windows 10
Rotki version: 1.14.2

**Comment by LefterisJP** [comment]
You seem to be confusing the portfolio tracking and the accounting sections of the application which are different.

Your current balances are reflected by what we can detect in all of your tracked accounts and by the manual balances. This is the porfolio tracking part of the application.

The accounting part of the application is different.And this is where all the trades (autodetected or manual), ledger actions etc. are coming into play. These are used to calculate profit/loss in a given period, cost basis of each sellf, cost basis of each asset etc.

As for the docs we are trying to update them but since both our field and the app is moving really fast it's pretty hard to keep them up to date.

For questions like that please also just ask in discord where it's easier to chat and explain things: https://discord.gg/aGCxHG7

**Comment by FrankvanCaspel** [comment]
Thank you so much for the response! I'll get over to Discord if I have any more of these questions.
