### ISSUE TITLE
Rounding error in balance amounts

### ISSUE THREAD

**Issue by FrankvanCaspel** [rotki/rotki#2479]
Amounts are _nearly_ always incorrectly rounded up, such that a balance of 0.011 is rounded up to 0.02, when the floating point precision is set to 2. I have added a particular blockchain balance which correctly shows 0.011 when I have a floating point precision of 3, but when I change it to 2, the balance is shown as 0.02. 

The incorrect rounding is shown here:
- If you go to Accounts & Balances, and click on the specific asset. Under 'amount' in the table it shows the wrong amount.
- The total owned on that same asset page is also wrong, apparently based on the rounded numbers in the table below.
- On the Dashboard under assets it also has the wrong total.

However, the _correctly_ rounded total also makes an appearance:
- If you go to Accounts & Balances and look at the table of 'blockchain balances per asset' (so without clicking on any particular asset), there you see a correctly rounded total.

Operating system: Windows 10
Rotki version: 1.14.2

**Comment by LefterisJP** [comment]
This rounding is only for display purposes and it depends on your given settings. The amounts are never rounded in the calculations. You can see the actual amount if you hover over any such number.

https://user-images.githubusercontent.com/1658405/109712165-fd065800-7b9f-11eb-8515-8a516f464a3e.mp4

Total owned in the assets table, like everything else is also rounded, but again the actual amount is shown when you hover over the number.


https://user-images.githubusercontent.com/1658405/109712292-27581580-7ba0-11eb-8944-e4bafd92742f.mp4

I think this probably answers your issue so I will take the liberty of closing it.

 If not please reopen - or comment further and we will see what can be done.

**Comment by FrankvanCaspel** [comment]
Nope, I do think there's an issue here. You are right that hovering over the amount shows the actual number, but still this can't be how it should work:

![afbeelding](https://user-images.githubusercontent.com/17382771/109713234-3ee3ce00-7ba1-11eb-8605-88e23d4c2689.png)

The unrounded total is correct, and it's good that that is used for calculations. However, even if it's only for display purposes, I'd venture to guess that most people would want this to behave differently :)

**Comment by LefterisJP** [comment]
Reopening the issue. I now understand the user says that in many places a really weird rounding algorithm is followed. Rounding to next decimal and not closest.

**Comment by a7e8** [comment]
Personally I think the main issue here is that decimal precision is shared with fiat currency and cryptos. I would prefer it to be separate and have no rounding of crypto at all.

**Comment by LefterisJP** [comment]
> Personally I think the main issue here is that decimal precision is shared with fiat currency and cryptos. I would prefer it to be separate and have no rounding of crypto at all.

No that's not it. This issue is for:

>  Rounding to next decimal and not closest.


>  I would prefer it to be separate and have no rounding of crypto at all.

You can make an issue for this and we can consider this. So essentially a different floating precision setting for crypto and a different one for fiat. Note: This would make tables look really ugly because they would not line up. @kelsos correct me here if I am wrong, but I remember you mentioning something like this.

**Comment by a7e8** [comment]
Yes I understand that's not what this issue is for, but if you didn't have rounding it wouldn't be an issue in the first place.

**Comment by LefterisJP** [comment]
> Yes I understand that's not what this issue is for, but if you didn't have rounding it wouldn't be an issue in the first place.

it would not be possible to not have rounding in the UI. Things would not align at all. If you want a different custom setting feel free to make an issue.

**Comment by kelsos** [comment]
The rounding of numbers is something we discussed extensively back in Summer. 

We decided to go with rounding up for crypto amounts displayed. The reason is that for assets that have a high value if you do a proper rounding to the nearest or just cutoff then the amount would display as zero.

Let's say for example that you have 0.0001 BTC and you have a two decimal display, with rounding upwards this would display as 0.01 (while inaccurate because you own way less this indicated that you own some BTC) if we cutoff or round to the nearest that would appear 0.00.

There are different ways to handle this, and I have seen a lot of applications, everyone does a different thing. 

For fiat the default is rounding down since physically you cannot have more than 2 decimal points.

I would say the best approach would be to keep the default, because the reasons we introduced it didn't change, and allow the user to customize the rounding for Crypto amounts.

**Comment by LefterisJP** [comment]
> I would say the best approach would be to keep the default, because the reasons we introduced it didn't change, and allow the user to customize the rounding for Crypto amounts.

So @kelsos then can you rename and re-adjust this issue to be used for customization of crypto amounts rounding method?

**Comment by a7e8** [comment]
Ledger Live recently made a change to their rounding method:

> Amounts are now rounded down to not be deceptive.

https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.23.0

**Comment by kelsos** [comment]
@a7e8 Do you have access to any screenshot where ledger live displays really small amounts? how do they show them in the UI?

**Comment by isidorosp** [comment]
What if we revert to rounding to nearest but for cases that are > 0 but if rounded to nearest would display "0.00", we display "`> 0.00`" (or conversely `< 0.01`) instead of just "0.00"?

**Comment by kelsos** [comment]
@isidorosp I am ok with the < or ~ or > part. This is actually what we were doing in the previous project I was working on.

**Comment by LefterisJP** [comment]
Wouldn't this break alignment?

**Comment by isidorosp** [comment]
Because numbers are right-aligned in general so since we're not increasing the number of "spaces" we need on the right hand side alignment shouldn't be affected.

**Comment by kelsos** [comment]
@LefterisJP well if you put the currency in-front it will take some extra space, but we already have hardcoded values there so it won't be worst than before. The same problems we have will still apply.

With the asterisk, it was on the right side like @isidorosp mentioned that's why it would break alignment

**Comment by LefterisJP** [comment]
Well try that then and see how it goes. And maybe if it's not too much work also make the choice of rounding for crypto configurable to delegate this to the user. But if 0.00...00 is displayed for non 0 amounts and we add an indicator like suggested to signify it's actually not zero then that's good.

**Comment by kelsos** [comment]
It shouldn't be much work. Luckily we have a single component :D

**Comment by a7e8** [comment]
> @a7e8 Do you have access to any screenshot where ledger live displays really small amounts? how do they show them in the UI?

It's probably better to study their source: https://github.com/LedgerHQ/ledger-live-common/blob/master/src/currencies/formatCurrencyUnit.js#L84

**Comment by kelsos** [comment]
> > @a7e8 Do you have access to any screenshot where ledger live displays really small amounts? how do they show them in the UI?
> 
> It's probably better to study their source: https://github.com/LedgerHQ/ledger-live-common/blob/master/src/currencies/formatCurrencyUnit.js#L84

Thanks I will have a look at it
