### ISSUE TITLE
Allow deletion of crypto.com data from the DB

### ISSUE THREAD

**Issue by a7e8** [rotki/rotki#2507]
## Problem Definition

The crypto.com import had 7 errors relating to unknown entry types. I would like to be able to delete all the entries it imported until the import script is fixed.

**Comment by a7e8** [comment]
I manually deleted the entries using the guide here: https://github.com/rotki/dbscript

Would still be useful to revert imports without manual intervention.

**Comment by kelsos** [comment]
@LefterisJP do you think just adding delete functionality on the UI (I am guessing this requires also backend changes) would suffice?

**Comment by LefterisJP** [comment]
Import entries errors like this is why I don't like supporting external CSVs. They change all the time.

So for this I would like to see the errors.

> I manually deleted the entries using the guide here: https://github.com/rotki/dbscript

That's great you managed to do it by manipulating the DB!

But yes we need to be able to delete them. Which tables was it? Wouldn't the purge exchange data do it? I see crypto.com is not in there since it's not really a supported exchange. But I think it would work if the frontend has the option to send also "crypto.com" as the name to delete data if the data was in the trades and/or asset movements table:

```python
    def purge_exchange_data(self, exchange_name: str) -> None:
        self.delete_used_query_range_for_exchange(exchange_name)
        cursor = self.conn.cursor()
        cursor.execute(
            'DELETE FROM trades WHERE location = ?;',
            (deserialize_location(exchange_name).serialize_for_db(),),
        )
        cursor.execute(
            'DELETE FROM asset_movements WHERE location = ?;',
            (deserialize_location(exchange_name).serialize_for_db(),),
        )
        self.conn.commit()
        self.update_last_write()
```

**Comment by kelsos** [comment]
It could easily be added there I think

**Comment by a7e8** [comment]
After I did this import I wished I had taken a copy of the db file beforehand. Do you think it would be a good idea to take snapshots of the db and let the user revert to previous snapshots?

**Comment by LefterisJP** [comment]
users can always do that manually (I do it myself often but mostly due to using develop rotki version with my accounts and things break there).

Essentially copy the DB often in a directory. We can definitely automate that. Can you make an issue for that too?
A sort of related issue is [this](https://github.com/rotki/rotki/issues/2219) where users want to be able to access and manipulate (edit/delete) the balance snapshots of the DB data.

I guess both should appear in some kind of new section in the UI, manage DB or user data or something like that.

**Comment by a7e8** [comment]
Yeah I was just thinking that you could solve this problem in a generic way rather than just for this specific CSV import.

Apple has similar feature to revert to previous versions of a file (for inspiration).

**Comment by LefterisJP** [comment]
Yeah understand. But after reading what you said I took this issue as meaning, "Add crypto.com" to the "delete DB data" section :)

Which is actually missing.

**Comment by kelsos** [comment]
@LefterisJP Do you think adding also cointracking in the purge would make sense?

**Comment by kelsos** [comment]
@LefterisJP Does this require also changes on the backend? It seems that fails at validation

**Comment by LefterisJP** [comment]
I will have to check. Let's discuss in discord.

**Comment by LefterisJP** [comment]
@kelsos with https://github.com/rotki/rotki/pull/2536 in bugfixes, then you can actually call crypto.com in that endpoint. Had to make some adjustments as some endpoints should accept only the fully supported exchange location names and some all of them. The purge data endpoint falls in the latter category.

**Comment by LefterisJP** [comment]
With #2536 and #2537 rotki should now be able to delete crypto.com data from the DB.
