### ISSUE TITLE
Filter for 'saleable assets' that have been held for over 12 months (thinking of Germany)

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2608]
I think a feature that could filter out assets that are over 12 months old would be a neat addition. In Germany something that is held for 12 months becomes tax free. It's difficult to keep track of what is available to sell. I've no idea how easy or difficult this would be.

**Comment by LefterisJP** [comment]
Hey @Blackswan122 this is indeed something really important as also @kelsos and others have pointed out.

Implementation-wise it's a biggy unfortunately. We do already have an issue. It's here: https://github.com/rotki/rotki/issues/701

Essentially what will need to be happening is to have PnL report run since start of history underneath keep the results, and then from these results overlay them in the dashboard including the info you asked for but also other cool ones (if you check the issue) such as considering current price of asset and the average buy/sell price of yous buys/sells are you + or - and how much %.

REALLY want to have this too. It will happen. just give us time. Also need to grow the team to be able to cope with the demand.

**Comment by Blackswan122** [comment]
Ah great I didn’t see it thanks.
