### ISSUE TITLE
API Docs curl calls are not always correct

### ISSUE THREAD

**Issue by jpbrissette** [rotki/rotki#2612]
## Problem Definition

Long time MAC / Linux user.  First time using rotki.  Installed from homebrew.  Ran application as GUI, created users and set up exchange APIs as well as private wallets and some manual inputs.  Wanted to use API to get all transactions back out in a consistent format (CSV) which appeared to be possible once I purchased the API support.  Installed API Key for two accounts - one with transaction history and one with minimal.  Using the CURL format examples directly from Rotki API documentation, some of the calls worked and some did not.  Most important to me was the "Querying complete action history"  
curl -i http://localhost:4242/api/1/history/ -H 'Content-Type: application/json;charset=UTF-8' --data-raw '{"async_query": true}'  as well as the inability to run "Export action history to CSV".

## Logs

[Rotki API issue example with log data 2021-03-20.txt](https://github.com/rotki/rotki/files/6176833/Rotki.API.issue.example.with.log.data.2021-03-20.txt)

### System Description

john@mackie scripts % system_profiler SPSoftwareDataType                                                                                                              
Software:

    System Software Overview:

      System Version: macOS 11.2.3 (20D91)
      Kernel Version: Darwin 20.3.0
      Boot Volume: Macky_HD
      Boot Mode: Normal
      Computer Name: John’s iMac
      User Name: John Brissette (john)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:18

Operating system: 
Rotki version: 1.15.1

**Comment by LefterisJP** [comment]
Hello @jpbrissette thank you for using rotki and for finding the time to report an issue.

All api calls work as they are used by the frontend. We support usage of the rotki UI and can help you with any errors there.
All data you want can be exported in CSV by using that You can achieve the exact same result by using the api and the backend directly but you have to make sure you know how to make all calls. And it's really advanced usage. 

I can't say why some calls failed for you but taking one example from the logs you posted I posit it's due to errors in the way you called them.

```
curl -i http://localhost:4242/api/1/history/ -H 'Content-Type: application/json;charset=UTF-8' --data-raw '{"async_query": true}'
```

This is doing a `PUT` request. Since you are providing raw data as json. You would have to specify `-X GET` to do a GET request.

**Comment by jpbrissette** [comment]
I used the direct copy/paste of the examples from the Rotki api doc.

On the Mac app, port 5042 is not available at default.  There is no instruction how to expose that other port.  I cannot pip install zeropc since it appears to be deprecated.

"In life, there is no reset button"
John Brissette
________________________________

**Comment by LefterisJP** [comment]
@jpbrissette Thank you for the response. The calls in the docs are not meant to be directly copy pasted. You have to adjust for your system, your tools, your port etc.

The docs are auto-generating calls for curl, httpie and other tools. Perhaps the autogenerating library has a bug there. But the docs clearly states that the endpoint querying verb there should be a `GET`.

![2021-03-21_18-00](https://user-images.githubusercontent.com/1658405/111914034-b73b0200-8a70-11eb-9002-d15ccbe9147b.png)


I will have a look at the autogenerated calls for curl and see if they can be fixed as indeed it seems wrong.

In the meantime to be 100% sure things work, use the user interface.

For advanced things like using the API directly all questions are welcome but make sure to double check you are usign the call correctly. And if unsure just hop in our community chat to ask questions: https://discord.gg/aGCxHG7

---

I will keep this issue open with the actionable item of adjusting the curl (and other tools) calls in the documentaiton, or completely removing them.

**Comment by LefterisJP** [comment]
Hmm so the extension we use for the docs seems to be abandoned. No new release in 2 years: https://github.com/collective/sphinxcontrib-httpexample

We should probably remove it then and be left only with the first screen. Then the user can adjust for their own tools without making a mistake at copy paste.

**Comment by LefterisJP** [comment]
Hey @kelsos I would like your opinion here. As you can see here the docs example generation seems to have a bug I suppose due to using arguments in a `GET`.

Should we bother trying to fork and fix the extension? Or just remove the extra examples? Are they useful you think? We can discuss in the standup planning tomorrow.

**Comment by kelsos** [comment]
Ok doing a quick google search I can't seem to find an alternative so I would guess forking would make sense.

I think they are useful yes.
