### ISSUE TITLE
Statistics Don't Honor Date Format Setting

### ISSUE THREAD

**Issue by dlehenky** [rotki/rotki#2626]
## Problem Definition

The charts on the Statistics page do not show dates in the *modified* date format (for US) in Settings. All other areas of the app *do* show dates in the proper/modified format.

## Logs

N/A

### System Description

Operating system: MacOS Big Sur
Rotki version: v1.5.2

**Comment by LefterisJP** [comment]
Thanks for the report @dlehenky!

@kelsos This I suppose requires work on premium components to respect main app's date setting?

No need to press this for v1.16.0 since we only got this week. Schedule when you believe you can tackle it.

**Comment by kelsos** [comment]
@dlehenky just to confirm, is this issue referring to the dates in errors and available data hint, or the date-picker (I guess not), or the tooltips and date axis?

I fixed it for the errors and the available data range hint so after the next release these will properly respect the user-specified date format.

For the date-picker it is a lot more complicated unfortunately due to the fact that we also parse it back. Allowing customization there is harder since it would require along with the format a custom parser that would parse back this format. 

Finally, the tooltips and axis follow a different format since there is no time there, so these are not following the user-specified format..
