### ISSUE TITLE
Request for Support for Alchemist (MIST)

### ISSUE THREAD

**Issue by Billyjameshowell** [rotki/rotki#2682]
Contract address: 0x88acdd2a6425c3faae4bc9650fd7e27e0bebb7ab

**Comment by LefterisJP** [comment]
Thanks Billy.

Will go in the next version. You can also add it manually as documented in the release notes of v1.15.0: https://github.com/rotki/rotki/releases/tag/v1.15.0

**Comment by Billyjameshowell** [comment]
Thanks! I'll give it a shot

**Comment by Billyjameshowell** [comment]
This is awesome. works like a charm. Closing these tickets

**Comment by LefterisJP** [comment]
> This is awesome. works like a charm. Closing these tickets

happy to hear! I will still keep them open as if someone needs them it's good to see if we can add them to the default asset sto.

**Comment by Billyjameshowell** [comment]
I'm not seeing this asset in Rotki now. And when I try to manually add I get "Failed to add asset _ceth_0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB into the assets table for details id 0x88ACDd2a6425c3FaAE4Bc9650Fd7E27e0Bebb7aB".

**Comment by LefterisJP** [comment]
That probably means you got affected by this issue: https://github.com/rotki/rotki/issues/2791

If you don't have any other custom assets you care about the quickest way to get rid of the problem is to delete your global DB and let it be recreated. If you do we can still fix it but it's a tiny bit more work.

Hop in our discord and I can help you there: https://discord.gg/aGCxHG7
