### ISSUE TITLE
Create a deb package for Linux

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#27]
At the moment the created artifact for Linux is a zip archive of the app created by [electron-packager](https://github.com/electron-userland/electron-packager).

It would be beneficial to also have a deb package. Possibly the easiest solution would be to use [electron-installer-debian](https://github.com/unindented/electron-installer-debian) as suggested by electron packager's Readme.

**Comment by michael1011** [comment]
Any updates on this?

**Comment by LefterisJP** [comment]
Nothing yet. @kelsos do you think we could easily include it in our packaging process? If yes we can schedule it for next release.

At the moment we got community members and other users packaging it for some distros. e.g. for Archinux: https://aur.archlinux.org/packages/rotki-bin/

**Comment by kelsos** [comment]
With electron builder this should be trivial. We just need to do a small adjustment to the build config.

**Comment by kelsos** [comment]
I am adding it to the next milestone.

**Comment by kelsos** [comment]
I am moving it to the next milestone since I need to figure out some minor problems. Adding the deb generation is trivial but there seems to be a problem with the desktop entry created after that. The entry is created but the icon is a generic app icon. I spend some time trying things yesterday but I couldn't manage to get the icon working.
