### ISSUE TITLE
Wrong asset amount - Kraken

### ISSUE THREAD

**Issue by djjldoooo** [rotki/rotki#2737]
## Problem Definition
The Kraken KSM amount in Rotki is 15.31 but actually I don't have anymore KSM on Kraken.

## Logs
I didn't see any interesting log.

### System Description
Operating system: 5.10.23-1-MANJARO
Rotki version: 1.15.2

**Comment by LefterisJP** [comment]
Hello @djjldoooo balances do not auto-refresh.

Try (1) refreshing balances or (2) restarting the app

**Comment by djjldoooo** [comment]
I tried and it doesn't work. Actually I noticed this issue days ago so I restarted the app several times.

**Comment by LefterisJP** [comment]
@djjldoooo 

Are you sure you have no balance of KSM in kraken then? Are you perhaps staking KSM in Kraken? If you are then they are also counted. And Kraken displays it as 0 in the overview since it displays only spot balances in the overview.

You can confirm by going there and checking to see if you have a balance
![2021-04-16_09-39](https://user-images.githubusercontent.com/1658405/114989578-d8d4b100-9e97-11eb-9302-f5bc253e7ac7.png)

I am pretty sure that's what's happening. I also actively use Kraken a lot with rotki and I see no problem. If that's not the case then I will need the full debug logs.

**Comment by djjldoooo** [comment]
Thanks a lot and sorry. I completely forgot about this stacking.
