### ISSUE TITLE
Dashboard button in top bar

### ISSUE THREAD

**Issue by adrien-be** [rotki/rotki#2766]
I'm going back and forth between the dashboard and some deeper topics (onchain balances, specific asset view, etc) and it's rather annoying to have to click on burgermenu>dashboard each time to go back to the initial view (kind of landing view).

Since the dashboard is so important, would it be possible to add a link to it in the top bar?

**Comment by isidorosp** [comment]
Good point, but in general you should be able to work around this by just making your app window wider (unless you're limited by a small horizontal resolution). If the app is over a certain width (I don't recall the exact number of pixels right now) the navigation menu should, instead of being fully hidden, appear either as a slim bar or a full menu.
![image](https://user-images.githubusercontent.com/27592/115590717-9402ad00-a2d1-11eb-87c0-bfcb9cf67abc.png)

**Comment by LefterisJP** [comment]
As @isidorosp said we have a link to the dashboard always visible, even if you shrink the window size. Is that sufficient for you @adrien-be ?

**Comment by adrien-be** [comment]
Yes I see it now. I was using the app with a small resolution size so I
didn't have the icons on the left. All good thx!

**Comment by isidorosp** [comment]
> As @isidorosp said we have a link to the dashboard always visible, even if you shrink the window size. Is that sufficient for you @adrien-be ?

Nah if you make the window too thin then even the thin menu bar goes away (this is for like "mobile mode"). Perhaps we should make this a frontend setting @kelsos ?

**Comment by kelsos** [comment]
I will have to check how easy it would be for that.

**Comment by adrien-be** [comment]
Sweet. A wee icon at the top would be great.
