### ISSUE TITLE
Show y = 0 on all graphs

### ISSUE THREAD

**Issue by rkalis** [rotki/rotki#2820]
All the graphs (dashboard, net value, asset amount & value) have some arbitrary lowest value on the y axis, which makes small fluctuations look huge. I'd like to have (the option to have) these graphs start at y = 0, so that the changes in value / amount reflect the changes relative to the total amount.

**Comment by LefterisJP** [comment]
Hey @kelsos how can we do this for the graphs? Any idea?

**Comment by kelsos** [comment]
I will have to check how easy it is. To be honest I would prefer to add that as an option, so that users can choose between **0-max** based scaling and **min-max** based. 

Btw I don't think arbitrary is the correct term in this case. The lowest and highest in these graphs follow a specific pattern, they are based on the lowest and highest values in that specific period.

**Comment by isidorosp** [comment]
Agree it should be an option

**Comment by rkalis** [comment]
Yeah "arbitrary" isn't the right word. Having it as an option is perfect for me.

**Comment by rkalis** [comment]
Thanks guys!

**Comment by rkalis** [comment]
Just tried this out in the new version, it's great 🎉

**Comment by LefterisJP** [comment]
Happy you like it @rkalis

**Comment by kelsos** [comment]
Happy to deliver :) @rkalis
