### ISSUE TITLE
External Trades - Option to use Summary Prices instead of Rate?

### ISSUE THREAD

**Issue by Cebrain** [rotki/rotki#2854]
## Abstract

At the moment when you add an external trade and setup an Time and a Trade Pair the prices gets fetched automatically.
This feature is great in general but on some Crypto Stores you only see a "Summary" Price (mostly with € and $) on the Quote or Webpage. Also the fetched prices are mostly different then on the stores.

## Motivation

Now it is necessary to use a calculator more or less to get the correct asset price.
It would be great if it would be possible to add the amount of bought Tokens and a the Complete price of the order:

Example (no correct prices ;))
I bought 200 XLM with 100$ and have 1$ fees
So it would be great i can directly add 200 XLM bought with 100$ and 1$ fee.

**Comment by LefterisJP** [comment]
You can edit the automaticaly fetched rate!

As for the other thing you are asking it's the same thing, it just requires you to use a calculation if the place where you got has quote asset amount instead of rate. Some places (especially the first exchanges rotki supported) use the rate, as rotki does.

We could at some point allow addition in both ways, but that would be a frontend only thing. On the backend we have to choose a single representation. Which is the rate.

I think this request has already been made here: https://github.com/rotki/rotki/issues/2446

So if you agree it's the same thing please close the issue in favour of that one.

**Comment by Cebrain** [comment]
Yes this is the same request, so i will close this one.

You are right that i can calculate the rates by myself (also if fetched wrong), but still would be great if this could be done by the fronted and this great piece of software :)
