### ISSUE TITLE
Binance US - Not Importing Deposits and Withdrawals 

### ISSUE THREAD

**Issue by krupawan5618** [rotki/rotki#2874]
Hello,

There is an issue regarding the Binance US API that I was wondering if anyone else can replicate? I am not able to view "Deposits and Withdrawals" with this API.

"Trades" appear to be working appropriately.

Operating system: Mac OS Big Sur 11.2.1
Rotki version:1.16.2

**Comment by yabirgb** [comment]
Hello @krupawan5618 Thank your for the report! Another issue reported the same in the support channel on discord and we are investigating. I'll let you know when we get more information or we solve it

**Comment by LefterisJP** [comment]
All right so did you purge all data for binance US before refreshing deposit/withdrawals as seen here? https://rotki.readthedocs.io/en/latest/usage_guide.html#purging-data

I tried a Binance api key for deposits/withdrawals and it seems to work fine with v1.16.2.

The only way I can imagine we can proceed here is if you can provide us a read-only binanceus api key that has deposits/withdrawals to see why the api does not return this data.

**Comment by krupawan5618** [comment]
Hi,

Yes, I did purge the Binance US data, as well as create a new API key. I would be happy to provide read only keys for Binance us for further debugging.

**Comment by yabirgb** [comment]
After reviewing the issue with @krupawan5618 it appears that the reason is binance not being available in the state where (s)he  was doing the queries to the API. The list of states where binance doesn't bring support is here https://support.binance.us/hc/en-us/articles/360046786914-States-That-Binance-US-Does-Not-Currently-Support

The bad thing is that the API calls don't fail but instead returns no information for some endpoints. It would be nice to add this information to the docs since is something that might happen to other users.

The affected user in this thread solved the issue by using a VPN.

**Comment by LefterisJP** [comment]
So @yabirgb this sounds it's not a solvable issue on our side and we just need to remember that it's a possibility that binance ip restricts certain endpoints.

Unless you have any suggestion on how to handle this in a nicer way I am inclined to close as it's not on our side.
