### ISSUE TITLE
Allow users to have premium API keys without an account if paying with crypto

### ISSUE THREAD

**Issue by m-roberts** [rotki/rotki#2883]
If paying with cryptocurrency, then there's really no justification for creating an account and providing email and address information. It's just a data leak vulnerability for Rotki's valued customers.

You only need a very simple system: crypto in, key out.

**Comment by LefterisJP** [comment]
> You only need a very simple system: crypto in, key out.

I personally would have loved for this to be true

But unfortunately this is not how a company can function. We are a registered company in Germany and as per German regulations (same regulations apply in most countries) for each paying customer we need to have an invoice to show with some basic data. Otherwise we would be in trouble.

**Comment by m-roberts** [comment]
Most crypto payment gateways should handle invoicing. Is there a specific requirement in Germany that you need an email address and physical address?

**Comment by LefterisJP** [comment]
Any internet payment in Germany requires those. A crypto payment gateway that can generate invoices would also keep that or else it won't be conforming to regulations.

**Comment by LefterisJP** [comment]
By the way, this has also been asked before and we have an open issue for this in case we manage to find a way to not require an address. Our talks with an accountant/lawyer did not find a way yet: https://github.com/rotki/rotki/issues/1343 unfortunately.

**Comment by m-roberts** [comment]
Sorry for missing that ticket! Thanks for directing me :)
