### ISSUE TITLE
Errors with Binance API

### ISSUE THREAD

**Issue by jsloane** [rotki/rotki#2976]
## Problem Definition

Error loading transactions and balances from binance API. Sometimes the balance manages to load.

## Logs

`Failed to query binance balances: binance account API request failed. Could not reach binance due to binance API request https://api.binance.com/api/v1/exchangeInfo for exchangeInfo failed with HTTP status code: 418 due to a too long retry after value (179 > 60)`

`binance account API request failed. Could not reach binance due to binance API request https://api.binance.com/api/v1/exchangeInfo for exchangeInfo failed with HTTP status code: 418 due to a too long retry after value (179 > 60)`

### System Description

Operating system: Ubuntu 20.04.2 LTS, running latest docker image
Rotki version: 1.16.2

**Comment by LefterisJP** [comment]
Hello. This is due to refreshing the binance API too many times and getting rate limited. It's on the Binance side.

Perhaps you are using a share computer or a VPN and too many requests hit from the same IP. The only thing we can do is to limit history queries for binance to a user specified list of pairs, which we will do in https://github.com/rotki/rotki/issues/1073
