### ISSUE TITLE
Binance error 418

### ISSUE THREAD

**Issue by hytrex** [rotki/rotki#2990]
## Problem Definition

Getting error 418 on Binance.com (not BinanceUS)

Failed query for Binance: Error: Binance API request https://api.binance.com/api/v3/myTrades?symbol=QLCETH&fromId=0&limit=1000&recvWindow=10000&timestamp=1622098019411&signature==XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX for myTrades failed with HTTP status code: 418 due to a too long retry after value (720 > 60)

Failed query for Binance: Error: Binance API request https://api.binance.com/api/v3/myTrades?symbol=ETHBTC&fromId=0&limit=1000&recvWindow=10000&timestamp=1622098302796&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX for myTrades failed with HTTP status code: 418 due to a too long retry after value (437 > 60)

## Logs

Failed query for Binance: Error: Binance API request https://api.binance.com/api/v3/myTrades?symbol=QLCETH&fromId=0&limit=1000&recvWindow=10000&timestamp=1622098019411&signature==XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX for myTrades failed with HTTP status code: 418 due to a too long retry after value (720 > 60)

Failed query for Binance: Error: Binance API request https://api.binance.com/api/v3/myTrades?symbol=ETHBTC&fromId=0&limit=1000&recvWindow=10000&timestamp=1622098302796&signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX for myTrades failed with HTTP status code: 418 due to a too long retry after value (437 > 60)

### System Description

Operating system: Windows 10 build 20H2 b 19042.985
Rotki version: App Version: 1.17.1
Frontend Version: 1.17.1
Platform: win32 x64 10.0.19042
Electron: 12.0.7

**Comment by LefterisJP** [comment]
Hello @hytrex that error is due to getting rate limited by binance. Either you refreshed too many times, or you are in shared network or VPN where your IP queries binance from multiple locations.

There is not much we can do for this apart from telling you to make sure to limit binance interaction to not get rate limited.

The one thing we can do to improve is https://github.com/rotki/rotki/issues/1073 which is going to happen in the next release.
