### ISSUE TITLE
Remove less than symbol "<" against token units

### ISSUE THREAD

**Issue by aaronmboyd** [rotki/rotki#3032]
## Problem Definition

Very very minor gripe here. The less than symbol always catches me out every single time I open my dashboard...

I always get a shock; _What do you mean, less than?! That's my balance!_

Can we use the "approximately" ~ tilde instead? Or just remove it entirely, we all should understand the units are rounded for visual purposes.

## Logs

N/A

### System Description

Operating system: Linux
Rotki version: 1.17.1

**Comment by aaronmboyd** [comment]
I feel bad raising this, I really do.

**Comment by LefterisJP** [comment]
There has been a big discussion on the rounding methodology we use: https://github.com/rotki/rotki/issues/2479

Since then we have made it customizable for the 2 different types of numbers you see in the app. It should have been [here](https://rotki.readthedocs.io/en/latest/usage_guide.html#amount-settings) in the docs but it's not! Since we have not yet updated it. The symbol essentially shows which methodology is used.

I just made a quick video to show how it works.

https://user-images.githubusercontent.com/1658405/120383611-61fb5680-c325-11eb-8d9d-584666b5710a.mp4

If that satisfies your request please close the issue.

**Comment by aaronmboyd** [comment]
Thank you, that makes it super clear. I've altered mine to equidistant to remove the symbol, I should have trawled the options before raising the erm, "issue".
