### ISSUE TITLE
Binance US can't fetch balances `API-key format invalid`

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#3038]
Retried a few time to regenerate and re-import api key and secret, but still fails to fetch balances:

**Error:**
`Binance US account API request failed. Could not reach binance due to Binance US API request https://api.binance.us/sapi/v1/lending/union/account?recvWindow=10000&timestamp=1622602107180&signature=MY_SIGNATURE for lending/union/account failed with HTTP status code: 500, error code: -1000 and error message: An unknown error occurred while processing the request.`

`Response`
```json
{"code":-2014,"msg":"API-key format invalid."}
```

App: 1.17.1

**Comment by LefterisJP** [comment]
Hey @CruiseMan that's strange. Can you hop in discord and share a read only version of the key? We don't have any binance.us key to test with and the binance keys we have work fine.

**Comment by LefterisJP** [comment]
I am not 100% certain if it's the same error, but we detected a problem with another user's binance.us api keys and am fixing it now. I will consider it being the same error due to the fact that it queries for lending. Binance.us DOES NOT have the lending endpoints, and the if check had a bug from v1.17.0 and on.

Fixing now.

**Comment by LefterisJP** [comment]
Should be fixed by https://github.com/rotki/rotki/pull/3039
