### ISSUE TITLE
Notify frontend when premium subscription finishes 

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3095]
## Problem Definition

When the premium subscription finishes the frontend is not properly notified and fails to query some UI components. Moreover
in the Keys section is appears that the subscription is active when it has already expired

## Logs
This happened in the UI + showing the error `failing to fetch watchers`

![image](https://user-images.githubusercontent.com/5068010/122534428-cb1be300-d022-11eb-8561-752cf884ed48.png)

### System Description

Operating system: Docker Image
Rotki version: 1.17.2

**Comment by kelsos** [comment]
Maybe is time to slowly start drafting a messaging mechanism between the frontend and backend. Websockets with some polling or long polling as a fallback

**Comment by LefterisJP** [comment]
This is what the user messages is for. This should just go in there. A different mechanism would be a different issue.

**Comment by kelsos** [comment]
> This is what the user messages is for. This should just go in there. A different mechanism would be a different issue.

The user messages are for notifying the user, but this, unfortunately, is only half the solution. Even if you notify the user the frontend will still treat the user as a premium user until they re-login and the state updates. This means that the frontend state will be wrong and a lot of actions will fail until the user re-logins.

The proper solution, would include the user message to notify the user that their subscription has expired, along with another messaging mechanism to notify the frontend itself so that it can switch to the non-premium mode and avoid the errors.

**Comment by kelsos** [comment]
We have this in regards to the messaging mechanism. https://github.com/rotki/rotki/issues/2062

**Comment by LefterisJP** [comment]
> The proper solution, would include the user message to notify the user that their subscription has expired, along with another messaging mechanism to notify the frontend itself so that it can switch to the non-premium mode and avoid the errors.

Makes sense. Let's try to use that then. This would be useful for many things, not only this one. Examples are user actions to do for fixing pnl report etc.

**Comment by LefterisJP** [comment]
Pushing this to next release, but this is an easy one. Let's just do this.
