### ISSUE TITLE
Error: Could not connect to rotki server (Binance API?)

### ISSUE THREAD

**Issue by hannesroth88** [rotki/rotki#3103]
## Problem Definition
After deleting Binance and Enabling it again with new API Key.
Rotki is loading forever and saying 'Retrieving trades for Binance'

After a while i get the error:
Error: Could not connect to rotki server due to ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))

Also in the Profit and Loss Report there are no Binance Trades, when pressing "generate" and also long loading times at the Binance step.

## Logs

Cannot find any setting to setup debug.
in the log theres only entries like:
[20/06/2021 18:29:10 Mitteleuropäische Sommerzeit] CRITICAL rotkehlchen.accounting.events: No documented acquisition found for ...

### System Description

Operating system: Windows
Rotki version: 1.18.0

**Comment by LefterisJP** [comment]
Hey @hannesroth88

> Cannot find any setting to setup debug.

See how to activate debug logs from here: https://rotki.readthedocs.io/en/latest/contribute.html?#id2

> Rotki is loading forever and saying 'Retrieving trades for Binance'

That is because Binance is a terrible exchange and in order to load all trade you need to, I kid you not, query all possible markets one by one.

It will eventually finish querying, unless you get rate limited, but in v1.18 we have fixed this by allowing you to specify the markets for which binance trades are to be queried. You can do that from the exchange api keys section. For more details check the release notes of v1.18.0: https://github.com/rotki/rotki/releases/tag/v1.18.0

If the above answer your questions please close the issue.

**Comment by hannesroth88** [comment]
Thanks for that information.
Debugging is on now.
I added the hugh amount of token pairs in the Binance settings :).
Too bad Binance doesn't provide proper API.

The error was not coming again and report is going through quite fast now.
