### ISSUE TITLE
The net worth graph is overlapping with the graph when the net worth has many digits

### ISSUE THREAD

**Issue by CruiseMan** [rotki/rotki#3128]
![Screen Shot 2021-06-26 at 11 31 48 PM](https://user-images.githubusercontent.com/15807643/123535257-84d81b00-d6d7-11eb-8a8e-506aa6b9e41f.jpg)

No manual changes were made do decimal, just added big amounts.

PS. Consider adding dates to chart.

**Comment by LefterisJP** [comment]
> No manual changes were made do decimal, just added big amounts.

That does not sound correct. We have tested with big amounts (deca-hundred) millions and it works fine since the default decimal digits is 2. In your screenshot it's not 2. Go and edit it from the settings as for some reason it's no longer using the default.

https://rotki.readthedocs.io/en/latest/usage_guide.html#amount-settings

> PS. Consider adding dates to chart.

What do you mean by that?

**Comment by kelsos** [comment]
Yes, the default value for decimals is set to two, this is 8 decimal points which means that the setting has been modified at some point.

@CruiseMan do you mean instead of showing the day of the week? or when hovering in a tooltip?

In general, on this graph, the latest entry is the current day of the week.

**Comment by CruiseMan** [comment]
@kelsos Yes, i would like to see month and date like so `28.06` instead/with date of the week.
With decimals precision set to `2` looks ok, it's `8` decimal overlaps.
<img width="979" alt="Screen Shot 2021-06-28 at 11 44 59 PM" src="https://user-images.githubusercontent.com/15807643/123749963-dc5ac000-d86a-11eb-92fd-4e681974a039.png">

**Comment by LefterisJP** [comment]
So @kelsos let's make this issue for fixing the overlap (can happen with many decimals option -- or trillion numbers). Perhaps they count their net worth in some asset like yen.

@CruiseMan for the days the days of the week is limited only to 1W and 2W options. For more it presents the actual dates, and if it's even more the months of the year.

![2021-06-29_21-57](https://user-images.githubusercontent.com/1658405/123859809-67988c00-d925-11eb-9908-f36d4116387f.png)

**Comment by LefterisJP** [comment]
@kelsos can you schedule this in a milestone and rename accordingly as we will forget about it.
