### ISSUE TITLE
Add TheGraph staking support (at least keep showing original balance)

### ISSUE THREAD

**Issue by kyodhin** [rotki/rotki#3153]
When staking $GRT, the balance simply "disappears" from balances. Would be nice if rotki would still be able to "see" the original balance, even if the compounding isn't shown yet in the staking field.

Simple solution maybe: if balance is send to this staking contract address, then keep showing the same balance.

**Comment by LefterisJP** [comment]
Hello @kyodhin thanks a lot for the issue. We already have an issue for this here: https://github.com/rotki/rotki/issues/2044
so I will close this as a duplicate.

It's not as simple as it sounds since you don't stake it in a single contract but you can delegate to any number of delegators which complicates the things. But we will definitely implement this. We also are using and delegating GRT ourselves.
