### ISSUE TITLE
Usage Guide talks of Settings/Modules; but there is no "Settings/Modules" in v1.18.1

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#3164]
## Problem Definition

Usage Guide talks of Settings/Modules; but there is no "Settings/Modules" in Rotki v1.18.1

There is only `Settings/General`, `Settings/Accounting`, `Settings/Data & Security`, and `Settings/DeFi` as available options.

(doing a search of the Rotki Usage Guide on "modules" didn't help much either)

### System Description

Operating system: Win10
Rotki version: 1.18.1

**Comment by kelsos** [comment]
@A2be the problem was that this was the latest of the user guide instead of the stable. This documentation reflected the development branch changes where the `Settings/DeFi` was renamed to `Settings/Modules`. With the release of 1.19, this should not be an issue any more so I am closing this is specific issue.

@LefterisJP we should consider a checkbox in the PR template as a reminder about updating the user guide for user-facing changes. We should also probably change the app links to stable instead of the latest at some point. But that should probably happen after the current update gets merged to master.
