### ISSUE TITLE
Manual price table add on column

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3183]
## Abstract

As a follow up from #3175 

![2021-07-13_16-01](https://user-images.githubusercontent.com/1658405/125465417-c9d9eb4f-abdf-4bd5-86cf-75355247c32e.png)

The text in the table can be improved.

Instead of "is" use "was worth" (done!)

Add an "on" column between "to asset" and date.

So it can read nicely in natural language.

So "BTC was worth 2500 USD on 01/07/2021"

**Comment by kelsos** [comment]
Just for clarification, I don't think the *on* is needed, nor I have seen this approach anywhere. 
Reading nice in natural language is not something that is usually done in tables.

Also, the date itself is self-explanatory the extra column doesn't provide any missing information that is not obvious from the data, so it is superfluous. In my experience working with interfaces what I have learned is that you don't add items to the UI unless it is absolutely needed.

That being said, if I could avoid having the *was worth* entry I would do it, it should not have a place on the table. However, the problem is that unfortunately without it is not possible to make sense of what the columns represent.

**Comment by LefterisJP** [comment]
Sure I get it that this is not standard, yet it's already done on that very same table.

**Comment by kelsos** [comment]
> Sure I get it that this is not standard, yet it's already done on that very same table.

I don't know it somehow feels like the explanation above was ignored, but anyway, whatever makes you happy, I am just the frontend dev.

**Comment by LefterisJP** [comment]
It was not ignored.

And yes it's superfluous in the same way the "was worth" is. Having it will in my opinion make this more easy to read. Agree that without "was worth" this would be really hard to decipher. Without the "on" not so much indeed. But having it would not hurt especially since the table does not have too many columns to hurt us when resizing here.

All this is extremely subjective and on the eye of the beholder. If we find a way to make it better and easier to read in the future we will. If we get more professional UX advice we will utilitize it.

**Comment by kelsos** [comment]
> And yes it's superfluous in the same way the "was worth" is. 

I  am pretty sure that is not what I wrote above.

It seems that we both agree that without "was worth" the table would be really hard to understand.  So the "was worth" is not superfluous as it provides the necessary context to the users. 

> Having it will in my opinion make this more easy to read.

That is because each row in the table will read like a sentence, correct? That is the only difference I can see between the suggested approach and the current one. I still don't see it as a tremendous improvement since it is still pretty easy to infer what the date column is about contextually even with the current approach.

We have a lot of other tables that have dates columns, and we never had the need to use prepositions in columns to provide context to the users about what the date implies, but they don't read as sentences.

> All this is extremely subjective and on the eye of the beholder. If we find a way to make it better and easier to read in the future we will. If we get more professional UX advice we will utilitize it.

This conversation sure it is, it is based on our biases and experiences.

In regards to UI, while can be subjective, that is true, but when it comes to adding elements in the UI, I just ask myself, can the user understand something without adding something else? If yes, then the addition is not necessary. If not then it is.


>. But having it would not hurt especially since the table does not have too many columns to hurt us when resizing here.

In my book, that means that if it can be skipped under any condition without making things more confusing for the user then it is not necessary.

So rather than easier to read etc., it's more like you would like it to read as a sentence and that is it so let's do that.

**Comment by LefterisJP** [comment]
you seem to have a really strong opinion on this and feel the need to argue strongly over it. I simply don't have the time for this for such a small detail.

**Comment by LefterisJP** [comment]
So @kelsos as I said above this is really not needed. We can just close it. If you want to add it just schedule it somewhere.
