### ISSUE TITLE
Revamp crypto to crypto trade setting

### ISSUE THREAD

**Issue by adrienlacombe-ledger** [rotki/rotki#3194]
## Abstract

At the moment, the setting "take into account crypto to crypto trades" impacts both the consideration of the trade to compute the cost basis and the fact that such trade constitutes a taxable event.

## Motivation

In order to comply with French law (there might be others), we need to consider the crypto to crypto trades to compute the average cost position but they shouldn't be considered as taxable events.

## Specification

Split current setting into two and use the new ones appropriately in the code.

**Comment by adrienlacombe** [comment]
I figured this one out while working on #1793 trying to make Rotki friendly with French law.
I will start working on a PR for this.

**Comment by adrienlacombe** [comment]
So today behavior is:
- if yes: trades are exploded into two with fiat in between hence generating pnl
- if no: trades are removed altogether from the set of trades considered to compute pnl

I don't see how option 2 can currently be useful to anyone as by removing the trades altogether, the cost of acquisition becomes wrong but in order to be fully backward compatible, this scenario still needs to be achievable with the new settings.

I therefore suggest 2 new settings to replace the old one:
1. Crypto to crypto are taxable events
- if yes, crypto to crypto trades are taken into account and exploded just like with current setting set to yes
- if no, crypto to crypto trades are still used to compute position cost but no pnl is created / no taxable event
2. Exclude crypto to crypto trades
- if yes, crypto to crypto trades are ignored, just like with current setting set to no
- if no, crypto to crypto trades are still used to compute position cost but no pnl is created / no taxable event

If 1 is set to yes, 2 can only be no.
If 2 is to yes, 1 doesn't matter.

**Comment by adrienlacombe** [comment]
I keep thinkin in boolean terms but now I think we need one setting with 3 values:
1. Crypto to crypto trades are exploded and considered as taxable events
2. Crypto to crypto trades only participate in position building and are not considered as taxable events
3. Crypto to crypto trades are excluded

**Comment by LefterisJP** [comment]
Hey Adrien, thanks a lot for the issue.

Ignoring crypto to crypto trades completely is good for the jurisdiction (back when this setting was written even the US ignored crypto to crypto) where you are only taxed when you go out to fiat.

So all others you don't care much about. You are right that you don't get much information about the profitability of your trades then but that comes with the option.

So let me see if I understand your suggestion correctly.

1. Crypto to crypto trades are exploded and considered as taxable events ->This is what we have now.
2. Crypto to crypto trades only participate in position building and are not considered as taxable events -> So here they would count for cost basis but not for the trades profit/loss
3. Crypto to crypto trades are excluded -> The behavior we have now for disabling crypto to crypto

**Comment by adrienlacombe** [comment]
Yeah but you would still want the trades to build your position I am pretty sure :)

Correct understanding ! I will start working on this. Might ask for some help on Discord ;)

**Comment by adrienlacombe** [comment]
@LefterisJP do you think it makes sense that I implement the 2nd option for FIFO? Thank you for your guidance!

**Comment by LefterisJP** [comment]
I think that with the new decoders/accountants if you disable crypto to crypto trades the cost/basis PnL is already being handled correctly so we can probably close this.
