### ISSUE TITLE
Support Optimism balance queries and transaction history

### ISSUE THREAD

**Issue by A2be** [rotki/rotki#3231]
## Abstract

Get Ethereum Layer 2 (L2) trades on Optimism into trade history

## Motivation

As Optimism/Uniswap continue their beta on L2, already supporting as many trades as Uniswap v3 on L1, there will be a lot of Rotki user's accounting data missing until Rotki supports Optimism L2 trades.

**Comment by A2be** [comment]
Recognizing this will not be a near-term Team Rotki priority, I queried the Hermez team on whether they might like to help integrate Hermez trades into Rotki.  
Link to their [Discord where the question was lodged](https://discord.com/channels/774279160192303104/774279647474090016/866633583795634186):

**Comment by SCBuergel** [comment]
Optimism is quite a huge mess right now that Rotki could uniquely resolve and maybe even position itself better than even Etherscan: After their Nov 11 relaunch (most) past transactions are gone. So I'm literally blind on where I aped around and while they keep saying "funds are likely safe" this doesn't help me at all because I have no idea where I locked my tokens without seeing past txs. So having Arbitrum txs, including those before Nov 11 would be amazing!

**Comment by LefterisJP** [comment]
This is coming in v1.27.0 -- soon
