### ISSUE TITLE
Uncheck selected trades

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3287]
## Problem Definition

When you click on the button to select all the trades  you can't unselect them all at once by clicking the same button (not other that I've seen)

![image](https://user-images.githubusercontent.com/5068010/128060501-2770aa90-2358-495f-b4e5-5daeae235301.png)

Operating system: Docker
Rotki version: 1.19.1

**Comment by LefterisJP** [comment]
So this is for @kelsos to look at I guess

**Comment by kelsos** [comment]
What was the state of the application when that happened. If I remember correctly, the way I implemented the select functionality, it only selects items based on the visible dataset. If you select all while it is loading for example and then more entries appear then the checkbox would be unchecked because the newly added items are not selected.

The same would happen if you select a location filter and then remove the filter.

**Comment by yabirgb** [comment]
@kelsos There was nothing selected, everything loaded already and no filter was applied

**Comment by LefterisJP** [comment]
So I managed to reproduce it and then with the help of @kelsos figured out the problem is actually the backend generating the same identifier for two different trades.

This, at least in my case, happened for different swaps from different AMMs but in the same transaction. So using an aggregator like paraswap or 1inch and having same transaction hash for a balancer swap and a uniswap swap.

I can easily fix by using the log index in the trade id too. But we probably need a nice way to log this in the frontend in case this happens again, so we know what is the root cause and fix it.
