### ISSUE TITLE
Refactor manual balances identifiers

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3370]
## Abstract

Currently we use the label of manually tracked balances as identifiers. This makes this field non mutable. 

## Motivation

It makes sense that, if we display the label as data for the balance a user, this field could be modified

## Specification

A new id random id should be generated and work as identifier, leaving the label field free to be modified.

**Comment by kelsos** [comment]
@nebolax I am re-opening since there are a couple more things we need to do.

## Backend

1. The API should return the id in the response (/api/1/balances/manual) (any verb in this endpoint that returns a list of balances
2. Patch should accept the id as the identifier
3. Update the docs with the changes

## Frontend 

1. Remove disabled on edit from ManualBalanceForm
2. Introduce the id in the schema
