### ISSUE TITLE
Help upvote binance api feature to get all trades history via single route

### ISSUE THREAD

**Issue by daffoxdev** [rotki/rotki#3412]
Hi everyone,

Guys, I know that there are not possible to request all trades history via single route from binance api. There need to request  all the existent pairs on binance first, then start to loop for each of them to collect whole picture of trades account did. 

We have large amount of users here, why not to go to binance devs web site and not to vote for this feature? There are only about 80 votes for this very critical feature for accounting. 

Binance is most popular exchange, but communication via api is most weird by them. So I would believe that via this vote we could give them knowledge that there are a lot of devs that waits for this feature. This feature allows to sync data waaay quicker than it happens currently and even binance servers will have less work after this. So this feature is win-win from both sides.

**Link to topic for vote:** https://dev.binance.vision/t/fetch-all-account-orders/279

P.S. Is only one of many similar requests in their forum that I have found with most votes. If you know with more votes, post it here please.

P.S.S. I know this is not directly related to rotki developent, but thiis feature invention could help rotki working more quicker and our community, I guess, is interested in this.

Thanks

**Comment by LefterisJP** [comment]
Thanks for the issue @daffoxdev I will keep it open for a bit so peopel see it and also post about it in our discord community: https://discord.com/invite/aGCxHG7

Then since it's not actionable on our side I will close it.

But I completely feel you on this. I tried to contact people from Binance many times about this and every time the response was the same. That they would not change this any time soon. Will also +1 the topic you posted ofc. Thank you.

**Comment by LefterisJP** [comment]
Closing this since there is nothing more actionable on our side.
