### ISSUE TITLE
Support for coinbase earn through the coinbase exchange api integration

### ISSUE THREAD

**Issue by arosboro** [rotki/rotki#3474]
## Abstract

Coinbase earn education program rewards are not showing after connecting a coinbase account.  This request seeks to sync those events in rotki.

## Motivation

Missing coinbase earn transactions result in unresolved acquisitions if those assets are liquidated.

## Specification

Refer to https://developers.coinbase.com/api/v2#transaction-resource and https://github.com/rotki/rotki/blob/develop/rotkehlchen/exchanges/coinbase.py#L525

Identify the transaction type used for a coinbase earn promotional transactions so they can be identified and recorded as a deposit

**Comment by arosboro** [comment]
I see a few possible ways this could be best completed, so I figure some ideation and discussion is needed before impacting the architecture for the exchange class.

In work with uphold and coinbase, I have identified deposits and withdrawals which can be considered income or expenses by their nature.  Some may consider this a judgement call that each user needs to make based on their jurisdiction.

Here are the cases I have discovered so far

* Deposits from other users as income
 * Brave International BAT rewards
 * Coinbase Earn Promotions
 * Coinbase Inflation Rewards (occur daily)
* Transfers to other users as Expenses
 * Brave BAT donations

Coinbase exchange implementation also incorrectly denotes network transfers coming in as withdrawals instead of deposits.  Ideally these would be verified against the rotki account to distinguish deposit vs income if it is an own address/account or outside address/account.

Currently I addressed these by generating ledger actions.

There are callbacks to query exchanges for trades and movements, but not ledger actions.

Two paths forward here:

1. Treat everything which could potentially be income or expense as an asset movement but provide a way to select and convert these imported records to ledger actions after manual review by the user.

2. Write a hook in exchange.py similar to query_online_deposits_withdrawals named query_online_ledger_actions that gets called on the Ledger Action page and on the P&L report this generates ledger actions which can be manually edited.

The current PR is undesirable because the ledger actions it creates only appear in the system after running the P&L.  The asset movements generate as before with a change to catch those missed deposits.

Feedback for this and suggestions/guidance would be appreciated so I can take the preferred approach when I revisit the PR.

**Comment by yabirgb** [comment]
Thank you for this write! Since this is an important change in the design I believe @LefterisJP should have the last word here.

In my opinion and after reading your explanation @arosboro  I believe that the second option provides more versatility and is more flexible. This option seems to be more user friendly also. Finally this second option needs less changes in the backend and will be easier to implement.

As for what the default values is what I guess should be selected carefully. And a way to let the user know that this ledger actions might need a review is also important

**Comment by arosboro** [comment]
One con to approach 1 is that the exchange will regularly sync events which need periodic manual action sometimes on a daily basis.  I considered an additional feature: categorization rules that automate conversion based on records to match incoming asset movements and reclassify them.  Again as you mentioned @yabirgb that will increase the scope of work dramatically, and I agree with you that introducing online ledger actions is less drastic of the two approaches.

**Comment by LefterisJP** [comment]
The only thing I can imagine as viable is (2). If we do know that some exchanges have something that should be a ledger action then we should turn it into one and not try something that does not fit the purpose.

Perhaps a way of letting the user know that they should periodically check their ledger actions to make sure it's generated correctly should be also implemented.

A problem I can see is the following:

Exchange data for say trades or asset movements is queried since start of time until now. Then the queried range is saved. And next time we only query the time range that was remaining. Exchanges data can be removed though. If you purge all kraken data, all trades and asset movements from kraken will be removed.

Should the same now be done for ledger actions too? There is a `Location` field in ledger actions. So in theory we could do that. But the problem is this would also encompass any custom made ledger action created by a user with location of the exchange. Say kraken for example.

But to be honest after writing that out, I can't really see when a user would do that. So perhaps not really a problem in the real world.
