### ISSUE TITLE
Consider integration with beancount (plaintextaccounting!)

### ISSUE THREAD

**Issue by ebuchman** [rotki/rotki#348]
## Problem Definition

First, this is an awesome project and kudos for building it :)

There is a growing movement around [plaintextaccounting](https://plaintextaccounting.org/), which refers to a plaintext human+machine readable format for keeping double-entry books, and the suite of open-source tools and scripts supporting it. I'm particularly fond of [benacount](http://furius.ca/beancount/), as I've had some success managing both personal and corporate crypto accounting in Canada the last 2 years. Beancount is written in Python, it has strong support for handling commodities/inventory/prices, and there's a high quality UI available in the form of [fava](https://github.com/beancount/fava). 

I wonder if there's some opportunity for integration between rotkehlchen and beancount? In particular I would love to see rotkehlchen adopt beancount's data format, as it would enable interoperability with existing beancount tools, like the fava UI and the `bean-query` tool for making SQL queries against transactions and accounts. It might also prompt other tools to adopt beancount as a common standard, which could be a huge win for portability and even correctness of the world's mess of accounting data.

Is this something you've thought about, or a direction you might be interested in going in?

**Comment by LefterisJP** [comment]
Hello Ethan,

> I wonder if there's some opportunity for integration between rotkehlchen and beancount? In particular I would love to see rotkehlchen adopt beancount's data format, as it would enable interoperability with existing beancount tools, like the fava UI and the bean-query tool for making SQL queries against transactions and accounts.

I have not considered this yet no.

My goal is for rotkehlchen to become an all-encompassing accounting, taxes and investments tools for others but first and foremost for me as I am probably the most hard-core user of the software. Once I add also normal expenses accounting (groceries e.t.c.) perhaps it would make sense to look into that format you mention. At the moment I am using a shitty android app for this and I wanted to switch that tracking to Rotkehlchen too.

So far the data format is an encrypted sqlite DB so that multiple users can exist in the same machine and for extra security of the financial data.

I will take a look at the links you left here. Also if you have any specific ideas on integration or any specific things you would like to see please say so or even better open PRs :smile:

**Comment by t-900-a** [comment]
Is there a data model diagram somewhere?
I don't see a models.py, so I'm not even sure where to start on understanding the database and how things are stored.

**Comment by LefterisJP** [comment]
@t-900-a what does that have to do with this issue? For general dev questions please join our discord channel: https://discord.gg/aGCxHG7

At the moment the DB's tables are defined here: https://github.com/rotki/rotki/blob/65eb8cb8d91a42817640e8bd88da758f7ff2d5c8/rotkehlchen/db/utils.py and the database handler is here: https://github.com/rotki/rotki/blob/65eb8cb8d91a42817640e8bd88da758f7ff2d5c8/rotkehlchen/db/dbhandler.py

**Comment by LefterisJP** [comment]
I am going to close this since it's not actionable for rotki at this point in time. If at some point we get something actionable to do for  integration, it should be specified properly with a spec and TODO items in a new issue in the future (or even reopen this one).
