### ISSUE TITLE
Take into account true fee used in kraken trades (such as KFEE or non quote asset)

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#3500]
## Abstract

At the moment is possible to have trade fees paid in KFEE but in the API it appears as paid with the quote asset. 

## Specification

To solve this issue we should compare every trade agains the ledger entries from kraken and check if KFEE was used

**Comment by yabirgb** [comment]
In addition to detect the ussage of KFEE it will be also be useful to detect the correct assets used in fees since the user can choose by querying the related ledger actions and obtaining the fee from there

**Comment by LefterisJP** [comment]
@yabirgb The user can not always choose. A lot of things happen automatically. The trade endpoint may return "quote currency equivalent" but "anything" can be the actual fee as I mentioned.

It can use KFEE if you have. It may also use base currency instead of quote currency. And who knows .. maybe something else too?

The only way to be 100% sure and correct about what was taken is to use the ledger endpoint: https://docs.kraken.com/rest/#operation/getLedgers

This is essentially all entries in the user's account and why. So this much BTC came in from deposit, this much as fee in this trade, this much sold in this trade, this much EUR came in etc.

By matching the trades to the ledger entries we can cross-check and get the correct fees.
