### ISSUE TITLE
Duplicate asset in my balances. 

### ISSUE THREAD

**Issue by pinoli** [rotki/rotki#3548]
## Problem Definition

rotki incorrectly shows an asset tied to an old contract that's been updated.
![image](https://user-images.githubusercontent.com/30185650/135701867-b42f8f8c-ac3c-48ac-b82b-d069d390a5ae.png)
In the screenshot you can see SingularityNet (AGI) listed twice:

- The first entry is the old contract (AGI), a balance I don't own anymore.
- The second entry is the correct one (AGIX, new contract and updated balance)

rotki should only show the balance for the updated contract and ignore the balance tied to the old contract

If there is a way to manually fix it, please let me know (I use automatic scanning of my ETH addresses)

### System Description

Operating system: Windows 10 21H1 19043.1237
Rotki version: 1.21.0

**Comment by LefterisJP** [comment]
This is not incorrect :)

The devs of this token did an upgrade by mirroring balances instead of swapping as should be done. You have both the new and the old token and they are both properly detected and shown as would be expected.

The contract exists and we detect the balance for it.

Yes there is an easy way to fix it manually. Go to the Settings -> Accounting and ignore the old one. It should be the one "Singularity Net".

![2021-10-02_09-38](https://user-images.githubusercontent.com/1658405/135708051-b0a3714f-8b37-47bd-9123-92f1cfb45267.png)

We should probably add rules for all these in the application itself though so this does not happen. Just hard to know in advance which tokens did this.

**Comment by LefterisJP** [comment]
Do tell us if this solved your issue. It should as I also tested it, but if you still have problem write here and we can help you.

**Comment by pinoli** [comment]
I'll write here just to thank you to close all of my three issues in less than a day. Fantastic.
I am a Premium User and I have to say rotki is a game changer, and I love the passion I see here.

Thanks again and yes, this fixes my issue. I understand it's on Singularity side and ignoring it works flawlessly.
