### ISSUE TITLE
Add total value of NFTs owned in the NFT dashboard table

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3555]
## Abstract

Much like the assets that have their total shown in the dashboard assets table the NFTs should also show the total value of all NFTs owned in their table in the dashboard

## Task

Do it

**Comment by rkalis** [comment]
I'm not sure if this is included in this issue, or if I should open a separate one, but I'd like to see e.g. my Cool Cats grouped as "Cool Cats" in the statistics view, rather than showing them separately (and without name) like it is now.

<img width="804" alt="Screen Shot 2021-10-04 at 11 43 18" src="https://user-images.githubusercontent.com/9142187/135829752-9e898a44-640f-4690-a2aa-c261622b9a49.png">

**Comment by kelsos** [comment]
> I'm not sure if this is included in this issue, or if I should open a separate one, but I'd like to see e.g. my Cool Cats grouped as "Cool Cats" in the statistics view, rather than showing them separately (and without name) like it is now.
> 
> <img alt="Screen Shot 2021-10-04 at 11 43 18" width="804" src="https://user-images.githubusercontent.com/9142187/135829752-9e898a44-640f-4690-a2aa-c261622b9a49.png">

Hey @rkalis  can you open a new issue for that. It is a separate issue and a bit more complicated one.

**Comment by rkalis** [comment]
Will do!

**Comment by LefterisJP** [comment]
This is done by #3558
