### ISSUE TITLE
API Binance History Trades Problem - failed with HTTP status code: 418 due to a too long retry after value (960 > 60)

### ISSUE THREAD

**Issue by vasiliyx** [rotki/rotki#3687]
## Problem Definition

Not able to retrieve History of Trades for Binance and not able to get a Profit and Loss report.

Failed query for Binance: Error: binance API request https://api.binance.com/api/v3/myTrades?symbol=BTSETH&fromId=0&limit=1000&recvWindow=10000&timestamp=1636........................................  for myTrades failed with HTTP status code: 418 due to a too long retry after value (960 > 60)

## Logs
Can attach In private message

### System Description
Operating system: OSX 10.15.7
Rotki version: 1.21.3

**Comment by LefterisJP** [comment]
Hello @vasiliyx this is because you are getting rate limited by binance. Binance is the worst api in existence and does not allow a way to query all your trades. The api can only iterate through all existing markets which are A LOT. And this ends up in rate limiting.

The only way to make binance work is to explicitly specify the markets you used: https://rotki.readthedocs.io/en/latest/usage_guide.html#binance-binance-us

**Comment by vasiliyx** [comment]
Thanks for a prompt response! I did experience difficulties retrieving anything informative even through the Binance website...

**Comment by LefterisJP** [comment]
My pleasure! We also have a discord server where you may also get more interactive help: https://discord.com/invite/aGCxHG7

Note: It has a captcha
