### ISSUE TITLE
Importing Cointracking.info CSV file

### ISSUE THREAD

**Issue by twooten1105** [rotki/rotki#3712]
## Problem Definition

I am having trouble importing cointracking's CSV file into rotki.

Every entry gives me this error: "Backend - Error during cointracking CSV import deserialization. Error was Failed to deserialize a timestamp from a null entry in cointracking.info. Ignoring entry."

Maybe cointracking has changed up the CSV fields and the timestamp field has been moved to a different spot?

I will attach part of the CSV file that was outputted from Cointracking

Thanks

[CoinTracking_Trade_Table.csv](https://github.com/rotki/rotki/files/7532602/CoinTracking_Trade_Table.csv)

![import error](https://user-images.githubusercontent.com/94203784/141656434-c14b7810-8c1d-4491-9dca-8eb90139a34d.PNG)

**Comment by yabirgb** [comment]
Hello @twooten1105 The file that you provided is different from what rotki expects. The expected input should be as follow https://github.com/rotki/rotki/blob/develop/rotkehlchen/tests/data/nexo.csv I'm really not sure if nexo changed format or is the incorrect CSV. I'll ask other users in discord to check what it could be

**Comment by yabirgb** [comment]
Hello @twooten1105 ! Your CSV was failing to be read because the format for the dates is one that we don't expect. We will ship in 1.23 an option to customize this format for all CSV imports and should make your file work

**Comment by twooten1105** [comment]
Hi Yabir

I just saw your reply. Thanks

I was wondering if there has been a fix for this issue?

Thanks
Tom

**Comment by yabirgb** [comment]
Hello @twooten1105! It won't be a direct fix but a new feature to allow custom date format inputs in CSVs. Will be shipped in the next version 1.23 that should come as soon as we finish some other pending tasks

**Comment by yabirgb** [comment]
So to close this issue we need to implement the functionality in the frontend. What needs to be done is to add a date input format form for each CSV import section and send this format in the request alongside the file as described here https://rotki.readthedocs.io/en/latest/api.html#put--api-(version)-import

Also we discussed with kelsos before that it might be a good idea, since the import components are modular, to create a dropdown to select the location and then render the form. The date format field should be added to every import.
