### ISSUE TITLE
Re-add arm64 Docker image

### ISSUE THREAD

**Issue by m-roberts** [rotki/rotki#3780]
As per [v1.22.1](https://github.com/rotki/rotki/releases/tag/v1.22.1)'s description:
> important note: No arm64 docker image exists for this release due to problem with our arm64 building pipeline. We will let you guys know when arm64 building is back and working.

I am just creating this ticket as I could not see it being tracked in an issue anywhere.

**Comment by yabirgb** [comment]
Hello @m-roberts! The builds for arm64 should come in the next release 1.23.0 if everything goes as expected. We had an issue with dependencies that got solved recently. Yesterday I managed to get the docker build working but not in time for the patch release 1.22.2 since we wanted to make sure that everything was working as expected.

If you need any of the functionalities of the patch release you can build it from this tag https://github.com/rotki/rotki/tree/v1.22.2 Sorry for the inconvenience.
