### ISSUE TITLE
ccxt support to connect to exchanges

### ISSUE THREAD

**Issue by criadoperez** [rotki/rotki#3834]
## Abstract
Rotki can currently only supports 17 exchanges. Adding and maintaining exchanges is a lot of work.
So why doesn't Rotki use the popular free software library [ccxt](https://github.com/ccxt/ccxt) to get balances from over 100 exchanges directly?

## Motivation

17 exchanges is not enough. ccxt will guarantee support for virtually all exchanges and reduce coding effort. 

## Specification

You can get a balance for an exchange with one command line with ccxt, using javascript, python or php.

**Comment by LefterisJP** [comment]
Thank you for your suggestion. We know ccxt and the decision was made early on to not use it.

Because the same problems of implementation and transformations of data to our own format would exist for each single one of those exchanges.  This has been discussed in other issues already and it's not something we want to do.
