### ISSUE TITLE
Independent Reserve issue with 1.23.0

### ISSUE THREAD

**Issue by drgonzo31** [rotki/rotki#3923]
## Problem Definition

I receive this notification on loading the Rotki  version 1.23.0
```
Could not save the balance snapshot at IndepentReserve 1. IndependentReserve request failed. Could not reach the exchange due to IndependentReserve api request for https://api.independentreserve.com/Private/GetAccounts failed with HTTP status code 401 and response {"Message":"Invalid credentials (bad nonce). This nonce=xxx, last valid nonce=yyy}
```
### System Description

Operating system: Linux
Rotki version: 1.23.0

**Comment by LefterisJP** [comment]
Hey @drgonzo31 not sure what this can be.

Try resetting the api key and also making sure your system clock is properly synced. This is what we have seen this error in other exchanges be related to.

Nothing was touched for this exchange in 1.23.0 so can't be related to our code changes.

If it persists perhaps you can join discord and share a test key for us to test with.

**Comment by yabirgb** [comment]
Hello @drgonzo31 ! With other exchanges a similar error happens when the clock is not synced (is the case of independent reserve also where the current time is sent in the request). Can you check installing `ntpdate` and running something similar to `sudo ntpdate 0.us.pool.ntp.org` to sync it? Also for support as lefteris said we use discord

**Comment by LefterisJP** [comment]
Closing this due to lack of information.
