### ISSUE TITLE
Add support for blockfi

### ISSUE THREAD

**Issue by sakgoyal** [rotki/rotki#3951]
can you add support for reading csv files for transaction so I can import my transactions from blockfi?

**Comment by yabirgb** [comment]
Hello @TheVaccin3 ! We already support blockfi int the `import data` section. Did you have any issue with blockfi?

**Comment by LefterisJP** [comment]
Blockfi is already supported via CSV import. If you have your CSV you can always import it. They don't offer any other API and since they [filed for bankruptcy under "Chapter 11"](https://blockfi.com/November28-ClientUpdate) last November they will soon cease to exist so no more integrations will be built.

Closing the issue, since the company went bankrupt.
