### ISSUE TITLE
Edit and delete manual balances are missing

### ISSUE THREAD

**Issue by adrianfako** [rotki/rotki#4020]
## Problem Definition

Cannot edit / delete balances in Accounts & Balances, the Manual Balances. The 2 buttons are missing.

### System Description

Operating system: Ubuntu 20.04
Rotki version: 1.23.2, AppImage

**Comment by LefterisJP** [comment]
Hey @adrianfako this sounds weird. They are there for me.
![2022-01-29_12-49](https://user-images.githubusercontent.com/1658405/151659867-a886110a-c474-4af2-a8d8-4810465f76e9.png)

For easier chat and to be able to figure out more easily what your problem is you can join our discord: https://discord.com/invite/aGCxHG7
(there is a captcha challenge)
