### ISSUE TITLE
Import Annotations or public tags from Etherscan for known walletadresses

### ISSUE THREAD

**Issue by eis2k** [rotki/rotki#4065]
## Abstract

i've imported a list of multiple Ethereum addresses. I accidently imported an exchange account and my rotki went nuts. 

## Motivation

I've a check before importing regarding the public tag would be made, this would prevent from importing garbage into rotki and it would also if you accicently imported an exchange account, showing the public tags as tags in rotki would be great to identify faulty imported wallets.

## Specification

imho it just an additional request if annotation =null then if not the warn before importing, If you want to import an exchange account or a liquidity pool or so then i should be possible if the user confirms it.

**Comment by LefterisJP** [comment]
This is unfortunately not possible since etherscan does not allow to export these names. 

We do want to create a registry of names enriched with all public data and also editable by users. I can't find an issue for it right now though. Will probably create one and close this or if I have you permission I can edit your issue to reflect this.

It has been discussed in Twitter: https://twitter.com/LefterisJP/status/1480474998775156737

WE d

**Comment by eis2k** [comment]
i dont get your answer.. 

https://etherscan.io/accounts/

Here you can see their public annotations. What should be the problem?

**Comment by LefterisJP** [comment]
> i dont get your answer..
> 
> https://etherscan.io/accounts/
> 
> Here you can see their public annotations. What should be the problem?

This is not offered via an API. What you see there is simply their website. We can't get it from there. Or .. well we could if I write a scraper, but scraping is not allowed by etherscan's ToS.

**Comment by LefterisJP** [comment]
Closing this issue as it's not feasible due to Etherscan's ToS. But we now have a hard-coded mapping of addresses to names and will open that up to the user for editing with https://github.com/rotki/rotki/issues/1420
