### ISSUE TITLE
Import Yearn vault prices through vault contract call

### ISSUE THREAD

**Issue by toro09** [rotki/rotki#4107]
## Abstract

Get Yearn vault prices by calling the pricePerShare function to read the value directly from the vault contract. 

## Motivation

Many Yearn vault assets don't have a price listed on CoinGecko and CryptoCompare. This results in an error when trying to update portfolio balances that have Yearn assets. Therefore, users don't have an accurate account of their balances. yVaults have a built in function called pricePerShare that allows for users to directly read the value of the token from the contract. 

## Specification

Get the value of yVault tokens by calling the pricePerShare function.. This function returns an 18 decimal value and needs to be converted to the user's desired currency preference.  Be careful to understand what the base token is in the price (i.e. USD, vs ETH, vs WBTC, etc.)

**Comment by yabirgb** [comment]
Hello @toro09! Yes, that logic is the one we use at the moment. You can see it here https://github.com/rotki/rotki/blob/develop/rotkehlchen/inquirer.py#L624

Calculating prices for wrappers like yearn is more complicated since you also have to calculate prices for underlying tokens if it's needed. In the case of the curve lp tokens we also have a special logic and it becomes a chain of queries that can fail at some point.

In the weekend (I believe it was you) who reported a set of yearn vaults not working properly regarding the price fetching functionality and that is an issue that I'm working on. The reason is the calculation of the price for the underlying curve assets.

Also the problem of the yearn vaults is that calculating historical prices is impossible if you don't know the state of the chain at the moment you want and this adds addition constraints

**Comment by toro09** [comment]
Copy all, thanks for the quick and detailed reply!
