### ISSUE TITLE
decoder failing on compound cETH token

### ISSUE THREAD

**Issue by joshuavial** [rotki/rotki#4149]
## Problem Definition

On the History > Ethereum Transactions page when the decoder encounters a transaction using cETH it fails to decode and stops decoding all transactions underneath it 

example transaction
https://etherscan.io/tx/0x508af91a5bd2903c13e999c299ab2bcfd931986f287d0b6bfcebf49fc221db20

from a random cETH user I found on etherscan
0xD610086899bBE55f08F4590B2197aeD9966e8C73

It will then throw an error when it periodically tries to decode
"Periodically decode evm trasactions died with exception: 'NoneType' object has no attribute 'decimals'. Check the logs for more details"

## Logs
The periodic decoding error shows

```
Periodically decode evm trasactions died with exception: 'NoneType' object has no attribute 'decimals'.
Exception Name: <class 'AttributeError'>
Exception Info: 'NoneType' object has no attribute 'decimals'

  File ".../rotki/rotkehlchen/chain/ethereum/decoding/compound/decoder.py", line 129, in decode_compound_token_movement
    return self._decode_redeem(tx_log=tx_log, decoded_events=decoded_events, compound_token=compound_token)  # noqa: E501
  File ".../rotki/rotkehlchen/chain/ethereum/decoding/compound/decoder.py", line 99, in _decode_redeem
    redeem_amount = token_normalized_value(redeem_amount_raw, underlying_token)
  File "...rotki/rotki/rotkehlchen/chain/ethereum/utils.py", line 71, in token_normalized_value
    return token_normalized_value_decimals(token_amount, token.decimals)
```

### System Description

Operating system: macOS 11.6.1
Rotki version: develop branch (commit deb2d26ab2436f3d9288c91c29071e5c798a601e) 1.20.2.DEV

**Comment by yabirgb** [comment]
Hello @joshuavial ! Thanks for reporting us this issue, will take a look asap. Remember that the develop branch is experimental and you will have issues if we add more changes to the database upgrade. Always take backups or use a secondary account.

**Comment by LefterisJP** [comment]
Hey @joshuavial thanks for reporting something with the decoders. Keep in mind the develop branch is under constant development and it's not a stable thing to test with. That branch can be broken at time. In fact as a user you should never ever try develop branch as it will mess up with your database.

Make sure to always keep a backup of the database if you play around with the develop branch.

Make sure to join our discord https://discord.com/invite/aGCxHG7 (has a captcha, so have DMs open) to report stuff in #dev-support channel if you are developing in rotki! We love it when people do that.

I will close the issue since it's not about production but we will test the scenario you mentioned when we strive to make develop stable to create v1.24.0
