### ISSUE TITLE
Map fiat deposits to stablecoins on FTX

### ISSUE THREAD

**Issue by dtsbsb** [rotki/rotki#4197]
## Specification

All fiat currency deposits made at the FTX exchange in USD are grouped into the stablecoin like USD, along with other stablecoins except USDT, which stays separate.
The same happens with the fiat currency BRL, which is automatically transformed into BRZ, without, however, there being an accounting record of this act. 
Thus, the balance of these currencies is wrong and can only be adjusted manually.
What can you do to correct this?
Translated with www.DeepL.com/Translator (free version)

**Comment by LefterisJP** [comment]
Hello @dtsbsb I am not sure I understand the issue.

Is there something wrong with the mapping of the detected assets in FTX? If yes what asset is not detected properly?

**Comment by dtsbsb** [comment]
Hello, @LefterisJP. Thanks for the response. 
No, the mapping is initially correct, but FTX runs a second, automatic, hidden transaction, as if it were a swap, that FTX itself does not account anywhere.
Example:
04/14/2022 14:30:25H - DEPOSIT BRL 1,500.00 (fiat deposit correctly accounted in FTX and in Rotki):
04/14/2022 14:30:25H - HIDDEN SWAP BRL -> BRZ 1,500.00 (1 BRL -> 1 BRZ).

**Comment by dtsbsb** [comment]
Another example:
Sell off ETH with BRZ (with positive balance in FTX):
09/04/2022 12:55:24	[ETH/BRZ](https://ftx.com/trade/ETH/BRZ)	Buy	Limit	0,10000000	15.200,00000000	1.520,00000000 BRZ	0,000000 ETH

The error message in the Rotki after this transaction type is:

_No documented acquisition found for BRZ(0x420412E765BFa6d85aaaC94b4f7b708C89be2e2B) before 30/12/2021 09:45:50. Let rotki know how you acquired it via a ledger action_

**Comment by LefterisJP** [comment]
I see. FTX doing things under the hood without reporting it via the API makes it very hard to provide a proper fix for this.

This is a problem with FTX itself and they should fix it and do proper reporting of all events via the API.

In the meantime if we wanted to do anything we would need to have:

1. List of all events and assets combination in FTX that generate these extra conversions underneath.

Is it only fiat deposits? For which assets? We need to be sure otherwise any change we make may be incomplete and mess up accounting for other FTX users.

**Comment by LefterisJP** [comment]
With FTX dead this issue is unfortunately no longer relevant.
