### ISSUE TITLE
Uninstall/Update doesn't work on Windows

### ISSUE THREAD

**Issue by daferna** [rotki/rotki#4831]
## Problem Definition

I can't uninstall or upgrade Rotki because the installer appears to think Rotki is still running despite this not being the case. Perhaps the installer is detecting itself as an instance of Rotki? This happens regardless of running the uninstaller or the new v1.25.3 installer.

## Logs

![image](https://user-images.githubusercontent.com/711733/189585400-e52539fc-a495-4a8b-927c-e13b3c05c0c9.png)

![image](https://user-images.githubusercontent.com/711733/189585474-2958351e-462e-43ce-a6f2-196e7c362554.png)

### System Description

Operating system:  Windows 11
Rotki version: 1.24.1

**Comment by LefterisJP** [comment]
Hey @daferna can you check if you have some remaining process via the task manager?

**Comment by daferna** [comment]
I did check the task manager, I have also tried rebooting and running the upgrade installer (without starting the already-installed app) and that doesn't work either.

**Comment by LefterisJP** [comment]
This is really weird. Nobody has ever reported this before. 

Which previous versions of rokit had you used? In the issue you are writing 1.24.1, but latest is 1.25.3. 1.24.1 is from 3rd of June.

**Comment by kelsos** [comment]
I can try the upgrade path as soon as I find some time and see if something happens.

**Comment by kelsos** [comment]
Hey, @daferna I just managed to find some time to look into it but unfortunately, I was unable to replicate it. 

I tried both on Windows 10 and 11 and upgrading from 1.24.1 to 1.25.3 happened without any issue. I also didn't have any issues uninstalling the application.

If you restarted the system and it still happens my best guess is that the problem is not any of the rotki processes still running (which can happen sometimes) but some system process or third-party software blocking access to the file.

What I would do is try to figure out which process is locking the file in Windows. I am not sure how this could be done but a google search would provide you with more information.
