### ISSUE TITLE
Add different tax calculation method HIFO

### ISSUE THREAD

**Issue by wolfspy** [rotki/rotki#5001]
## Abstract

My friends and I definitely need the HIFO tax calculation option for our situations.

## Motivation

We can’t be the only few who need HIFO in order to minimize capital gains taxes, and this would benefit anyone else that needs it as well.

We also won’t buy the product until that feature is there, so we’re forced to use a different subpar product that does offer the HIFO calculation.

**Comment by LefterisJP** [comment]
Thank you for the issue @wolfspy 

> We can’t be the only few who need HIFO in order to minimize capital gains taxes, and this would benefit anyone else that needs it as well.

You are actually the first to ask for it since https://github.com/rotki/rotki/issues/566 which just requested separation of lifo from fifo.

We will see what we can do. Should not be too hard.

For the dev who picks this up, this is a quick explanation of HIFO: https://www.investopedia.com/terms/h/hifo.asp

Is this what you would need? @wolfspy 
I wish Germany recognized HiFO :smile:

**Comment by wolfspy** [comment]
That is the feature I need. We have no wash sales rules in place for crypto in the US yet so me and my friends would like to sell some ~$60k BTC we bought during the bull market and immediately buy back the current ~$19k BTC and we can only do that properly with a Highest In First Out tax calculation strategy.

**Comment by wolfspy** [comment]
Thanks so much team! You have a new paying customer (with more on the way). Now I just need [v1.27.0](https://github.com/rotki/rotki/milestone/54) to release before end of year with these changes 🤞
