### ISSUE TITLE
Better Oasis Earn Overview 

### ISSUE THREAD

**Issue by tradooor** [rotki/rotki#5148]
## Abstract

Currently there is no way in rotki to display Oasis' new [Earn](https://oasis.app/earn) positions in a meaningful manner.

## Motivation

I would expect many to use the curated Oasis Earn products in the future.

## Specification

I only tested the `stETH/ETH AAVE` position so far: rotki by default display's the ETH account's `WETH` debt as liability, but none of the `stETH`. If one adds Oasis' proxy contract address manually, `aSTETH` appears, along with `variableDebtWETH` (but listed as asset, not liability). BUT the only meaningful representation imo would be the total net value of the position in ETH, just like Oasis' web app does:
![image](https://user-images.githubusercontent.com/98160556/202464304-ca8f3019-f219-4bc8-a0c3-208dad9d9041.png)

And yes, I am a very happy rotki premium user.

**Comment by tradooor** [comment]
One more thing I noticed: `aSTETH` value is off by 2x since when adding `DSProxy` account manually, rotki detects `aSTETH` in both, the regular account used with Oasis and the proxy contract. When I delete `DSProxy` from rotki again, `aSTETH` completely disappears again.

**Comment by tradooor** [comment]
Somewhat could solve the `aSTETH` 2x issue by enabling the AAVE module for the proxy contract, but NOT for the maker contract.

**Comment by nebolax** [comment]
As found out, there is no central registry for oasis earn positions. That means we can't say for sure about a DSProxy whether it has positions that were opened through oasis-earn or somehow else. And that it why we cannot show "Net ETH value in Oasis" or anything like that. Oasis web app assumes that you provide it an address that has positions opened via oasis but we cannot assume that since it might confuse users who have not interacted with oasis.

**Comment by tradooor** [comment]
Got it. If I understood https://github.com/rotki/rotki/pull/5178 correctly, it'll display my `aSTETH` as assets and `WETH` as debt/liability without manual interaction from my side, which is good enough.
