### ISSUE TITLE
Uniswap pool assets (and similar) can not be differentiated in the PnL report issues view

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5255]
## Abstract

Right now is not possible to get the identifier for certain assets in the PnL report

![image](https://user-images.githubusercontent.com/5068010/207394664-472a2429-adad-41c6-82f2-921b29c79406.png)

Would be nice to display it and allow to copy by clicking somewhere

## Motivation

In the case of uniswap pools and some others where the symbol and name are the same you can't differentiate them

## Specification

Since they frontend already displays name and symbol I believe is a frontend only task

**Comment by LefterisJP** [comment]
This still sounds ugly. So what? You gonna add a new copy button in each of these lines making everything full of more clutter just for the edge case of pool tokens that have same name and symbol? I get why.

The problem you stated: 

> In the case of uniswap pools and some others where the symbol and name are the same you can't differentiate them

Say you do that. How is the user supposed to know what to do with that? They press it. And puts the id in the clipboard. What are they gonna do with it? How will they know it's there? It will say "copied". Okay so now what to do? Open a text editor and paste it? They see something like `eip155:56/erc20:0xF301C8435D4dFA51641f71B0615aDD794b52c8E9`. What do they do now? What does that mean to them? Will they know that they then need to copy only the last part after the `:` to etherscan and then open the "read code" to see what asset1 and asset2 are in order to figure out which pool it is?

I understand the problem you are describing. But the solution is not a solution for the users. It's a debugging solution for a developer.

**Comment by LefterisJP** [comment]
Also changed the title. Do not describe an issue by what you think we should do. Describe the problem. Solution are many. The problem is concrete and easy to describe.

**Comment by yabirgb** [comment]
1. Having the address at least I can go to etherscan or search the asset to know what exact pool I do have to search the price for. 
2. Is fine to copy only the address(since they are evm tokens) since the chain is exposed already in the icon with the small chain logo

I do believe having the option to copy the address is not just a dev solution since at the moment there is no way to differentiate the tokens and addresses are already familiar to users

**Comment by LefterisJP** [comment]
My tone was a bit aggressive back then.

So let me say that perhaps we can add an "etherscan" link perhaps for each asset that is an evm chain asset? In a non-obtrusive way that would not make it looks weird that it's missing from non-evm assets?
