### ISSUE TITLE
Linux binaries for 386

### ISSUE THREAD

**Issue by anselal** [rotki/rotki#54]
Is there a change you could compile a Linux binary for 386 architecture ?

Maybe more users like me would like to run rotkehlchen on an older spare pc...

**Comment by LefterisJP** [comment]
Hmmm you can always try to do it manually, but I use Travis and the ones that Travis supports for now are x86 binaries for Linux and OSX

**Comment by anselal** [comment]
Did you mean x64 ?

**Comment by LefterisJP** [comment]
yes

**Comment by anselal** [comment]
Got it. If you can compile the x86 binaries yourself and upload it whenever you release a new version that would be cool.

Otherwise we can always run rotkehlchen inside an isolated VM on our PC.

You can close this issue if you want...

**Comment by LefterisJP** [comment]
@kelsos is it possible to generate such binaries also to accomodate older pcs?

**Comment by kelsos** [comment]
Originally I was going to assume that we could do this, but it seems that it might not be possible anymore.  From a quick search, it seems that electron has dropped 32bit support on Linux: https://www.electronjs.org/blog/linux-32bit-support

Looking through the versions and releases, they have not been supporting 32bit Linux since around July 2019.
