### ISSUE TITLE
FTX File Import

### ISSUE THREAD

**Issue by jeffreytai** [rotki/rotki#5527]
## Problem Definition

Importing FTX trade returns. Prior to completely turning off all their services, many people were able to download their trades. Currently unable to do a manual import with "Custom Import".

File sample:
```
"ID","Time","Market","Side","Order Type","Size","Price","Total","Fee","Fee Currency","TWAP"
"6064395746","1/6/2022, 10:55:49 PM","FTM-PERP","sell","Market","109","2.67365","291.42785","0.12385683625","USD","false"
"6064395744","1/6/2022, 10:55:49 PM","FTM-PERP","sell","Market","469","2.67365","1253.94185","0.53292528625","USD","false"
"6064395742","1/6/2022, 10:55:49 PM","FTM-PERP","sell","Market","734","2.67365","1962.4590999999998","0.8340451175","USD","false"
"6064395740","1/6/2022, 10:55:49 PM","FTM-PERP","sell","Market","5","2.67365","13.36825","0.00568150625","USD","false"
"6064395738","1/6/2022, 10:55:49 PM","FTM-PERP","sell","Market","315","2.67365","842.19975","0.35793489375","USD","false"
"6064395736","1/6/2022, 10:55:49 PM","FTM-PERP","sell","Market","35","2.67365","93.57775","0.03977054375","USD","false"
"6064374934","1/6/2022, 10:55:11 PM","FTM-PERP","sell","Market","882","2.67915","2363.0103","1.0042793775","USD","false"
"6064374932","1/6/2022, 10:55:11 PM","FTM-PERP","sell","Market","404","2.67915","1082.3766","0.460010055","USD","false"
"6064374930","1/6/2022, 10:55:11 PM","FTM-PERP","sell","Market","1","2.6792","2.6792","0.00113866","USD","false"
```

## Logs
```
Invalid CSV format, missing required field: Could not find key 'Sell Amount' in csv row {'ID': '6064395746', 'Time': '1/6/2022, 10:55:49 PM', 'Market': 'FTM-PERP', 'Side': 'sell', 'Order Type': 'Market', 'Size': '109', 'Price': '2.67365', 'Total': '291.42785', 'Fee': '0.12385683625', 'Fee Currency': 'USD', 'TWAP': 'false'}
```

### System Description

Operating system: macOS Ventura 13.1
Rotki version: 1.26.3

**Comment by LefterisJP** [comment]
Hey @jeffreytai. Welcome!

The generic CSV import feature is explained [here](https://rotki.readthedocs.io/en/latest/usage_guide.html#rotki-generic-import).

It's so that you can modify any CSV import **manually** to match something we expect and import it to rotki. It concerns manual work since this you would use for CSVs we don't have an importer for. So you would need to modify that CSV in order to match the generic import format to be able to import it.

Supporting specifically the FTX format for the few people who had enough time to download the CSV before the website went down is not something we can dedicate resources too as the exchange is dead.

If you have trouble using the generic import after reading the docs feel free to join our discord and ask: https://discord.gg/aGCxHG7  (need to have DMs open since there is a captcha challenge)

**Comment by jeffreytai** [comment]
> Hey @jeffreytai. Welcome!
> 
> The generic CSV import feature is explained [here](https://rotki.readthedocs.io/en/latest/usage_guide.html#rotki-generic-import).
> 
> It's so that you can modify any CSV import **manually** to match something we expect and import it to rotki. It concerns manual work since this you would use for CSVs we don't have an importer for. So you would need to modify that CSV in order to match the generic import format to be able to import it.
> 
> Supporting specifically the FTX format for the few people who had enough time to download the CSV before the website went down is not something we can dedicate resources too as the exchange is dead.
> 
> If you have trouble using the generic import after reading the docs feel free to join our discord and ask: https://discord.gg/aGCxHG7 (need to have DMs open since there is a captcha challenge)

Ah I missed this document earlier, that's perfect. Thanks!
