### ISSUE TITLE
CI feature: integrate pull request preview environments

### ISSUE THREAD

**Issue by waveywaves** [rotki/rotki#5597]
I would like to support Rotki by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) preview environments.
Disclaimer: I work on [Uffizzi](https://github.com/UffizziCloud/uffizzi).

Uffizzi is a Open Source full stack previews engine and our platform is available completely free for Rotki (and all open source projects). This will provide maintainers with preview environments of every PR in the cloud, which enables faster iterations and reduces time to merge. You can see the open source repos which are currently using Uffizzi over [here](https://uffizzi.notion.site/)

Uffizzi is purpose-built for the task of previewing PRs and it integrates with your workflow to deploy preview environments in the background without any manual steps for maintainers or contributors.

We can go ahead and create an Initial PoC for you right away if you think there is value in this proposal.

**Comment by kelsos** [comment]
Thank you for the proposal @waveywaves 

We have tried to do preview environments in a previous job and the idea is not bad itself. However, at least for the rotki workflow, I wouldn't use a cloud preview environment.

Due to the nature of the application, when testing rotki we rely on local data/accounts which I would not personally move outside of my workstation. But even if I was willing to do so, managing, and syncing these data outside of my workstation would add an overhead to checking each PR.

I am not sure what @LefterisJP thinks but at least for me this is not something I would use.

**Comment by LefterisJP** [comment]
I agree with @kelsos. Probably not a good fit for us at this time.

Thank you for the proposal.
