### ISSUE TITLE
Separate settings table into multiple categories

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5655]
## Abstract

The only key-value table in the user DB is the settings table. There we dump everything we need to remember but it starts to get really big and hard to manage.

We should separate it in categories.

Some are:

- accounting settings
- general settings
- frontend settings (@kelsos asked for a key-value pair for frontend stuff)
- more.. ?

## Task

There is two ways I can think of doing it.

1. Add prefixes to settings. So `frontend.settings.setting1 = "value"`. This would be queried with `LIKE prefix%` in the backend. Would allow for multiple categories, subcategories all separated by ".". Probably a bit slower due to the matching?
2. Add a category column to the settings and separate stuff on the categories.

In any case a user DB ugprade would be needed to change schema and move data.

**Comment by kelsos** [comment]
Yes so for the frontend we have been pilling up stuff in the frontend_settings field.

And while a lot of them are settings, for example, we have now also added the user filters for the history pages there.

The filters are user data, they should follow the user account, so local storage is not an acceptable location since it is not portable, but also putting these data in the frontend_settings does also not make sense since these data should be section specific and only loaded while the user is in the respective section.

**Comment by LefterisJP** [comment]
Not sure if this is needed. Settings got reorganized in the UI but I don't see the point of changing the DB schema for it. No benefit.
