### ISSUE TITLE
Refactor HistoryBaseEntry

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#5689]
At the moment the HistoryBaseEntry contain special fields that are used only in EVM events. https://github.com/rotki/rotki/blob/d4bd4d3ded2583761e990a02a92ac5327007520b/rotkehlchen/accounting/structures/base.py#L89 . This is the case of the counterparty field for example.

We want to use this class and create statistics from them and do other complex operations. This would require the introduction of more complex fields to classify the history events but those won't be needed for example in kraken events or other types of base history event which is supposed to be the least common denominator of an event.

While developing statistics for liquity we saw that the current approach for counterparty doesn't allow us to filter by product or contract and this is something that would have made the queries easier. In addition there will be cases for certain protocols where we won't be able to query the needed information with the data we currently have.

The HistoryBaseEntry contains the `extra_data` field but since it is json if we want fast SQL queries we would need a text search and this is slower than doing a filter in a column.

## Proposed solution

We should create a new table that could be used with `JOIN` statements and would allow to consume extra information for EVM transactions while avoiding unused fields in other kind of events like exchange events.

Currently the evm transactions use location `ETHEREUM` and `OPTIMISM` and this can be used as criteria to apply the join

The columns that can be removed from the history events table are:

- counterparty
- extra_data is filled at the moment only in evm events

The new table let's call it `evm_events_info` should have

- [string] identifier: the same identifier as in history_events so we can join by this column.
- [string] protocol:  used to mark the protocol, for example curve or liquity
- [string] product: for example if we are interacting with a pool, staking contract or others. This will help when filtering the events adding easier granularity to the searches.
- [string] address: This would be the address of the contract. This would help to filter by older versions or limit searches to certain subsets of contracts. For example this would help filtering interactions with curve gauges.
- [string(json)] the extra data column from the history_events

### After this is done

- [ ] After this issue also do #5716

**Comment by LefterisJP** [comment]
I edited the spec names since this is an evm specific subtable we don't need to have super generic names. They should have the correct name they are supposed to be. Also I have questions:

`protocol`: This should be optional/null as not every EVM event will have a specific protocol, right?
`product`  -> I am not sure what this is. Can you explain what are the possible values? Can it be optional?
`address` -> This would be contract address for actions that interacted with a contract. For actions that just send ETH, would they be the receiver? For actions that received ETH? For token transfers it would still be the token contract, right?

**Comment by nebolax** [comment]
> This should be optional/null as not every EVM event will have a specific protocol, right?

Yes.

> I am not sure what this is. Can you explain what are the possible values? Can it be optional?

Probably @yabirgb is better to ask about this. From my perspective hm ... reading this now to me it looks quite similar to what `event type` and `event subtype` do.

> For actions that just send ETH, would they be the receiver? For actions that received ETH?

I would yes to these.

> For token transfers it would still be the token contract, right?

For this hm... good question. To stay in line with other events looks like the contract address will make more sense, but then we would lose the address of the other user, which we currently do save. https://github.com/rotki/rotki/blob/936ec65794a20fcc60ba98ff66a15a2e9161dc17/rotkehlchen/chain/evm/decoding/base.py#L121

Not sure ... one more field will probably be too much?

**Comment by LefterisJP** [comment]
> would lose the address of the other user, which we currently do save.

Isn't this the `location_label` in history_event? Do we need that to be in history_event? Is it generic enough for all events?

The idea to go forward is:

`history_event` is the least common denominator and has the minimum amount of info for each subevent.
Depending on event type it may have extra information in another table like this `evm_events_info` for evm transactions.

So that table can have as many entries as needed.


What I am not sure about is if we need an event_kind on history_event to know what table to join with if any.

**Comment by yabirgb** [comment]
The product `product` is something in addition to the protocol to allow for more granularity. For example when doing the analytics for liquity I found that having `protocol=liquity` was not enough to filter correctly the events and doing it by the type and subtype + assets was hard. The product in that case would be `staking contract` and `stability pool` and then I can filter by those special products inside the protocol.

The same happens with other for example curve, as a user I would find it useful to filter my interactions not just with curve but also limit it to gauges or pools.
