### ISSUE TITLE
Warn on unknown event type/subtype combination when adding/editing history events in EVM transactions

### ISSUE THREAD

**Issue by xtc0r** [rotki/rotki#5703]
Rotki does allow the users to pick any event type / subtype combination which can result in Transaction event type "unknown" but there is no error or warning presented to the user. 

This can be improved by:

- Simple: give error when transaction type unknown ir just do not allow to save it.
- Medium complex: Only allow to select subtypes which match event type by shrinking the subtype selection list based on event type
- Premium solution: 90% of defi events I found in my history are decoded as 3-4 events:

1. Gas fee
2. Action A
3. Action B
4. Approval (optional)

Usually Action A and Action B are linked which rotki could consider to improve UX by proposing event type for Action B based on Action A.

- If Action A is set as Trade / Spend then Action B is Trade / Receive
- If Action A is Deposit / Deposit Asset then Action B is Received / Receive Wrapped
- If Action A is Withdrawal / Remove Deposit then Action B is Received / Return Wrapped

What I don't know if this can be used as a general procedure to decode not yet implemented protocols.

**Comment by LefterisJP** [comment]
There is a mapping of accepted events in the frontend at the moment. The frontend can already check if the combination would match this mapping and if not warn the user.

I think the solution we should go for, at least for this issue is:
>  give error when transaction type unknown ir just do not allow to save it.
> Medium complex: Only allow to select subtypes which match event type by shrinking the subtype selection list based on event type

But instead of error a warning. Since we will offer customization of all types for accouting so user can make their own types: https://github.com/rotki/rotki/issues/4341


We are also going to move these mappings eventually to the backend so we don't maintain the mappin in 2 places. But at the moment I think this can be done on the frontend: https://github.com/rotki/rotki/issues/2203
