### ISSUE TITLE
Approval event in swaps

### ISSUE THREAD

**Issue by nebolax** [rotki/rotki#5722]
## Problem Definition

An approval event in between of the spend and the receive event in a uniswap v2 swap, which causes wrong numbers in PnL.

## Spec

- [x] Fix the particular case reported by Sebastian.
![image](https://user-images.githubusercontent.com/63492346/222718479-cca2cf4d-ac7a-4cbf-a101-1e464f375fed.png)

- [x] Add a test for that case
- [ ] Check other swaps decoders and make sure that are no approval events can appear there in between spend and receive. 

Operating system: 
Rotki version: 1.27.1

**Comment by LefterisJP** [comment]
Note: **any event** in between. Approval is just how this one manifested.

There should be no event between a send and a receive. Otherwise it's not a swap. I would go so far as saying we should run checks on those post-decoding maybe? I am not sure.

We can also go further. And show a recognized swap in a specific way in the frontend.

**Comment by LefterisJP** [comment]
This should be fixed afaics
