### ISSUE TITLE
Allow default connect/read timeout and more to be customizable

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#6041]
## Abstract

At the moment all connection related timeout and retries variables are hard-coded constants in the code:
https://github.com/rotki/rotki/blob/9e640017554fd44f7eedda06ca79b8edfa344105/rotkehlchen/constants/timing.py#L16-L18

There is no possibility to customize them depending on the user's situation and connection capabilities.

## Motivation

If a user is in a slow connection place we should allow them to configure these variables.

## Specification

Make them configurable settings

**Comment by dimyG** [comment]
Currently the only way to access the settings is to read them from the user database with the DBHandler.get_settings method (https://github.com/rotki/rotki/blob/develop/rotkehlchen/db/dbhandler.py#L552). 

This creates a challenge in moving these constants to settings because these constants are used in many places, including places where the dbhandler instance is not available. For example https://github.com/rotki/rotki/blob/develop/rotkehlchen/chain/ethereum/graph.py#L91 or https://github.com/rotki/rotki/blob/develop/rotkehlchen/icons.py#L163 and elsewhere. 

We discussed two possible solutions:
1. Pass down the dbhandler instance to all places where these constants are used (and get them from get_settings method). 
2. Cache the settings in a global object, import this object directly where you need it and read the settings you want from it.

Additional details for solution 1
The change can happen gradually, by having these values both in constants and in settings and read them from settings when you can while keep using the constants when its difficult to get access to the dbhandler.

Additional details for solution 2
We can use a singleton to cache the settings. It is initialized at user login and deleted at user logout. Here is an approach using a SettingsManager singleton class https://gist.github.com/dimyG/27322bb312ed3659370b58f9d8338261. Then you can sync_with_user_db in dbhandler get_settings method, update the cached settings in dbhandler set_settings and set_setting methods. This singleton approach though is an antipattern. We only use them for things that are really global over the entire app such as the globalDB and global prices, while the settings is specific to the user and not to the app. Many users can have account to the same app installation.
