### ISSUE TITLE
Binance API does not retrieve my AXS transactions, only ETH

### ISSUE THREAD

**Issue by PabloCastellano** [rotki/rotki#6283]
## Problem Definition

I have connected rotki with my Binance API key. Looks like it imported my transactions correctly but it only imported ETH and I have also made transactions with AXS.

From the [documentation](https://rotki.readthedocs.io/en/stable/usage_guide.html#binance-binance-us):

> Binance API is engineered in a way that makes it really slow to query information for trades since every possible market pair has to be queried. This process can also fail since many requests have to be made to binance servers and rate limits may apply. To avoid having to query all existing trade pairs, it is possible to select what markets should be queried. This will considerably increase the speed as the amount of queries to binance will be reduced to only the markets you specify. To select which what markets you want to query edit your binance exchange instance

I have added the all available market pairs starting with axs* as explained in the documentation but still nothing. The operation was exchanging AXS to EUR. Not sure this pair needs to be specifically entered but I could not find it in the available options.

### System Description

Operating system: Linux
Rotki version: v1.28.0

**Comment by LefterisJP** [comment]
> ## Problem Definition
> I have connected rotki with my Binance API key. Looks like it imported my transactions correctly but it only imported ETH and I have also made transactions with AXS.
> 
> From the [documentation](https://rotki.readthedocs.io/en/stable/usage_guide.html#binance-binance-us):
> 
> > Binance API is engineered in a way that makes it really slow to query information for trades since every possible market pair has to be queried. This process can also fail since many requests have to be made to binance servers and rate limits may apply. To avoid having to query all existing trade pairs, it is possible to select what markets should be queried. This will considerably increase the speed as the amount of queries to binance will be reduced to only the markets you specify. To select which what markets you want to query edit your binance exchange instance
> 
> I have added the all available market pairs starting with axs* as explained in the documentation but still nothing. The operation was exchanging AXS to EUR. Not sure this pair needs to be specifically entered but I could not find it in the available options.
> 
> ## Logs
> ### System Description
> Operating system: Linux Rotki version: v1.28.0

It needs to be specifically entered. If it's not there, then it's history can not be retrieved by the binance API. This is yet another problem with the way binance have constructed their API :disappointed: 

So you sure it was that pair and that pair is no longer available?

**Comment by PabloCastellano** [comment]
I have confirmed in the binance ui that the pair for the transaction is AXSEUR. Then I've doublechecked that indeed this pair in not showing up in the filter.

![image](https://github.com/rotki/rotki/assets/73274/7ecf93a1-0c74-4ed0-b00e-f1c3e46489b7)

**Comment by LefterisJP** [comment]
> I have confirmed in the binance ui that the pair for the transaction is AXSEUR. Then I've doublechecked that indeed this pair in not showing up in the filter.
> 
> ![image](https://user-images.githubusercontent.com/73274/247080192-7ecf93a1-0c74-4ed0-b00e-f1c3e46489b7.png)

Yeah so then as I suspected this can only mean the pair has been delisted, which also delists its history from the API.

The pairs we get from binance itself. The API is open and it's this call: https://api.binance.com/api/v3/exchangeInfo

As you can see if you filter for AXS the AXSEUR pair is missing.

![2023-06-20_13-13](https://github.com/rotki/rotki/assets/1658405/3c486519-ee52-49e0-a51e-644178fbc4a5)

The only way according to binance's API (and also as you saw in the docs posted above) to query history is by iterating all listed pairs and then getting history per pair. Using this endpoint: https://binance-docs.github.io/apidocs/spot/en/#account-trade-list-user_data

If a pair does not exist then its history can not be retrieved via the API. You can probably open a ticket asking them about this, though we and other users have opened tickets, complained in the forums for a better API but binance does not seem to want to improve it.

Since we can't do anything to help here on our side I am going to close the issue. If there is anything you think we can do on this or you have any more things to note write here and we can reopen.
