### ISSUE TITLE
Add ability to export history events (unprocessed)

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#630]
Edit by Lef: Newest edit and what we consider the spec as of 21/09/2023

## Abstract

The user should be able to export their history of events out of rotki. They should be able to go to the history events view, press export and get an export of all the events in their history in the rotki events format.

They should also be able to filter down the selection by the already existing filters of that view. So if a filter is applied the export will only export all events matching that filter.

At the current state of rotki, this will miss some events. Namely trades, ledger actions and asset movements. But once:

- https://github.com/rotki/rotki/issues/6097
- https://github.com/rotki/rotki/issues/6096
- https://github.com/rotki/rotki/issues/6099
- https://github.com/rotki/rotki/issues/6623

are done, and everything has been moved to history events, this will actually export everything.

## Motivation

Some effort wents into rotki to setup all the info. Rotki should not "lock in" the user but provide an export functionality in an unencrypted way. Even though the PnL export exists, this is for processed events. Users should be able to also export their raw history events or any subset of them.

## Specification

- [ ] Create a new API endpoint for exporting history events. That endpoint should accept the exact same filters (without pagination part) that https://rotki.readthedocs.io/en/latest/api.html#dealing-with-history-events accepts. It should also accept either a filepath for electron app or nothing for docker. It should then export the events in our raw format in CSV file to the filepath for electron or prompt for a download of a file in docker.
- [ ] Premium limits should not apply here. We do not hold users data hostage for money. They can export all data no matter the premium level.
- [ ] Write tests for it
- [ ] Create the frontend part, including integrating the export in a nice and visible part in the UI of the history events view.

**Comment by LefterisJP** [comment]
What format would be the best for such an export @coinyon?

**Comment by coinyon** [comment]
You can choose between CSV, XML or JSON. It would probably be JSON nowadays. You could export `Trades.json`, `OTCTrades.json`, `Balances.json`, and so on, and define a JSON-Schema for each, but thats optional.

**Comment by LefterisJP** [comment]
Trades + OTCTrades would be together. Since the format is the same. You can actually look at all these if you go into your DB manually and see it with sqlite queries.

JSON huh? I was more thinking of CSV for such a thing but let's see. Will do some research as to what would fit best.

For balances what do you mean? The current balances? There is no need for that since each time it changes depending on your configured assets.

Addresses per blockchain and owned tokens definitely.

**Comment by coinyon** [comment]
Yep, you are right about the balances.

CSV is also a possibility and maybe the easiest to implement. JSON could contain some Meta information like export version, if you are planning to change the export schema later, also JSON could contain all information in a single file. But CSV is also ok.

**Comment by IsseiBelial** [comment]
Json long-term for sure. 
But CSV is also fine and allows for backwards compatibility with other tax software. 

From a business prospective, long run I'd love to know that the address I sent my .001btc to was the coffee shop for a meeting. Or I spent .3ETH for X conference. It makes it easier for itemized deductions that will likely become more common asore people do business in the space. 
Having to itemize my entire tax list this year and year before(but didn't care much then) actually is kind of a pain lol. Since I think I only made 10% income in actual cash, and moreso most everything was business. 

But seriously seeing this made my day. I have been hoping to see something like this for years, and almost gave up on it. Glad I saw it posted today.

**Comment by A2be** [comment]
A related issue was discussed on the Rotki Discord on 23 Nov 2020.  

discussing whether the existing Rotki Github issue (#630, from Jan 2020) would only export all of the following:
     "Add ability to import and export trades / addresses / balances"

whereas the Discord user was asking about something that would NOT export any trades or balances, but only the addresses, exchanges, API keys, config data, etc.

In other words, 
 - IF one could export all the user-specified info of that type, including customizations like tags, settings, etc.
 - THEN a new Rotki instance (potentially, on a new machine) would go out and find/get all the trades, deposits, withdrawls, balances, and other tax-related info, simply by querying the blockchain and doing exchange API reads, and just doing what Rotki does well.  But would not lose the customer input data that took a lot of time to input into Rotki.

lefterisjp | Rotki  :  yeah as I said that issue could be configurable. i.e. you configure what you want to export.

Cantillon:  It sounds like that is not possible today.
But as a potential feature enhancement, I think it'd be helpful to have (but it is not the same as Github Rotki issue #630)

Cantillon replied to lefterisjp | Rotki
I got it.  Yeah, if you **make the export sufficiently granular**, that would solve the problem.  Thanks for the responses.

**Comment by sap51** [comment]
I'm not exactly sure that I'm in the right thread, but I'm definitely looking forward a CSV import functionality.

I'm using a Ledger wallet, which offer a CSV export functionality, and I would love to be able to create a new "custom wallet" in Rotki, name it "Ledger", and then import the CSV data to it.

I understand that it is complicated to support all kind of possible import CSV formats, but that would be already nice if there was even a single mandatory format that was allowing CSV import.

You could be the one deciding what is the supported CSV import format (i.e. what is the order of the cells, and what are their expected values), and users could easily edit their CSV to match this format before importing it.

Is it something that is on the roadmap ?

Thanks

**Comment by LefterisJP** [comment]
Hey @sap51 thanks for chiming in.

That would be the import part of the issue. And yes we also need to implement that. But I think for now first we would need to deal with the export of the events first and then deal with importing as a follow up.

**Comment by bitofit** [comment]
@LefterisJP 
> I think for now first we would need to deal with the export of the events first and then deal with importing as a follow up.

Maybe consider the reverse?  I would prioritize onboarding users onto the platform.  As it stands, users coming from (hundreds of) tax/trading platforms which (mostly) export to CSV have no way of importing their trade history onto Roki.

**Comment by LefterisJP** [comment]
> Maybe consider the reverse? I would prioritize onboarding users onto the platform. As it stands, users coming from (hundreds of) tax/trading platforms which (mostly) export to CSV have no way of importing their trade history onto Roki.

For each platform you need supported we need to do work in order to support that specific CSV format. For example https://github.com/rotki/rotki/issues/2224 etc. And that format may also change in the future, which is a nightmare to support. We heavily prioritize platforms that offer APIs instead as these tend to stay stable.

I don't know of anyone who would manually try to convert a specific platform's CSV to our own. They would expect us to import directly. So for now we just go by user requests.

Making a generic import format for our platform should not be that hard though. So is not that hard to implement. I just don't know who would use it,. as it would require a lot of manual work on the user's side to convert the CSV on their own.

**Comment by bitofit** [comment]
I would use it right now today.  I have 8 years of trade history on bitcoin.tax and no way of importing it to Rotki.

**Comment by LefterisJP** [comment]
This is a fair enough point @bitofit. I feel you. I will try to prioritize this then. We are a very small team, completely self-funded so prioritizing is hard mostly due to lack of resource, but you do have a valid point. Thanks a lot for chiming in.

At the same time for bitcoin.tax we got this issue: https://github.com/rotki/rotki/issues/1217

but nobody has provided us examples of CSV files. If we get example CSV files with what it's possible to contain we can also create importers ourselves which would make your and other users coming from bitcoin.tax life easier.

**Comment by bitofit** [comment]
Completely understand!  I'll add CSV export templates to #1217 as well

**Comment by LefterisJP** [comment]
For importing let's use https://github.com/rotki/rotki/issues/2270 that @bitofit made, so we got those as two separate actionable items.

**Comment by 0xRusowsky** [comment]
+1

## Abstract
Rotki is a powerful decoder that gathers plenty of information from different data sources and provides users with extremely valuable information with a really comprehensive UX. Nevertheless, despite having all this information accessible in the app, users can only download a PnL report.

To unleash the full power of Rotki, users should be able to extract any information available in the tool (instead of being limited to a single PnL report). 

Use cases:
- Custom PnL reports
- Share information with tax authorities and/or tax accountants
- Ability to manipulate data (excel, python, etc) to develop custom tools such as trading logs, custom portfolio statics, etc.



## Motivation
Rotki describes itself as a `portfolio tracking, analytics, accounting and tax reporting application that protects your privacy`. To power the advertised suit of applications, Rotki is first a decoder. Nevertheless, its inability to download decoded data is limiting its flexibility and potential value-add for users.



## Specification
data extract format: CSV

technical specifications: tbd by the team

**Comment by LefterisJP** [comment]
So this issue has gotten a lot of comments over the years so let me clarify what we want to do here and consider this closed.

## Problem

We want to allow the user to export all the preprocessed data of rotki without any processing so it can be moved elsewhere or shared with an accountant or someone else.

## Specification

- Create a new API endpoint for this purpose
- It will export them in a CSV format
- The exported data can be filtered. You can exclude specific event types and locations from the export.

Export the data of the following events from the DB:
- All exchange trades
- All exchange events that are not trades/withdrawals/deposit. For example kraken staking. Binance earn.
- All exchange deposits/withdrawals
- All decoded evm transactions for all chains.
- Staking data for ethereum consensus layer. The income of validators per day.


(If more events are thought of they can be added later).

Balances are off-scope. This is only for events.

**Comment by A2be** [comment]
@LefterisJP , I've got a clarifying question.

You focus on events there in your summary comment.  Would there also be a way to export (sans events) all of the blockchain addresses + exchange accounts + (maybe) the text names & group classifications of all accounts?  I.e., all the stuff a Rotki user might want to share with a tax professional who is then gonna want to go and use their own techniques (on-chain, etc.) to find all the on-chain xactions?

I just want to be sure this works for the use case where one can get their tax professional up to speed on all one's blockchain stuff (from info already in Rotki), without having to send the Rotki DB and DB decryption key to the tax professional.

**Comment by Beasta** [comment]
i track a large number of accounts and always thought it would be very handy to have a chrome extension for saving notes on them. if rotki had an api for accessing as well as modifying those notes, i'd work on a chrome extension for consuming it. 

i've done work on a scraper for exporting my personal etherscan address notes. would be super handy if i could then upload them to rotki

**Comment by LefterisJP** [comment]
> i track a large number of accounts and always thought it would be very handy to have a chrome extension for saving notes on them. if rotki had an api for accessing as well as modifying those notes, i'd work on a chrome extension for consuming it.
> 
> i've done work on a scraper for exporting my personal etherscan address notes. would be super handy if i could then upload them to rotki

We have an api for notes and you can access them. Check https://rotki.readthedocs.io/en/latest/api.html#handling-user-notes
The entire communication between frontend and backend is done through this API and all endpoints are there ^

**Comment by A2be** [comment]
> > @LefterisJP , I've got a clarifying question.
> > You focus on events there in your summary comment. Would there also be a way to export (sans events) all of the blockchain addresses + exchange accounts + (maybe) the text names & group classifications of all accounts? I.e., all the stuff a Rotki user might want to share with a tax professional who is then gonna want to go and use their own techniques (on-chain, etc.) to find all the on-chain xactions?
> > I just want to be sure this works for the use case where one can get their tax professional up to speed on all one's blockchain stuff (from info already in Rotki), without having to send the Rotki DB and DB decryption key to the tax professional.
> 
> This is out of scope for this issue. We want to focus on events here as this is what most people need.
> 
> Tracked accounts and labels is a very small bit of info and not sure how it can be helpful, but it can also be done as a followup. Should not be too hard. Exchange accounts can't be exported as there is no account there. Just an api key. Perhaps make a follow up issue describing what you want?

Thanks, Lefteris.  I opened a new feature add:  **Export Rotki info to get a tax professional onboarded to doing (non-Rotki) taxes** [Github #5822](https://github.com/rotki/rotki/issues/5822)

**Comment by LefterisJP** [comment]
> So this issue has gotten a lot of comments over the years so let me clarify what we want to do here and consider this closed.
> 
> ## Problem
> We want to allow the user to export all the preprocessed data of rotki without any processing so it can be moved elsewhere or shared with an accountant or someone else.
> 
> ## Specification
> * Create a new API endpoint for this purpose
> * It will export them in a CSV format
> * The exported data can be filtered. You can exclude specific event types and locations from the export.
> 
> Export the data of the following events from the DB:
> 
> * All exchange trades
> * All exchange events that are not trades/withdrawals/deposit. For example kraken staking. Binance earn.
> * All exchange deposits/withdrawals
> * All decoded evm transactions for all chains.
> * Staking data for ethereum consensus layer. The income of validators per day.
> 
> (If more events are thought of they can be added later).
> 
> Balances are off-scope. This is only for events. Balances are already exported/imported via the snapshots.

I am scheduling this for next release. Only for history events. Editing the title & description to clarify what needs to be done.
