### ISSUE TITLE
Have good and documented extensibility

### ISSUE THREAD

**Issue by coinyon** [rotki/rotki#631]
## Abstract

I think a open source project like rotki should have good extensibility for token specific logic.

## Motivation

Onboard more developers and have each integration written by the people who actually know about them (see https://twitter.com/coinyon/status/1206159428115935232). Examples would be #598, #597, or maybe even show MKR that is owned but currently in voting contract.

## Specification

1) A good and simple interface. Seeing that some of rotki is written in python, you could define a python interface that gives access web3 modules, and should return either a list of current balances or a history of transactions etc.?

2) A good documentation. It should be easy to get started.

**Comment by LefterisJP** [comment]
Hey @coinyon Rotki is actually quite modular and extensible! For example:

- The backend is running completely independent of the front-end. In theory multiple different front-ends could be written. The backend can be queried through a REST HTTP API.
- There is a single module per component. For example one module per exchange [here](https://github.com/rotki/rotki/tree/develop/rotkehlchen/exchanges)
- Single module per external API connections. [See here](https://github.com/rotki/rotki/tree/develop/rotkehlchen/externalapis)
- Ethereum module [here](https://github.com/rotki/rotki/blob/develop/rotkehlchen/ethchain.py)

and so on and so forth...

> A good documentation. It should be easy to get started.

We got documentation, but as usual it could be improved. But being an opensource project it's really not always easy for us to do everything. Current docs are [here](https://rotki.readthedocs.io/en/latest/). If something is unclear all feedback is welcome and we will fix it.


> Onboard more developers and have each integration written by the people who actually know about them

That's a great goal! I would love that. But unfortunately it's easier said than done. I have been tweeting and posting in reddit asking for help in developing this tool for more than a year. Not many people replied. And from those who did even less ever visited Github. So at the end I guess we have to implement at least the most popular features on our own since more than other developers we need users and feedback from said users.

If you got any ideas or ways with which we can attract more developers to this project I am happy to try and experiment.

**Comment by coinyon** [comment]
Cool, when I find the time I'll try my luck with #629 and see how the extension onboarding process is like and wether it can be optimized.

**Comment by LefterisJP** [comment]
I guess we can close this as it's not really actionable. And it generally echoes with the more modular approach we would like to take for the app: https://github.com/rotki/rotki/issues/1874
