### ISSUE TITLE
Automatically update in the background the portfolio plot on the main dashboard

### ISSUE THREAD

**Issue by schklom** [rotki/rotki#6407]
## Abstract

In the dashboard, the plot of portfolio value over time is only updated when the website gets loaded.
I would prefer that it gets updated every X amount of time, I feel every 2 hours is a good start.

## Motivation

If I do not connect to the main webpage in over 2 weeks, the dashboard plot only displays the current value of the portfolio, and I have no idea if it went up or down in the last few days.

## EDIT
I am running Rotki via Docker on a ARM64 machine.

**Comment by kelsos** [comment]
Hey, @schklom how are you using the application, electron, docker, dappnode?

You mention "the website" so probably not the electron application, right?

So for the first part, you can optionally enable the automatic balance refresh
![image](https://github.com/rotki/rotki/assets/2269732/438270c6-58d0-4ad5-a745-23698aa59c24)
But this only works while the front end is running and connected.

You can find the setting if you scroll down in the general settings.

Now for the second part, this is trickier. The graph works using snapshots, for snapshots, you have to open the application daily.

Any solution for auto-updating snapshots would require a user to be logged in otherwise it won't work. 

For the missing data, we have an issue getting any available public information (#1379) but it won't be as accurate as a snapshot.

I am not sure how easy or hard would be to implement an automated periodic snapshot mechanism but this would still require a logged user.

Maybe @LefterisJP can chime in here.

**Comment by LefterisJP** [comment]
Don't we already have automatic snapshots every `X` seconds?

**Comment by schklom** [comment]
Thanks for the fast answers :)

@kelsos Rotki is running in a Docker container on a Raspberry Pi (arm64).

> So for the first part, you can optionally enable the automatic balance refresh

Already enabled, set at 60 minutes.

> The graph works using snapshots, for snapshots, you have to open the application daily

Does it mean I would need to have a browser with the webpage opened every hour in order to show a hourly graph? I guess I could setup a Firefox/Chrome in a Docker container, point it to Rotki, and enable `Automatic balance refresh`, but this does not sound intuitive for regular end-users.

**Comment by kelsos** [comment]
So if you want an hourly graph you need to adjust the following setting.

https://rotki.readthedocs.io/en/latest/usage_guide.html#balance-data-saving-frequency

If I am not mistaken it is now once per day.
We discussed it with @LefterisJP and there is a mechanism in the backend that will try to generate a snapshot automatically as long as enough time has passed, the time between snapshots is determined by the setting above. 

In the meanwhile, we will also fix a bug in the frontend to ensure that it includes the snapshot data on the automatic refresh.

**Comment by schklom** [comment]
Thanks @kelsos :)
I guess I should keep this open until the bug in the frontend is fixed.

**Comment by kelsos** [comment]
The linked PR is #6424 and I think it misses a changelog entry maybe we can add a changelog entry and close the issue.

It should make it to the next release
