### ISSUE TITLE
Disable the motion background on the registration account

### ISSUE THREAD

**Issue by mariushosting** [rotki/rotki#6554]
The motion animated background in the registration page can cause epileptic seizures.
I think It should be disabled from the beginning or put a warning about this.

**Comment by kelsos** [comment]
Hey @mariushosting, thank you for the input.

The animated background it's going to be removed in the next feature release of rotki.
We are working on a updated design for the login screen.

I will close the issue since it is already part the work in progress but I will link to the PR when it is ready.

**Comment by mariushosting** [comment]
Thank you kelsos!

**Comment by kelsos** [comment]
> Don't we already have an option to remove it for computes that can't handle it? https://rotki.readthedocs.io/en/stable/usage_guide.html#animations-effect
> 
> Or does this not affect the loading background?

Animations are on by default, which means that you will get exposed to the moving background before being able to disable it, so it doesn't help.

**Comment by kelsos** [comment]
@tewshi when you have the PR ready for the login can you link it to this issue too, just to have a link for tracking?

**Comment by lukicenturi** [comment]
new login screen has been pushed to develop, so this motion background is no longer exist
