### ISSUE TITLE
Explain required permissions when adding an exchange API key

### ISSUE THREAD

**Issue by MantisClone** [rotki/rotki#6739]
## Abstract

Make the UI explain the required permissions when adding an exchange API key.

## Motivation

This could ease onboarding for users who do not yet understand the capabilities of Rotki. This could help users understand which permissions are necessary, which are optional, and which are unnecessary. This would allow them to make better security-conscious decisions about least privilege.

As a relatively experienced user, it's unclear to me if adding a Kraken account requires Query permission or Data Export permission, or both.

## Specification

Consider adding informational text or images in the whitespace below the API Key and API Secret fields.
![image](https://github.com/rotki/rotki/assets/2530913/eccbd26c-3634-4014-8920-f7ac9cc3ae5e)
![image](https://github.com/rotki/rotki/assets/2530913/b847ec16-8b5c-40b4-a57d-83ce459d4390)

**Comment by LefterisJP** [comment]
Hey fren welcome!

It's all in the docs and since it depends on each exchange it's kind of hard to have it in the UI. Here is the relevant section: https://rotki.readthedocs.io/en/latest/usage_guide.html#api-key-permissions

The permission you have in the screenshot are what you should have.

Btw such questions are easily answered via discord: https://discord.rotki.com/

@originalrfr do you have any advice here?

**Comment by MantisClone** [comment]
Oh, fair enough. I didn't even think to look for documentation. I still think instructions in the UI could help, but feel free to close the issue if you prefer.

**Comment by originalrfr** [comment]
Thanks for sharing your idea @MantisClone 😊
We have discussed it, but due to the maintenance it would require and its dependencies on each exchange, it will not be implemented instructions within the application.
The documentation is accessible within the application through the help button and the discord.
