### ISSUE TITLE
Feedback on generic impact functionality

### ISSUE THREAD

**Issue by TimDaub** [rotki/rotki#6979]
Type	Location	Base Currency	Buy Amount	Sell Amount	Quote Currency	Timestamp	Fee	Fee Currency
Sell	binance	ETH	1	2	EUR	1		
Sell	binance	ETH	1	2	EUR	1		
Buy	binance	XMR	1	2.     ETH	1		
Buy	binance	XMR	1	2.     ETH	1		

A few things I just noticed

- if I define "Type" "sell" then rotki will import it as "Buy". If I define "Type" as "Sell" it properly imports it as "Sell"
- the docs say that Fee, Fee Currency and Description are optional, but the importer at least requires the headers. IMO it'd be nice if it could tolerate not getting those headers

**Comment by LefterisJP** [comment]
Hey @TimDaub since for issues we want to have actionable items let me see if I understand what you are asking.

### Should Error on unknown headers

> if I define "Type" "sell" then rotki will import it as "Buy"

For this I guess you would expect an error and not silently sending it to another type

### Case-insensitive headers

sell, Sell, SELL, sElL should all map to the same.


-------------------------------

> the docs say that Fee, Fee Currency and Description are optional, but the importer at least requires the headers. IMO it'd be nice if it could tolerate not getting those headers

The headers are not optional but the value in the column is optional.

**Comment by LefterisJP** [comment]
To close this issue up @OjusWiZard take this one as it's easy.

Just do the small stuff I mentioned above and make it against bugfixes.

The stuff I mentioned should essentially all be here: https://github.com/rotki/rotki/blob/b8a8c48d6ff482eb0be02a1599a5fef730c9f79c/rotkehlchen/data_import/importers/rotki_trades.py#L27

**Comment by LefterisJP** [comment]
closed by #7113
