### ISSUE TITLE
The Profit and Loss report seems to ignore the start date and rounds down to the beginning of the calendar year.

### ISSUE THREAD

**Issue by fvanderelst** [rotki/rotki#7257]
## Problem Definition

When producing a Profit and Loss report aligned to the UK tax year, and entering 06/04/2022 to 05/04/2023 (6 April 2022 to 5 April 2023), the report gets generated with the first line being the most recent (2023-03-20 01:09:30 in my case, there were no transactions after that and before 5 April 2023) - this is correct.

However the the last line (the oldest one) is 2021-01-02 18:49:11. This is *before* the start date I wanted, i.e. 6 April 2022. It means I can't use the totals generated to summarise the 12 months of the UK tax year.

The title at the top of the page shows:

"Report starting from 2022-04-06 00:00:00 to 2023-04-05 00:00:00"

Which is correct.

The CSV export includes all the lines shown, i.e. from *before* my intended start date (i.e. earliest is 2021-01-02).

Hopefully I'm just entering this incorrectly, apologies if so...  Thank you for a great piece of software !!!

### System Description

Macbook air M1, 2020

Operating system: Mac OS X Monterey, 12.6
Rotki version: 1.31.2, with Premium components, build 2023-12-06.

App Version: 1.31.2
Frontend Version: Frontend Version:
Platform: darwin arm64 12.6.0
Electron: 27.0.1
Premium Version: 7.0.1
Build: 1701857296807

**Comment by LefterisJP** [comment]
Hey hello! Thanks for being a rotki user and for the issue.

For such questions best please join our discord and ask there as this is not an issue rather a question: https://discord.rotki.com/

You can also check the [usage guide](https://rotki.readthedocs.io/en/latest/usage_guide.html#creating-a-profit-loss-report) and see that events **before** the report are always included because they are needed to determine the cost basis of your assets up until the start of the report. You don't start at 0 each year.

**Comment by fvanderelst** [comment]
Hello Lefteris,
Thanks for you answer.
You are correct and I should have read the doc more carefully ! Looking through the CSV file properly shows that the pnl_taxable columns is zero outside the dates I've chosen, so the total reported is correctly the total of the 12 months I'm after.
Thanks for a great tool/product. Awesome.
