### ISSUE TITLE
Import of Test cointracking file not working

### ISSUE THREAD

**Issue by franzkugelmann** [rotki/rotki#731]
## Problem Definition

After noticing Rotki in the latest gitcoin grants round i was trying to import the cointracking demo file (rotkehlchen/tests/data/cointracking_trades_list.csv) to get a quick feeling for the app. However, i get the following error message popup after selecting the file.
"source': {'Must be one of: cointracking.info.'}"
After searching a bit in the code (never coded in python), i have the feeling that maybe just the hardcoded source identifier is wrong in electron-app/src/views/ImportData.vue:91?
Should it be _cointracking.info_ instead of _cointracking_info_?

Nothing logged into the logfile.

### System Description

Ubuntu 19.10 with latest appImage rotki-linux_x86_64-v1.1.1.AppImage

**Comment by LefterisJP** [comment]
Hah! Indeed. Nice catch!

And naturally backend tests exist and work, but we don't have acceptance tests for the frontend yet for this since it's rather hard.

Would you like to make a PR to fix this since you found it out or should we just handle it? It's an easy fix and will be included in the next release.

Generally cointracking.info import is not a very well tested feature and it's not recommended since their data export format loses a lot of data.

**Comment by franzkugelmann** [comment]
Hi LefterisJP,
great! Please handle it without pull request from me. Thank your for your great work!

**Comment by LefterisJP** [comment]
Thanks @franzkugelmann we will handle it then. Also will ask if anyone out there wants to score an easy commit. It's literally an one line change :)

The change should happen here: https://github.com/rotki/rotki/blob/ad3d80c032618c5c88b5909f52254f57b1288c14/electron-app/src/views/ImportData.vue#L91 and it should be `cointracking.info`

**Comment by LefterisJP** [comment]
Fixed by #732
