### ISSUE TITLE
No support for Bech32 (bc1) addresses

### ISSUE THREAD

**Issue by hjorthjort** [rotki/rotki#734]
## Problem Definition

I have some BTC balance in a Bech32 address (those that begin with `bc1`).
blockchain.info doesn't support those on the API level.
For example, here is a random address I found on blockchain.info: `bc1qhkje0xfvhmgk6mvanxwy09n45df03tj3h3jtnf`
This can be viewed in the interface: <https://www.blockchain.com/btc/address/bc1qhkje0xfvhmgk6mvanxwy09n45df03tj3h3jtnf>
But the API does not support it: <https://blockchain.info/q/addressbalance/bc1qhkje0xfvhmgk6mvanxwy09n45df03tj3h3jtnf>

The relevant rotkehlchen.log entry is:

```
20/02/2020 14:57:07 CET -- DEBUG:rotkehlchen.api.rest:Request successful response={"result": {"status": "completed", "outcome": {"result": null, "message": "The given string bc1qsvhnjfuhfund4684tylcqnd402jvdr9lt3h7l0 is not a valid BTC address"}}, "message": ""}, status_code=200
```

Maybe the `query_btc_account_balance` function in `blockchain.py`  could be modified to use different APIs depending on address type:

```py
        try:
            if account[0:3] == 'bc1':
                btc_resp = request_get(
                    url='https://api.blockcypher.com/v1/btc/main/addrs/%s/balance' % account,
                )['balance']
            else:
                btc_resp = request_get_direct(
                    url='https://blockchain.info/q/addressbalance/%s' % account,
                    handle_429=True,
                    # If we get a 429 then their docs suggest 10 seconds
                    # https://blockchain.info/q
                    backoff_in_seconds=10,
                )
```

### System Description

```
uname -a
command -v geth && geth version
command -v parity && parity --version
command -v rotkehlchen && rotkehlchen version
[ -d .git ] && git rev-parse HEAD
```
gives
```
Linux alladin 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64 GNU/Linux
/usr/bin/geth
Geth
Version: 1.9.9-stable
Git Commit: 017449971e1e9e220efcd97d3313a0e27f47003b
Git Commit Date: 20191206
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.5
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go
/home/hjort/.local/bin/rotkehlchen
1.1.2.dev0+g42481b5.d20200220
42481b5f2ef28f25c99663a092f5c85157285379
```

**Comment by LefterisJP** [comment]
Argh this is annoying. Had no idea about this. If they don't support querying of these type of address balances then indeed we need to have yet another api to query as you suggest.

Two questions.

1. Where can I read more about these type of addresses and why they are different?
2. Rotki does not accept the address, right? Or it accepts it but fails at balance query?

**Comment by hjorthjort** [comment]
1. I'm no expert and didn't really know the difference before looking into this. I looked at <https://wiki.trezor.io/Bech32> and the BIP that introduced Bech32 addresses, <https://en.bitcoin.it/wiki/BIP_0173>

2. Correct. I get a "bell" notification: `Operation failed due to The given string bc1*************************************** is not a valid BTC address`

**Comment by LefterisJP** [comment]
Hey @hjorthjort would you like to handle this issue and submit a PR? If not don't worry we can also do it but since you discovered it I thought it might be a nice thing for you to contribute into Rotki this way.

What needs to be done is:

1. Add [bech32](https://pypi.org/project/bech32/) to the [rotki requirements](https://github.com/rotki/rotki/blob/develop/requirements.txt#L10).
2. Add a check for bech32 addresses in the  BTC address validator here: https://github.com/rotki/rotki/blob/d0c73f3bed898d815743146e985b6d331703e377/rotkehlchen/chain/bitcoin.py#L6. You would need to use [this function](https://github.com/fiatjaf/bech32/blob/master/bech32/__init__.py#L64) and check if it's a valid bech32 address. If not validation should fail. Essentially BTC logic should be like:
    * Is it a valid bas58 BTC address? Yay! We take it.
    * No? Then let's check for bech32 using the newly added library.
    * Is it a valid bech32 address? Yay! We take it.
    * No? Validation Error. The given string is not a valid BTC address
3. Add what you suggested in your [original comment](https://github.com/rotki/rotki/issues/734#issue-568376859). But since then the code changed. The blockchain class is now the chain manager and the new location is here: https://github.com/rotki/rotki/blob/d0c73f3bed898d815743146e985b6d331703e377/rotkehlchen/chain/manager.py#L186
4. Add also test cases for the new bech32 addresses in this unit test: 
https://github.com/rotki/rotki/blob/d0c73f3bed898d815743146e985b6d331703e377/rotkehlchen/tests/test_blockchain.py#L107-L114

For test cases I would recommend the one you used in your original post and the mainnet examples from [the specification](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#examples)

**Comment by hjorthjort** [comment]
I'd be happy to. Not until next week the earliest though.

Would you prefer using a single endpoint? Rather than checking what type of address it is and using different APIs, if we support the API that can handle more kinds of addresses, maybe we should just do that.

**Comment by LefterisJP** [comment]
> Would you prefer using a single endpoint? Rather than checking what type of address it is and using different APIs, if we support the API that can handle more kinds of addresses, maybe we should just do that.

Naah using multiple endpoints is good. In general, should have multiple backups as all these services go offline pretty often.

> I'd be happy to. Not until next week the earliest though.

Okay then depending on how v1.2.0 goes I may either do it myself if everything else is ready by the time we want to release it or push it to the next version and leave it to you. It's really something quick and easy. I listed all steps above :D

**Comment by hjorthjort** [comment]
Alright! I'm moving to Berlin this week which is why things are a bit chaotic, so do as you like. I'll put it in my backlog for now.

**Comment by LefterisJP** [comment]
hey @hjorthjort how is the move to Berlin going? Think you can still pick this issue up? We pushed it to the next release

**Comment by hjorthjort** [comment]
> hey @hjorthjort how is the move to Berlin going? Think you can still pick this issue up? We pushed it to the next release

Pretty rough first week, but I'm excited to dig into this. Getting to know virtualenv right now so I can run as a dev.

**Comment by hjorthjort** [comment]
Getting a `500 Internal Server Error` when trying to test with a Bech32 address through the app. Any way to print-debug the/run the backend as a server and query directly?

**Comment by hjorthjort** [comment]
Seems mostly good to go, but I haven't completed all the manual tests. Found two manual tests not working, assuming it's a regression but want to check whether it's a bug on `develop` or in my PR.

**Comment by LefterisJP** [comment]
Which manual tests? You mean testing for some stuff manually? I can check too, just tell me what.

**Comment by hjorthjort** [comment]
I mean the list here: <https://rotki.readthedocs.io/en/latest/contribute.html#manual-testing>
Adding Bech32 addresses manually works correctly AFAICT. Some of the manual tests are new steps to me, so I'll look at them after work.
