### ISSUE TITLE
Gemini Exchange Support

### ISSUE THREAD

**Issue by outpoints** [rotki/rotki#764]
I personally don't use Coinbase Pro/Coinbase anymore and would love to see the implementation of Gemini's API to import trading history!

I'm sure I'm not the only one who uses Gemini :)

https://docs.gemini.com/rest-api/

**Comment by LefterisJP** [comment]
hey @outpoints thank you for the issue! You are the second person to talk to us about Gemini so that's actually good. It means Rotki users would be interested in using it.

**Comment by LefterisJP** [comment]
This issue has been prioritized by a premium subscriber!

**Comment by cemozerr** [comment]
This seemed to have regressed. I'm getting these issues when I try to connect rotki to Gemini API:
```
Failed query for Gemini: Gemini query at https://api.gemini.com/v1/transfers responded with error status code: 400 and text: {"result":"error","reason":"MissingAccounts","message":"Expected a JSON payload with accounts"}
```

**Comment by LefterisJP** [comment]
Hey @cemozerr What do you mean regressed? Gemini is supported. This issue was to implement that, not for a bug.

For your specific issue can you (1) make a new issue and probably (2) hop into the discord https://discord.com/invite/aGCxHG7 and DM me to share a read-only key to try and reproduce the problem? I don't have a gemini api key (apart from the testnet one they have) to test a live gemini user.
