### ISSUE TITLE
Password handling

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#805]
## Problem Definition

passwords exceeding a certain length or containing special chars throw (500). With a 49 char and without special chars, everything is fine

### Solution Definition

- [ ] show max pw length in create screen. Show excluded/included chars. Target user group of rotki likely generates pws.
- [ ] show if entered password contains "illicit" chars and disable "create" button.
- [ ] show "passwords don't match" hint only after pressing "create" button.

**Comment by LefterisJP** [comment]
Hey @kilrau thank you so much for spotting this. Had no idea we had such a problem. We will handle it!

**Comment by LefterisJP** [comment]
I have not tested it yet but can you provide few examples of invalid passwords? Is it only the 50 chars limit? Or also some characters not allowed? We are only limited by what the underlying sqlcipher library permits.

**Comment by LefterisJP** [comment]
So @kilrau I had a look at this and the only thing I could find as not being handled correctly was a password containing the `"` character, and that's due to the way sqlcipher accepts the password (hint: it closed the password string).

By providing a proper escaping of this character all other passwords seemed to work. And I could not find a problem with the character limit.

Do you have any passwords not containing the `"` character which are not accepted? If not then this PR should handle this https://github.com/rotki/rotki/pull/812
