### ISSUE TITLE
Allow BTC xpub keys

### ISSUE THREAD

**Issue by kilrau** [rotki/rotki#808]
## Abstract

Allow the user to enter extended BTC pubkeys to track all addresses of the wallet

## Motivation

Since address reuse is highly dangerous and discouraged, most users hold funds in HD wallets and generate a new address for each deposit. Tracking a portfolio is not really possible with Rotki atm since one had to enter a new address everytime one does a tx.

## Specification

Allow entering extended pubkeys and derive addresses automatically. Allow modifying key path.

**Comment by LefterisJP** [comment]
That's a nice request and many bitcoin users have actually asked for this. I wonder how easy it is. My familiarity with Ethereum makes me not so familiar with the xpub style of BTC keys, but I will see how easy it is to implement them.

**Comment by LefterisJP** [comment]
We need to push this and may need help here.

**Comment by prestwich** [comment]
coming in from twitter. the outline here is

1. Import the xpub and store it
2. Derive the bip44 & 84 account nodes (potentially with user-selectable account number)
3. Derive internal and change addresses under those nodes iteratively until you have X unused addresses in each subtree
4. Track each address
5. Every time an unused address becomes used, derive a new unused one and track that

**Comment by LefterisJP** [comment]
Hey @prestwich thanks a lot for hopping in here. Any libraries/code (preferrably python) to use for (2) and (3) along with maybe some docs?

**Comment by prestwich** [comment]
We worked on this one. Installation is a bit finicky because of the libsecp256k1 requirement. I haven't bothered figuring out how to make it work with a simple `pip install`. I _have_ tested it with pyinstaller and it does package well. https://github.com/summa-tx/riemann-keys

There's also pycoin, which is a huge lib with built-in support for many coins: https://github.com/richardkiss/pycoin

I haven't used this one yet, but it does exist: https://github.com/ranaroussi/pywallet

**Comment by LefterisJP** [comment]
Thank you @prestwich will give it a try.

**Comment by prestwich** [comment]
Reading the bips themselves will be the most useful thing you can do. Relevant BIPs are 32, 44, 49, and 84

**Comment by pereztechseattle** [comment]
One way or another Rotki will have to talk to a Bitcoin node.  I use Electrum Personal Server myself, but bitcoind or anything like that should work.  You probably don't want to package a bitcoin fullnode with Rotki, so the question is: which public full nodes will Rotki talk to?

**Comment by pereztechseattle** [comment]
Note: as a quick-and-dirty workaround, you can use blockchain.info's REST API and pass in an xpub address, and it will do the work for you.  Example: https://blockchain.info/multiaddr?active=xpub123ABCD.......

**Comment by LefterisJP** [comment]
> One way or another Rotki will have to talk to a Bitcoin node. I use Electrum Personal Server myself, but bitcoind or anything like that should work. You probably don't want to package a bitcoin fullnode with Rotki, so the question is: which public full nodes will Rotki talk to?

Good question. Ideally just like with ethereum rotki should be able to connect to the user's node if they have one. If not then a node out of a list of pulic nodes should be used. I am not very bitcoin-literate so I am not sure how such a list should look like.
Some nodes from here? https://bitnodes.io/nodes/leaderboard/

> Note: as a quick-and-dirty workaround, you can use blockchain.info's REST API and pass in an xpub address, and it will do the work for you. Example: https://blockchain.info/multiaddr?active=xpub123ABCD.......

I saw that too. Is that not leaking a lot of info for the users though?

**Comment by pereztechseattle** [comment]
Yes, the downside with using blockchain.info is lack of privacy, but assuming Rotki will have to talk to a public node, that's an issue anyway.

**Comment by pereztechseattle** [comment]
> I saw that too. Is that not leaking a lot of info for the users though?

Yes, the downside with using blockchain.info is lack of privacy, but assuming Rotki will have to talk to a public node, that's an issue anyway.

**Comment by LefterisJP** [comment]
> but most users probably will not have a bitcoin full node of their own.

True. Same with ethereum. But this is something some of our users really like about Rotki. But yeah this is a different issue.

So then question. The difference between blockchain.info xpub and using a fullnode is that you have to trust the api of blockchain.info but with a full node you at least query the standard bitcoind api?

**Comment by pereztechseattle** [comment]
>The difference between blockchain.info xpub and using a fullnode is that you have to trust the api of blockchain.info but with a full node you at least query the standard bitcoind api?

I suppose the full node could be lying to you too.  But it's easy to simply switch to another node (or use a quorum of several), as opposed to being locked into blockchain.info as a kind of "service provider."

It's 1000x quicker and easier tho.  :). Might be an OK option in the meantime.  As long as users understand what it's doing.

**Comment by LefterisJP** [comment]
>  But it's easy to simply switch to another node (or use a quorum of several),

Yeah this is what we do with ethereum too.

So perhaps an easy plan forward is:

1. Tackle this issue with the blockchain.info endpoint
2. Make another issue for using a bitcoin full node for it for the long run. Use pool of pulic nodes.
3. Allow user to connect to his own (another issue)

For connecting to a bitcoin node and getting all addresses for an XPUB the only way to do it is like described here? https://github.com/rotki/rotki/issues/808#issuecomment-687903266

**Comment by pereztechseattle** [comment]
Happy to pitch in if I can.

**Comment by prestwich** [comment]
The main reason xpubs aren't published is that they exacerbate key compromise situations. If any private key under an xpub's public derivation gets compromised, the xpub and that privkey can derive all other public child privkeys

**Comment by LefterisJP** [comment]
> The main reason xpubs aren't published is that they exacerbate key compromise situations. If any private key under an xpub's public derivation gets compromised, the xpub and that privkey can derive all other public child privkeys

This danger is true for any kind of communication with a public node, though @prestwich right? The only way to avoid this is run a local bitcoin node and derive all addresses from the XPUB?

But that's good information for a warning if the user wants to add an XPUB to rotki.

**Comment by pereztechseattle** [comment]
> The main reason xpubs aren't published is that they exacerbate key compromise situations.

Yes, there are definitely privacy tradeoffs the xpub user should be aware of.  I think it's a reasonable risk, tho, since unless the user is connecting to their own full node, the addresses they're tracking will be made public anyway.

**Comment by prestwich** [comment]
Ya, any time you communicate an xpub you're running the risk that it gets cached and used to worsen future key compromise situations. I don't think this is typically a very large risk, but the community tends to discourage transmitting an xpub over the wire.

Side note:
- You don't need a bitcoin node to derive addresses. That can be done efficiently in any application. It's a pretty simple hmac-sha512 key derivation function

**Comment by LefterisJP** [comment]
> * You don't need a bitcoin node to derive addresses. That can be done efficiently in any application. It's a pretty simple hmac-sha512 key derivation function

Thanks James. So this would be our second approach (after an easy first iteration) then I guess. Because (I suppose) even if you derive the bitcoin addresses from an XPUB, they would be a lot and you would still need either a node or blockchain.info to query them, right?

So perhaps a good plan is:

1. For now, tackle this issue with the blockchain.info endpoint but warn the user carefully about the dangers of sharing their xpub publically.
2. Make another issue for calculating addresses from the XPUB and then querying a node for used addresses

Does that make sense?

> Happy to pitch in if I can.

Would love help with this, even with (1) as we are a small team. If you are not in discord, join in: https://discord.gg/aGCxHG7 and we can coordinate from there.

This is where a new bitcoin address is added: https://github.com/rotki/rotki/blob/358641dfca19629f0d2644a556ad97e21dde5828/rotkehlchen/chain/manager.py#L386

**Comment by kilrau** [comment]
Sorry for chiming in late.

> even if you derive the bitcoin addresses from an XPUB, they would be a lot and you would still need either a node or blockchain.info to query them, right?

Correct. Gotta see this differently though: exposing "5 single addresses", even to one service like blockchain.info is just several magnitudes less info exposure compared to "all addresses I'll ever generate with these keys" -> it's about protection of privacy in the future. Also [you can control how many unused addresses you generate](https://github.com/rotki/rotki/issues/808#issuecomment-687903266) after the last used one. So it can be all addresses the user generated and used so far + e.g. 5 fresh ones (just to be sure the user didn't press receive/generate 5 times without sending funds to the address). But not sure what  a common value here is, should check some wallets. For a typical hodler's hardware wallet, you might end up with several dozen addresses max, not more, estimated based on my personal usage. In short: the only correct thing to do is make rotki generate these addresses locally imho.

> 1. For now, tackle this issue with the blockchain.info endpoint but warn the user carefully about the dangers of sharing their xpub publically.

Not sure if the feature will get much love or usage that way (in all honesty, I wouldn't use it), especially not with blockchain.info, it might even harm the "protecting privacy" branding of rotki.

> 2. Make another issue for calculating addresses from the XPUB and then querying a node for used addresses

I would go this route right away without shortcuts. Generating the addresses with the libraries @prestwich linked should be doable. Where to query / how to query these addresses in a pro-privacy way is a bit more tricky and using a service like blockchain.info/blockstream.info is the obvious choice and can be instead the v1. For v2 you can consider doing what [Wasabi](https://wasabiwallet.io/) is doing: https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#synchronization to achieve privacy for these addresses too and also would allow anyone connecting their own node, but maybe someone has a better idea.

**Comment by LefterisJP** [comment]
Hey @kilrau, thanks a lot for chiming in and thank you for voicing your concerns.

> Not sure if the feature will get much love or usage that way (in all honesty, I wouldn't use it), especially not with blockchain.info, it might even harm the "protecting privacy" branding of rotki.

I understand that concern, I also would be reluctant to use it but there are users who have said that they would use this. Such as @pereztechseattle or this guy https://twitter.com/sjude09/status/1303416494072635392.

I don't see how it would hurt the privacy branding as long as there is a proper warning. There can never be 100% privacy when you need to contact so many different services as we do. All we can try to do is minimize them, shuffle them, and confuse them with fake queries. Our dedication to privacy is never going to change. If I was just full of shit I would not even be having this conversation and would simply query blockchain.info xpub and not care.

> I would go this route right away without shortcuts.

I would love to. I really do. The problem is lack of resources. As you have already seen we are a very small team, we are self-funded and trying to bootstrap. Our backlog for each release is huge and If we can deliver some value this release instead of pushing the whole thing for an indeterminate amount of time in the future I would like to provide this value. Releasing value early has the potential to translate to paid users, which helps us keep going. There is no ICO or VC money behind us.

On the other hand, perhaps this whole conversation is also not really worth it and the "no shortcuts" way is not going to take as long as I fear. But it's definitely longer than simply querying an API endpoint. If it's also not something terribly hard we can just do it and be done with it.

If someone can come help and implement it, that would be great.
If not I will take a look myself and assess how hard the no shortcut way is.

**Comment by pereztechseattle** [comment]
> If someone can come help and implement it, that would be great.

I should be able to contribute some time in the coming days and weeks; I just need to come up to speed on the codebase first.  

Phase 1 - Blockchain.info, quick and dirty

Phase 2 - "derive public keys privately but query them publicly"

final Phase 3 -  "talk directly to my fullnode"

**Comment by pereztechseattle** [comment]
BTW, I just discovered Rotki last week and it's already improved my systems immensely!  I'm using the REST API to feed data to my Kibana dashboards and bots and whatnot.  

Tracking your own balances everywhere SUCKS!!  Just wanted to say thank you. 🙏

**Comment by isidorosp** [comment]
> BTW, I just discovered Rotki last week and it's already improved my systems immensely! I'm using the REST API to feed data to my Kibana dashboards and bots and whatnot.
> 
> Tracking your own balances everywhere SUCKS!! Just wanted to say thank you. 🙏

We'd love for you to share what you did with "owning your own data" on our discord (https://discord.gg/aGCxHG7) or by tagging rotki (@rotkiapp) on twitter =) We're trying to build the community around rotki and we would love to see how your are using it in different ways. Such tooling/extensions of the application may be valuable to other users as well if you eventually feel comfortable enough sharing them!

**Comment by LefterisJP** [comment]
> > If someone can come help and implement it, that would be great.
> 
> I should be able to contribute some time in the coming days and weeks; I just need to come up to speed on the codebase first.
> 
> Phase 1 - Blockchain.info, quick and dirty
> 
> Phase 2 - derive addresses privately but query them publicly
> 
> final Phase 3 - talk directly to user's fullnode
> 
> I can probably implement the quick-and-dirty blockchain.info version fairly quickly, and you can decide if you want to include it or not. (either way, I'll probably use it on my own machine.  )

Thanks. As I said above if what you refer to as Phase 2 makes is not really hard we could go directly for it, but I would have to find some time to investigate.

Anything you can do to help is appreciated :+1:

**Comment by pereztechseattle** [comment]
Hello.  Quick update from me on this...   I've been digging into Rotki the last couple of weeks and I don't think I'll be contributing much unfortunately.  Reasons being:

1. realized this is written in python, not JS
2. for my purposes, most of this app is superfluous.  All I really want is an easy REST API with all my balances.  All the surrounding stuff (building the native app, username/password, trades history, the entire DeFi portion, etc.) it really just in the way for me.    

thanks!

**Comment by LefterisJP** [comment]
This does not seem like it will be made in 1.8.0. Pushing it to a smaller release but right after.

**Comment by outpoints** [comment]
Using a public service to lookup Xpubs is a huge security vulnerability because it gives them the ability to track all adresses back to one person.
It'd be better if we could somehow utilize something like [Electrs](https://github.com/romanz/electrs) or [Samourai Dojo](https://github.com/Samourai-Wallet/samourai-dojo) both of which require that you download the entire Bitcoin blockchain to a local drive so it's not being transmitted ANYWHERE but your local node.

**Comment by prestwich** [comment]
> Using a public service to lookup Xpubs is a huge security vulnerability because it gives them the ability to track all adresses back to one person

More accurate to call it a privacy issue. Which is true. But the app is aimed at Ethereum users who have already adopted the account model, so it is not worse than the existing privacy model for this application

**Comment by LefterisJP** [comment]
Hey @outpoints 

> Using a public service to lookup Xpubs is a huge security vulnerability because it gives them the ability to track all adresses back to one person.

Rotki **does not** use a public service to derive addresses from xpubs.

 We derive the addresses locally. We only use a public service to query each address's balance. Try it out. It's just released:  https://github.com/rotki/rotki/releases/tag/v1.8.1

Props to @prestwich for showing the way.

Verify what I am saying is true by studying the code: https://github.com/rotki/rotki/blob/f8f7f4545c79bad3dbb5e9ace3fe1b380240eaab/rotkehlchen/chain/bitcoin/xpub.py#L98

>  But the app is aimed at Ethereum users who have already adopted the account model, so it is not worse than the existing privacy model for this application

That's not true. We want all crypto users, to use rotki. In the long vision even non-crypto users to utilize the app.

This is why we completely skipped Phase 1 which I described [above](https://github.com/rotki/rotki/issues/808#issuecomment-689182378) since from @kilrau and other people's comments it was clear this was not something they would want to use.

**Comment by outpoints** [comment]
> More accurate to call it a privacy issue. Which is true. But the app is aimed at Ethereum users who have already adopted the account model, so it is not worse than the existing privacy model for this application

Sorry, I'm working so I couldn't articulate properly

**Comment by outpoints** [comment]
> Rotki **does not** use a public service to derive addresses from xpubs.
> 
> We derive the addresses locally. We only use a public service to query each address's balance. Try it out. It's just released: https://github.com/rotki/rotki/releases/tag/v1.8.1

Is it possible to use tor while querying them?
But even if you use tor and send btc to an exchange they'll still have your address. If they wanted to they could see who is querying all those addresses and put those together to find out who owns what.
If you were to use a local indexer it would mitigate the issue entirely.

**Comment by LefterisJP** [comment]
> Is it possible to use tor while querying them?

We have not experimented with rotki querying via Tor.

> If you were to use a local indexer it would mitigate the issue entirely.

It's in our plans to offer the option utilize a local node/indexer for Bitcoin: https://github.com/rotki/rotki/issues/1557. We already do so for Ethereum

> If they wanted to they could see who is querying all those addresses and put those together to find out who owns what.

This is true for all public oracles/websites. There is a lot of stuff that can't be queried locally (especially in the ethereum world) for 99% of the users even if they run a local node. At some point it's really hard to avoid it but you can implement some strategies to confuse would be de-anonymizers: https://github.com/rotki/rotki/issues/817
