### ISSUE TITLE
Bisq support

### ISSUE THREAD

**Issue by t-900-a** [rotki/rotki#824]
## Abstract

Rotki should support import of trades using the decentralized exchange bisq. Bisq does provide a csv export. So maybe it should just support a csv import of bisq's csv formatting?

## Motivation

Bisq is pretty popular so the trades should be imported pretty seamlessly
https://bisq.network/stats/

## Specification

N/A

**Comment by t-900-a** [comment]
Also created bisq issue: https://github.com/bisq-network/bisq/issues/4111

**Comment by LefterisJP** [comment]
Thank you for the issue @t-900-a. We have many exchange integration requests and not as many resources. But we will queue it up.

In general an API key integration is highly preferred. So far we don't offer CSV import for any exchange. This can be naturally added but more work would be needed.

PRs are always appreciated.

**Comment by lorisilva88** [comment]
Attached are some trade history examples as typical csv
[bisqTradeHistoryExamples.csv](https://github.com/rotki/rotki/files/6452534/bisqTradeHistoryExamples.csv)

**Comment by LefterisJP** [comment]
@yabirgb scheduling this for v1.18.0 since I think we can follow same way we did for nexo and blockfi here since a user provided example CSV

**Comment by yabirgb** [comment]
Working on this for 1.23

**Comment by yabirgb** [comment]
@t-900-a A couple of questions that appearing making the implementation:

- The `Fee in BTC` and `Fee in BSQ` is because at some point you could choose the fee currency?
- Buyer deposit and seller deposit are the secuirty deposit right?
- In which currency is the transaction fee denominated?
- In the transaction with id `GxxL` have you modified it? Should be the amount in BTC around 0.18?
- And do you know if the deviation has been already taken into account?

**Comment by lorisilva88** [comment]
Thanks for taking care @yabirgb 
I try to answer the questions:
The structure of the export is still the same as in the trade history examples from May.

> * The `Fee in BTC` and `Fee in BSQ` is because at some point you could choose the fee currency?
Yepp, BSQ is incentivized, you can choose for every trade to use BTC or BSQ (https://bisq.wiki/Trading_BSQ#Why_buy_or_sell_BSQ.3F)

> * Buyer deposit and seller deposit are the secuirty deposit right?
Yepp, they are not relevant from a Tax-Point-of-view after the trade is finished.

> * In which currency is the transaction fee denominated?
BTC

> * In the transaction with id `GxxL` have you modified it? Should be the amount in BTC around 0.18?
Yepp, we obfuscated the numbers, but not consistently, price/amount ratios might make no sense for the given date. Sorry if that was confusing.

> * And do you know if the deviation has been already taken into account?
Yes, the deviation has been already taken into account

**Comment by lorisilva88** [comment]
@yabirgb I found an issue with the bisq importer. For SELLs, instead of the base token amount, the quote token amount is imported.
I.e. those two lines from the bisqTradeHistoryExamples.csv above
xxcz,10 Mar 2021 10:16:00,BTC/EUR,50500.0000,N/A,0.01,505,EUR,0.0001,,0.40,0.0030,0.0030,Sell BTC,Completed
LxxAob,11 Jun 2019 20:21:44,DASH/BTC,0.01541873,3.00%,0.30,19.45685539,DASH,0.000228,0.0009,,0.03,0.03,Sell DASH,Completed

actual result in rotki trade history
SELL | 0.30 | DASH | for | BTC | < 0,02
expected correct result
SELL | 19.45685539 | DASH | for | BTC | < 0,02

and
actual result in rotki trade history
SELL | 505.00 | BTC | for | EUR | 50.500,00
expected currect result
SELL | 0.01 | BTC | for | EUR | 50.500,00

**Comment by yabirgb** [comment]
@lorisilva88 Thanks for reporting it. We changed the logic in the importers and we might have introduced this error. Will take a look and come back to you
