### ISSUE TITLE
Unnecessary checksum check

### ISSUE THREAD

**Issue by koeppelmann** [rotki/rotki#836]
I wanted to add an ETH address.
When I clicked "add" nothing (obvious) happend.
So the first request would be a error message directly near the add button. (and not just a hard to see notification in the top)

The second request: I see now reason why addresses that do not follow the check sum format should be rejected. This is nothing security critical and if the address exists (contains ETH/tokens) it should simply be added?

![Screen Shot 2020-04-04 at 14 13 39](https://user-images.githubusercontent.com/2594089/78450443-e0eff300-767e-11ea-91ac-c185e53ff570.png)

Not sure if/how related to: https://github.com/rotki/rotki/issues/69

**Comment by LefterisJP** [comment]
Hey @koeppelmann thanks for the issue!

@kelsos About the eror message here how can we improve in general on errors seen when running background tasks for a user? Related issue: https://github.com/rotki/rotki/issues/751

@koeppelmann For the checksum I am not sure. At the moment we enforce checksums everywhere in case we start managing user funds in the future, I think it's a good practise. All addresses are saved checksummed in the DB too.

We could just forgive and turn to checksummed address anyway in fields like this since no on-chain action is taken. So you would prefer if we were not enforcing this in the address additions?

**Comment by kelsos** [comment]
The problem I currently see, and we should definitely improve, is that all the validation at the moment happens on the backend. We should implement input field validation providing direct feedback to the user in the input field. 

Since the call adding an account is an asynchronous task, this is the reason the message appears on the notification, the frontend only gets the result when the task resolved, which is not a good experience indeed.

We should evaluate which inputs have specific rules, not only the addresses and we should include a first validation layer in the frontend itself. This provides the benefit of the user being directly notified about any invalid input directly on the fields itself.

In regards to the checksum, we don't have to change anything on the backend, the conversion can happen on the front-end itself and it can still provide the checksummed address to the API. It would certainly make the experience of using Rotki easier. And since Rotki is not a wallet there is no danger. 
After being added the address will be still displayed in checksummed format.

**Comment by LefterisJP** [comment]
> The problem I currently see, and we should definitely improve, is that all the validation at the moment happens on the backend. We should implement input field validation providing direct feedback to the user in the input field.

The problem with such an approach is that the backend is the source of truth. You need to be able to handle any kind of error from the backend and show it properly.

> And since Rotki is not a wallet there is no danger.
After being added the address will be still displayed in checksummed format.

Hmm that's a good idea. Perhaps you can consider doing it as the solution to this issue? We can keep #751 for the showing errors to the user problem.

**Comment by isidorosp** [comment]
> In regards to the checksum, we don't have to change anything on the backend, the conversion can happen on the front-end itself and it can still provide the checksummed address to the API. It would certainly make the experience of using Rotki easier. And since Rotki is not a wallet there is no danger.
> After being added the address will be still displayed in checksummed format.

Is there any danger that auto-converting a non-checksummed address into a checksummed one would possibly lead to an incorrect address? If not, then even in the case where rotki will do more than just querying, what would the risk be?

**Comment by LefterisJP** [comment]
> In this case we're just talking about the uppercasing of some of the letters right?

Yes this is how [EIP55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) implements checksumming.

**Comment by kelsos** [comment]
@LefterisJP 
Having input validation on the frontend doesn't mean we remove the validation from the backend, that would not make sense. But transforming the error messages from the backend to UI errors it not easy. 

It would be easier to evaluate the most important rules from the backend and integrate them in the front-end. Sure it's double effort, but it provides better user experience.

**Comment by isidorosp** [comment]
> > In this case we're just talking about the uppercasing of some of the letters right?
> 
> Yes this is how [EIP55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) implements checksumming.

Don't see any risk in autoconverting it then, and if it's going to autoconvert, shouldn't it just happen in the backend?

**Comment by LefterisJP** [comment]
> But transforming the error messages from the backend to UI errors it not easy.

Hm yes yes. Sorry I think I may have not expressed myself correctly.
Definitely somehow autodetecting that the error that popped up from the backend is for a specific field is going to be hard. For that reason yes it would make sense to have field checks in the frontend.

But the problem I am referring to and I think that @koeppelmann also referred to is that it's hard to realize that the error that the user sees in the notifications is due to a particular task. Perhaps we should make a new issue for it? Or discuss in #751 ?

**Comment by kelsos** [comment]
Sure, we had a discussion before with @isidorosp about displaying some kind of toast or snackbar message when there is a notification to ensure better visibility to the user. We should create an issue and include it in the next release.

**Comment by LefterisJP** [comment]
>  We should create an issue and include it in the next release.

@kelsos sounds good. Can you create such an issue?

**Comment by kelsos** [comment]
Sure I will do in a moment
