### ISSUE TITLE
Improve notifications 

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#840]
## Problem Definition

Currently, notifications are only displayed in the notification area which makes them really easy to miss. We should implement and add a mechanism that shows the notifications for a short period of time to the user. This will make it easier for the user to not miss important notification such as errors.

We need to add [popup notifications](https://en.wikipedia.org/wiki/Pop-up_notification).

We can use the https://vuetifyjs.com/en/components/snackbars/ for the popup notification.

By default, the snackbars are not stacking so we need to evaluate if it makes sense to implement a queue of the messages, or maybe create a summary and show one notification.

**Comment by LefterisJP** [comment]
This issue should be prioritized as the current notifications system is suboptimal and people have complained.

Is this the actionable part of https://github.com/rotki/rotki/issues/751? If yes and if they are related it would be nice to keep only one issue open.

> By default, the snackbars are not stacking so we need to evaluate if it makes sense to implement a queue of the messages, or maybe create a summary and show one notification.

Looking at the example snackbar in your link, I think I have seen vue/react apps with multiple snackbars being thrown at me if some background task errored. Wouldn't that be fine?

On the other hand perhaps we should also rethink the classification of errors shown by the backend. We could have some categories shown to the user via snackbar and some via other less direct means.

Cause we have warnings even if some trade is let's say not processed due to some exchange misbehaving or having an entry we dont' understand. These are problems the user should know (since let's be honest, logs would only be read for debugging a problem), but does not need to worry much or do an immediate action.
