### ISSUE TITLE
Implement a ping endpoint in the back-end API.

### ISSUE THREAD

**Issue by isidorosp** [rotki/rotki#858]
## Abstract

Implement a `ping` endpoint in the back-end API. Use a valid response as the trigger to allow a user to log in.

## Motivation

Currently there is no ideal "minimum path" to know that the backend is up and fully functioning during application initiation. In the front-end we use the `/version` endpoint but that endpoint looks up releases on Github in the background which could either be slow or fail so it's not ideal as a way to establish that the backend API is up and running.

## Specification

A very simple & fast API endpoint with little room for error will be useful in cases where a UI client will want to do any of the following:
* Establish when the API is up and running (i.e. when a client loads, from which point on the user can try to log in)
* Allow for easy way to monitor back-end API status

TODO: Details of specification (files to be edited etc.)

**Comment by LefterisJP** [comment]
@isidorosp Thanks a lot! 

> which could either be slow or fail

Even if it fails the endpoint will still return, but indeed it can be slow since it depends on an external RPC call over a network.

> TODO: Details of specification (files to be edited etc.)

I can help with that. It's everything that's required to create a new endpoint. It should just always return true. You can either wait for me to spec it out or try to see from older PRs or from the code what's required.

If you want to impement it that is. It should be a nice and easy issue to learn new parts of the code.

**Comment by isidorosp** [comment]
> I can help with that. It's everything that's required to create a new endpoint. It should just always return true. You can either wait for me to spec it out or try to see from older PRs or from the code what's required.

Is https://github.com/rotki/rotki/commit/e8e53a398d3ffd4e3b9368cea067e2f65845efb6 a good place to start from in terms of an example on this?

**Comment by LefterisJP** [comment]
@isidorosp yes I would say so!
