### ISSUE TITLE
GBPe on Gnosis chain no longer detected

### ISSUE THREAD

**Issue by benjaminion** [rotki/rotki#8681]
## Problem Definition

Rotki used to find my Monerium GBPe on Gnosis chain but no longer does so.

Observations:
- The GBPe asset exists in Rotki and [the contract address](https://gnosisscan.io/address/0x5Cb9073902F2035222B9749F8fB0c9BFe5527108) for it is correct.
- I have a balance of Gnosis chain GBPe on two of the addresses Rotki tracks. It is no longer showing on either.
    - I have confirmed I have GBPe in that contract by calling its `balanceOf()` function. The balances also show in my wallet.
- The graph on the GBPe asset page shows previous balances up to 1/10/2024.
    - The page says "Data available: 31/03/2024 15:33:57 - 01/10/2024 08:49:43".
    - Under "Asset locations" it shows "No item found", whereas it should show two addresses.
    - "Total owned shows "0.00 GBPe" whereas it should show a balance.
- I upgraded Rotki to 1.35.0 sometime around 2/10/24 19:00 UTC
- I've tried re-decoding all transactions and re-detecting tokens, as well as restarting Rotki etc.
- My other Gnosis chain assets (sDAI, xDAI, GNO) show correctly.

### System Description

Operating system: Windows 11
Rotki version: 1.35.0

**Comment by LefterisJP** [comment]
Hey @benjaminion these stuff are easier debugged in discord:  https://discord.rotki.com/

I think my number 1 hunch as to what is off here is that it got automatically ignored due to the way they credited GBPe (same as EURe) when they did the v2 upgrade.

I think we put an exception for EURe but not sure if we did for GBPe. @yabirgb did we?

So @benjaminion in short:

1. read this: https://docs.rotki.com/usage-guides/assets.html#whitelisting-of-ignored-assets
2. Go to the page for your assets, filter by ignored assets and see if GBPe is there (any of the official ones (v1 or v2)). If yes then both unignore them and add them to the whitelist so the automatic algorithm does not do that again.

**Comment by benjaminion** [comment]
Great! That fixed it. The [newer GBPe](https://gnosisscan.io/address/0x8E34bfEC4f6Eb781f9743D9b4af99CD23F9b7053) had been marked as ignored. This whole multiple GBPe contracts thing is so messed up.

Many thanks! ❤️
