### ISSUE TITLE
If asset of an account is same as main currency the displayed value is off due to double conversion

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#957]
## Problem Definition

This has been a long standing problem in Rotki's UI which we need to address.

If the main currency is the same as the asset of an account entry then the Fiat Value is wrong due to the double conversion of going from USD -> Main Currency Fiat. An example screenshot of the problem with EUR below:

![2020-04-29-175936_1019x112_scrot](https://user-images.githubusercontent.com/1658405/80618239-6038d280-8a43-11ea-8432-63a9a4e2437e.png)

## Task

The backend will always return USD values of each asset. Will not change this. But this should be easily addressable in the frontend. The Fiat value column should have a special rule added. In pseudocode:

```
if main_currency == entry.asset:
    display(entry.amount)
else:
    display(entry.usd_value * main_currency.exchange_rate)
```

Should be trivial to fix.

**Comment by isidorosp** [comment]
As of a 1.4.1 we implemented the AmountDisplay component which is basically a component where you feed it a `value` (amount / usdValue / whatever) and a set of parameters and it will render it appropriately in the UI. This is good because it prevents us from having to repeat things in the front-end code like the decimal formatting, exchange rate application, etc.

For example, if you call it as
`<amount display :value="usdValue" fiat>` it will take the value that you fed it and apply the exchange rate and decimal rounding/cutoff/etc. If you do not include the `fiat` flag, it does not apply an exchange rate. However, the value fed is just a `BigNumber`, so the component doesn't know the "context" of what it's being fed (what the corresponding `amount` or the `asset` properties are for that `asset.usdValue`).

I think we have a few options:
1. Implement the "special rule" suggested above whenever this double-conversion might happen _before_ we feed the relevant `value` into the `<amount display>` component. Right now the only case that comes to mind is when we're talking about fiat balances, is that correct? If so this probably happens in very few places and would require no adjustments to AmountDisplay.
2. We feed the AmountDisplay component extra properties when needed (e.g. if we're displaying an asset that may exhibit this double conversion behavior). In this example we would also supply `amount` and `assetCurrency`, since the component will have a "full picture", it will then check if `assetCurency` == `userCurrency`, and render `amount` instead of `usdValue`, otherwise render `usdValue`.


@kelsos do you see another way? 

What do you guys think?

**Comment by kelsos** [comment]
@isidorosp in your PR with the asset do you already feed the asset symbol in the amount-display?

**Comment by isidorosp** [comment]
The PR as it is right now doesn't address this. The only thing it does is allow you to optionally ask AmountDisplay to render the currency symbol for the rendered value (based on the user's primary currency).
