### ISSUE TITLE
Detect airdrops

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#972]
## Problem Definition

Most aidropped ethereum tokens are scams but there is some which legitimately did airdrops and users may have had the accounts added in the portfolio via an airdrop.

At the moment there is no way to detect this in Rotki.

**The current workaround** is to see when the airdrop happened, see roughly how much you got and then input it as a manual trade with the date and amount set properly. The date is the most important thing here as the software will use it to calculate if any taxes are owed, what the price was when you got it e.t.c.

## Task

For some of the most well known tokens, like `OMG` see if the airdrop can be detected automatically for all of the users accounts and detect it and save them in the DB as trades. (perhaps special trades?) Essentially what the workaround does but done automatically.

**Comment by LefterisJP** [comment]
@kelsos write your ideas about this as we discussed today

**Comment by kelsos** [comment]
As we were discussing today, for airdrops that you care you, if I understand correctly, have to do a manual balance for the report feature to work properly. It would make sense to me after detecting any airdrops to get some kind of "wizard" where I select the airdrops that have actual value to me, and I am guided through the adding o manual balances for the specific airdrops so that the effort of adding them is minimal on my side.

**Comment by LefterisJP** [comment]
Closed by #1985
