### ISSUE TITLE
Fix potential stack overflow error in coinbase pagination

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#974]
## Problem Definition

At the moment the handling of coinbase pagination uses pure recursion of the `api_query()` function.

https://github.com/rotki/rotki/blob/bec6533a5642a5a5a037794fea8613e4a92e1dfe/rotkehlchen/exchanges/coinbase.py#L291-L307

That should work fine for most of the cases of our users.

But if a user has too many trades that the recursion hits the stack limit, Rotki will crash in a not so nice way.

## Task

Handle the potential recursion stack overflow error by using a loop instead.

**Comment by Eshaan7** [comment]
Hi. I am new to this project. Will try to raise a PR for this. The approach I am thinking is:
- extract out the _pagination_ logic into a private method which uses loop (not recursion) and is called from `_api_query`.
- If we use loop, the calculation of sha256 signature and building of `request.Session` instance would be done only once so that's a good thing for performance.
