### ISSUE TITLE
Clean database -- new install on Windows

### ISSUE THREAD

**Issue by vchatela** [rotki/rotki#997]
## Problem Definition
Hello,
I would like to start a new Rotki (with everything clean) but even by deleting .rotkehlchen folder in $USER I still have the issue while importing : 
`Failed to add "deposit of  EUR with id ec38bb0942d5d2031be500cc6d599d6cf881bd2d0e323e1ff26f697e9fcedbbe in external at timestamp 1584109260" to the DB. It already exists.` 

### System Description
Windows 10 using latest v1.4.2 rotki

Thank you

**Comment by LefterisJP** [comment]
Can you share a the logs? What are you trying to do? Are you trying to add a duplicate entry? This is how it looks like.

**Comment by vchatela** [comment]
It is because of #995 . I have adapted the CSV but while trying to import I got this issue.
So I tried to "clean" the database/full app to start from scratch and do the full import.
And I have this appearing.

Log : 
[rotkehlchen.log](https://github.com/rotki/rotki/files/4630646/rotkehlchen.log)

I have checked and there is no duplicated lines in my CSV import.

**Comment by LefterisJP** [comment]
So you delete the database, restart and without doing anything you get this?

Or you try to delete the database and then reimport? Can you share the exact CSV you are trying to import? Are there any entries with the same date? The accuracy of the exported data from cointracking is only up to the minute which can cause these errors.

But generally while working on #995 I noticed they have changed more fields which is why the feature is broken now. We will fix it so that i can work with the data you provided in #955 but this will be included in a next release.

**Comment by vchatela** [comment]
Yeap I fully understand, and again thank you for that !
This issue was more, I don't find how to fully clean the installation. I have deleted the .rotkehlchen folder but I assume there is a cache of the database somewhere else.

So how can I start a "new" rotki on windows ? What do I have to do ?

**Comment by LefterisJP** [comment]
@vchatela I see.

Let's try to understand what you are doing. Let me see if this is correct.

1. You deleted `%HOME/.rotkehlchen` in windows, effectively nuking the DB and every cache rotki keeps.
2. You restarted the application
3. At this point. Did you:
    (a) Create a new user.
    (b) Logged in the old user you had before?
4. Afterwards what did you do? Did you try to import the cointracking CSV import again? And then you saw the `deposit of EUR with id ec38bb0942d5d2031be500cc6d599d6cf881bd2d0e323e1ff26f697e9fcedbbe in external at timestamp 1584109260` error?

If the answer to 3 above is (a), then you are deifnitely using a new database.
If you got the error while doing 4, then please paste all deposit entries you got in the CSV here or send them to me via a private email in lefteris@rotki.com if you prefer.

I suspect the reason is you got entries which are not the same but yet are considered duplicate by rotki since all fields are the same.

**Comment by vchatela** [comment]
You are on it exactly. I have deleted the 'user' folder so I have created a new one.

The CSV is that one : 
```
"","Type","Buy","Cur.","Sell","Cur.","Exchange","Trade Group","Comment","Trade Date"
"","Trade","3300.00000000","CRO","197.01000000","EUR","no exchange","","","14.05.2020 11:46"
"","Deposit","197.01000000","EUR","","","no exchange","","","14.05.2020 11:44"
"","Trade","4784.80000000","CRO","286.57000000","EUR","no exchange","","","14.05.2020 10:54"
"","Trade","0.00120200","BTC","80.00000000","CRO","no exchange","","","14.05.2020 10:44"
"","Trade","2000.00000000","CRO","117.54000000","EUR","no exchange","","","11.05.2020 21:58"
"","Deposit","117.54000000","EUR","","","no exchange","","","11.05.2020 21:06"
"","Trade","197.17000000","EUR","0.02300000","BTC","no exchange","","","06.05.2020 23:32"
"","Trade","89.40000000","EUR","18.51000000","MCO","no exchange","","","02.05.2020 13:51"
"","Withdrawal","","","0.57000000","EUR","no exchange","","","29.03.2020 11:20"
"","Trade","0.01310000","BTC","80.30000000","EUR","no exchange","","","25.03.2020 12:15"
"","Trade","1.00000000","ETH","119.13000000","EUR","no exchange","","","19.03.2020 13:22"
"","Deposit","200.00000000","EUR","","","no exchange","","","19.03.2020 08:10"
"","Trade","0.05000000","BTC","259.96000000","EUR","no exchange","","","13.03.2020 15:44"
"","Trade","18.51347874","MCO","0","EUR","no exchange","","","13.03.2020 15:23"
"","Trade","50.00000000","MCO","128.54000000","EUR","no exchange","","","13.03.2020 15:22"
"","Deposit","259.96000000","EUR","","","no exchange","","","13.03.2020 14:21"
"","Deposit","128.54000000","EUR","","","no exchange","","","13.03.2020 14:21"
```

I don't see any duplicate but two line with same timestamp. Which is possible in the same minute.. Is that the issue so ?

**Comment by LefterisJP** [comment]
yes this is the issue. There is no point in importing deposits for no exchange anyway if they have no fees. They are not used anywhere in rotki in this form.

The problem is that cointracking exports data **only** up to the minute. You probably did those deposits in different seconds. But we look at them and check timestamp + type + unique identifier of the exchange, which cointracking does not export to figure out a UUID for each row.

So these two rows appear the same. This would not be a problem if we supported crypto.com and rotki pulled data directly from there.

But as I said you can safely delete them. They will not be used at all in this form. Or ... if you want you can just consolidate them manually to one entry.

**Comment by vchatela** [comment]
I think they have improved their export as now there is the second.
I had removed them while searching what was wrong with the import but maybe second is not an issue.

Understood so I propose you as I already gave you the CSV export in the other issue (#995) then not need to keep this track open.

Thank you again that's very nice.

**Comment by LefterisJP** [comment]
> I think they have improved their export as now there is the second.

They have? This is important information. If yes, please tell me now. The CSV you gave me, and the old CSV I have when testing before is only up to the minute. Example: `13.03.2020 14:21`.

If they have change this format I need to know, or else we will have problems importing data from them again.

**Comment by vchatela** [comment]
Of course I understand. On the issue #995 I paste the real export which contains seconds.

You can take it as correct source
